force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoyaltyTransactionTriggerHandler.cls
/*********************************************************************
Name    :       Loyalty Transaction Trigger Handler
Date    :       29 April 2020
Author  :       Miguel Paguio
Description:    Trigger handler of Loyalty Transaction for Loyalty_Transaction__c Object
History :       
*********************************************************************/

public class LoyaltyTransactionTriggerHandler {
  //calls all methods Before Insert
  public static void onBeforeInsert(
    List<Loyalty_Transaction__c> loyaltyTransactionList
  ) {
    customerContact(loyaltyTransactionList);
  }

  public static void onAfterInsert(
    List<Loyalty_Transaction__c> loyaltyTransactionList
  ) {
  }
  public static void customerContact(
    List<Loyalty_Transaction__c> loyaltyTransactionList
  ) {
    Set<Id> accIds = new Set<Id>();
    for (Loyalty_Transaction__c transList : loyaltyTransactionList) {
      accIds.add(transList.Loyalty_Consumer__c);
    }
    if (!accIds.isEmpty()) {
      Map<Id, Account> accMap = new Map<Id, Account>(
        [SELECT PersonContactId FROM Account WHERE Id IN :accIds]
      );
      for (Loyalty_Transaction__c ltyTrans : loyaltyTransactionList) {
        ltyTrans.Contact__c = accMap.get(ltyTrans.Loyalty_Consumer__c)
          .PersonContactId;
      }
    }
  }
}