force-app/main/default/objects/Charity__c/Charity__c.object-meta.xml
<CustomObject>
    <label>Charity</label>
    <nameField>
        <label>Charity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Charity__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Donation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Charity__c.field-meta.xml
<CustomField>
    <fullName>Charity__c</fullName>
    <label>Charity</label>
    <referenceTo>Charity__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donated_Points__c.field-meta.xml
<CustomField>
    <fullName>Donated_Points__c</fullName>
    <label>Donated Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/DonorContact__c.field-meta.xml
<CustomField>
    <fullName>DonorContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DonorContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Loyalty_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Transaction</label>
    <referenceTo>Loyalty_Transaction__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Has_Charity__c.field-meta.xml
<CustomField>
    <fullName>Has_Charity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Charity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyDonationBuilder.cls
public without sharing class LoyaltyDonationBuilder{
    
    //Loyalty Transaction related:
    private String loyaltyId; 
    private String loyaltyConsumer; 
    private Integer transactionAmount;
    private String transactionType;
    private String loyaltySource;
    private Boolean hasCharity;
    
    //Donation Related:
    private Integer donatedPoints; 
    private String donorId;
    private String charityId; 
    private String transactionId;
    private String contactId;
    
    public LoyaltyDonationBuilder setLoyaltyId(String loyaltyId){
        Loyalty__c loyRec = [SELECT Id FROM Loyalty__c WHERE External_ID__c = :loyaltyId LIMIT 1];
        this.loyaltyId = loyRec.Id;
        return this;
    }
    
    public LoyaltyDonationBuilder setLoyaltyConsumer(String loyaltyConsumer){
        this.loyaltyConsumer = loyaltyConsumer;
        return this;
    }
    
    public LoyaltyDonationBuilder setTransactionAmount(Integer transactionAmount){
        this.transactionAmount = transactionAmount;
        return this;
    }
    
    public LoyaltyDonationBuilder setTransactionType(String transactionType){
        this.transactionType = transactionType;
        return this;
    }
    
    public LoyaltyDonationBuilder setLoyaltySource(String loyaltySource){
        this.loyaltySource = loyaltySource;
        return this;
    }
    
    public LoyaltyDonationBuilder setHasCharity(Boolean hasCharity){
        this.hasCharity = hasCharity;
        return this;
    }
    
    public LoyaltyDonationBuilder setDonatedPoints(Integer donatedPoints){
        this.donatedPoints = donatedPoints;
        return this;
    }
    
    public LoyaltyDonationBuilder setDonorId(String donorId){
        this.donorId = donorId;
        return this;
    }
    
    public LoyaltyDonationBuilder setCharityId(String charityId){
        Charity__c chaRec = [SELECT Id FROM Charity__c WHERE External_ID__c = :charityId LIMIT 1];
        this.charityId = chaRec.Id;
        return this;
    }
    
    public LoyaltyDonationBuilder setTransactionId(String transactionId){
        this.transactionId = transactionId;
        return this;
    }
    
    public LoyaltyDonationBuilder setContactId(String contactId){
        Loyalty_Transaction__c ltyRec = [SELECT Id, Contact__c FROM Loyalty_Transaction__c WHERE Id = :contactId LIMIT 1];
        this.contactId = ltyRec.Contact__c;
        return this;
    }
    
    public Loyalty_Transaction__c transactionbuild(){
        Loyalty_Transaction__c t = new Loyalty_Transaction__c();
        
        if(String.isNotEmpty(this.loyaltyId)){
            t.Loyalty__c = this.loyaltyId;
        }
        if(String.isNotEmpty(this.loyaltyConsumer)){
            t.Loyalty_Consumer__c = this.loyaltyConsumer;
        }
        if(this.transactionAmount != null){
            t.Transaction_Amount__c = this.transactionAmount;
        }
        if(String.isNotEmpty(this.transactionType)){
            t.Loyalty_Transaction_Type__c	= 'Redeem';
        }
        if(String.isNotEmpty(this.loyaltySource)){
            t.Loyalty_Source__c = this.loyaltySource;
        }
        if(this.hasCharity != null){
            t.Has_Charity__c = this.hasCharity;
        }
        return t;
    }
    
    public Donation__c donationbuild(){
        Donation__c d = new Donation__c();
        if(this.donatedPoints != null){
            d.Donated_Points__c = this.donatedPoints;
        }
        if(String.isNotEmpty(this.donorId)){
            d.Donor__c = this.donorId;
        }
        if(String.isNotEmpty(this.charityId)){
            d.Charity__c = this.charityId;
        }
        if(String.isNotEmpty(this.transactionId)){
            d.Loyalty_Transaction__c = this.transactionId;
        }
        if(String.isNotEmpty(this.contactId)){
            d.DonorContact__c = this.contactId;
        }
        return d;
    }
}