force-app/main/default/objects/Community_Consent_Label__mdt/Community_Consent_Label__mdt.object-meta.xml
<CustomObject>
    <label>Community Consent Label</label>
    <pluralLabel>Community Consent Labels</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_1__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_1__c</fullName>
    <label>Consent Text 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_2__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_2__c</fullName>
    <label>Consent Text 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_3__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_3__c</fullName>
    <label>Consent Text 3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Consent Text Version</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_Label__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Label__c</fullName>
    <label>Privacy Policy Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_URL__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_URL__c</fullName>
    <label>Privacy Policy URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunityConsentLabelsSelector.cls
public class CommunityConsentLabelsSelector {
  public static List<Community_Consent_Label__mdt> getCommunityConsentLabelsForCommunity(
    String communityName,
    String country
  ) {
    return [
      SELECT
        Id,
        DeveloperName,
        Label,
        Consent_Text_1__c,
        Consent_Text_2__c,
        Consent_Text_3__c,
        Consent_Text_Version__c,
        Privacy_Policy_URL__c,
        Privacy_Policy_Label__c,
        Privacy_Policy_Version__c,
        Country__c
      FROM Community_Consent_Label__mdt
      WHERE Label = :communityName AND Country__c = :country
    ];
  }

  public static Map<String, Community_Consent_Label__mdt> getCommunityConsentLabels() {
    List<Community_Consent_Label__mdt> consentLabels = [
      SELECT
        Id,
        DeveloperName,
        Label,
        Consent_Text_1__c,
        Consent_Text_2__c,
        Consent_Text_3__c,
        Consent_Text_Version__c,
        Privacy_Policy_URL__c,
        Privacy_Policy_Label__c,
        Privacy_Policy_Version__c,
        Country__c
      FROM Community_Consent_Label__mdt
    ];

    Map<String, Community_Consent_Label__mdt> consentLabelsByName = new Map<String, Community_Consent_Label__mdt>();
    for (Community_Consent_Label__mdt consentLabel : consentLabels) {
      consentLabelsByName.put(consentLabel.Label, consentLabel);
    }

    return consentLabelsByName;
  }
}