force-app/main/default/objects/Survey_Campaign_Profile__c/Survey_Campaign_Profile__c.object-meta.xml
<CustomObject>
    <label>Survey Campaign Profile</label>
    <nameField>
        <displayFormat>SCP-{00000}</displayFormat>
        <label>Survey Campaign Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Campaign Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Campaign_Profile__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Survey Campaign Profiles</relationshipLabel>
    <relationshipName>Survey_Campaign_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Campaign_Profile__c/fields/campaignprofileid__c.field-meta.xml
<CustomField>
    <fullName>campaignprofileid__c</fullName>
    <externalId>true</externalId>
    <label>campaignprofileid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Survey_Campaign_Profile__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Campaign Profiles</relationshipLabel>
    <relationshipName>Survey_Campaign_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyCampaignProfileSelector.cls
/**
* All Survey Campaign Profile related SOQL queries
*
* @author tim.dirckx@emark.com
*/
public with sharing class SurveyCampaignProfileSelector {
    
    public static List<Survey_Campaign_Profile__c> findUnique(String campaignProfileId, Id campaignId, Id personContactId) {
        return [SELECT Id FROM Survey_Campaign_Profile__c WHERE campaignprofileid__c = :campaignProfileId AND CampaignId__c = :campaignId AND ContactId__c = :personContactId];
    }
}