force-app/main/default/objects/OCI_Commerce_API__c/OCI_Commerce_API__c.object-meta.xml
<CustomObject>
    <label>OCI Commerce API</label>
    <nameField>
        <label>OCI Commerce API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCI Commerce API</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCI_Commerce_API__c/fields/deltaToken__c.field-meta.xml
<CustomField>
    <fullName>deltaToken__c</fullName>
    <description
  >The token returned when fetching availability. By passing this token, a delta since the previous fetch is returned.
If empty, the full availability is returned.</description>
    <inlineHelpText
  >The token returned when fetching availability. By passing this token, a delta since the previous fetch is returned.
If empty, the full availability is returned.</inlineHelpText>
    <label>deltaToken</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OCI_Commerce_API__c/fields/exportID__c.field-meta.xml
<CustomField>
    <fullName>exportID__c</fullName>
    <description>ID to retrieve the requested availability export from OCI. If empty or expired, it will be set by an export request.</description>
    <inlineHelpText>ID to retrieve the requested availability export from OCI. If empty or expired, it will be set by an export request.</inlineHelpText>
    <label>exportID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Commerce_API__c/fields/organisationID__c.field-meta.xml
<CustomField>
    <fullName>organisationID__c</fullName>
    <description>The organisationId of this org that needs to be passed to OCI. Can&apos;t be fetched programmatically directly, but is available as &apos;TenantId&apos; at /lightning/setup/OmniChannelInventory/home</description>
    <inlineHelpText>The organisationId of this org that needs to be passed to OCI. Can&apos;t be fetched programmatically directly, but is available as &apos;TenantId&apos; at /lightning/setup/OmniChannelInventory/home</inlineHelpText>
    <label>organisationID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Stock__c/OCI_Stock__c.object-meta.xml
<CustomObject>
    <description>Internal representation of OCI stock positions</description>
    <label>OCI Stock</label>
    <nameField>
        <label>sku@location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCI Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCI_Stock__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <description>hidden external id field (equal to name)</description>
    <externalId>true</externalId>
    <label>id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OCI_Stock__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>OCI Stock</relationshipLabel>
    <relationshipName>OCI_Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OCI_Stock__c/fields/safetyStockCount__c.field-meta.xml
<CustomField>
    <fullName>safetyStockCount__c</fullName>
    <description
  >Amount of safety stock kept for this SKU in this warehouse</description>
    <label>Safety stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCI_Stock__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OCI/OCITestDataFactory.cls
public with sharing class OCITestDataFactory {
  public static List<OCI_Stock__c> createOCIStockTestData(
    Integer numberOfRecords
  ) {
    Schema.Location loc = new Schema.Location(
      name = 'Test Location',
      externalReference = 'Test Location'
    );
    insert loc;
    List<OCI_Stock__c> stockRecords = new List<OCI_Stock__c>();
    for (Integer i = 0; i < numberOfRecords; i++) {
      OCI_Stock__c stock = new OCI_Stock__c(
        id__c = 'Test Stock ' + i,
        Name = 'Test Stock ' + i,
        SKU__c = 'SKU-' + i,
        location__c = loc.id,
        safetyStockCount__c = i
      );
      stockRecords.add(stock);
    }
    insert stockRecords;
    return stockRecords;
  }

  public static OCI_Commerce_API__c createOCICommerceAPITestData(
    String deltaToken,
    String exportId
  ) {
    OCI_Commerce_API__c apiSettings = new OCI_Commerce_API__c(
      organisationID__c = 'Test Org ID',
      deltaToken__c = deltaToken,
      exportID__c = exportId
    );
    insert apiSettings;
    return apiSettings;
  }
}