force-app/main/default/objects/Brewer_Registration__c/Brewer_Registration__c.object-meta.xml
<CustomObject>
    <label>Brewer Registration</label>
    <nameField>
        <label>Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brewer Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brewer_Registration__c/fields/Account_Commercial_Consent__c.field-meta.xml
<CustomField>
    <fullName>Account_Commercial_Consent__c</fullName>
    <description>Added for the CLM Flow</description>
    <formula>TEXT( Customer__r.Consent_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Commercial Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/CLM_Welcome_Mail_Sent__c.field-meta.xml
<CustomField>
    <fullName>CLM_Welcome_Mail_Sent__c</fullName>
    <description>For welcome email journeys</description>
    <label>CLM Welcome Mail Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Consumer_Country__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Country__c</fullName>
    <description>Added to make the CLM Flow working</description>
    <formula>TEXT( Customer__r.Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumer Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Send_Welcome_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Welcome_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Welcome Email?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_Flow_CountryBrand__mdt/CLM_Flow_CountryBrand__mdt.object-meta.xml
<CustomObject>
    <label>CLM Flow Country and Brand</label>
    <pluralLabel>CLM Flow Countries and Brands</pluralLabel>
</CustomObject>

force-app/main/default/objects/CLM_Flow_CountryBrand__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Senseo</fullName>
                <default>true</default>
                <label>Senseo</label>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L&apos;Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Saimaza</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Jacqmotte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLM_Flow_CountryBrand__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Countries for which the CLM Flow applies</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NL</fullName>
                <default>true</default>
                <label>NL</label>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IRE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RU</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLM_Flow_CountryBrand__mdt/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bosch</fullName>
    </customValue>
    <customValue>
        <fullName>Cadbury</fullName>
    </customValue>
    <customValue>
        <fullName>Carte Noire</fullName>
    </customValue>
    <customValue>
        <fullName>Costa</fullName>
    </customValue>
    <customValue>
        <fullName>Evergood</fullName>
    </customValue>
    <customValue>
        <fullName>Friele</fullName>
    </customValue>
    <customValue>
        <fullName>Gevalia</fullName>
    </customValue>
    <customValue>
        <fullName>Grand Mere</fullName>
    </customValue>
    <customValue>
        <fullName>Hag</fullName>
    </customValue>
    <customValue>
        <fullName>Jacobs</fullName>
    </customValue>
    <customValue>
        <fullName>Kenco</fullName>
    </customValue>
    <customValue>
        <fullName>Koziol</fullName>
    </customValue>
    <customValue>
        <fullName>L&apos;Or</fullName>
    </customValue>
    <customValue>
        <fullName>Let</fullName>
    </customValue>
    <customValue>
        <fullName>Marabou</fullName>
    </customValue>
    <customValue>
        <fullName>Marcilla</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell House</fullName>
    </customValue>
    <customValue>
        <fullName>Milka</fullName>
    </customValue>
    <customValue>
        <fullName>Oreo</fullName>
    </customValue>
    <customValue>
        <fullName>Ritzenhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Suchard</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo</fullName>
    </customValue>
    <customValue>
        <fullName>Twinings</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Senseo</fullName>
    </customValue>
    <customValue>
        <fullName>Douwe Egberts</fullName>
    </customValue>
    <customValue>
        <fullName>Pickwick</fullName>
    </customValue>
    <customValue>
        <fullName>Maison du Café</fullName>
    </customValue>
    <customValue>
        <fullName>Jacqmotte</fullName>
    </customValue>
    <customValue>
        <fullName>Illy</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLMTriggerFlowClass.cls
public class CLMTriggerFlowClass 
{
	public static void CLMTriggerFlow(List<Brewer_Registration__C> lBrewerRegistrations)
    {
        List<Id> lBrewerRegistrationsinCLM = new List<Id>();
        // Countries and Brands for which the CLM Flow applies
        List<CLM_Flow_CountryBrand__mdt> CountryBrandMD = [SELECT Id, Country__c, Brand__c, Active__c, Start_Date__c FROM CLM_Flow_CountryBrand__mdt WHERE Active__c = TRUE];
        Map<String,CLM_Flow_CountryBrand__mdt> CountryBrandMap = new Map<String,CLM_Flow_CountryBrand__mdt>();
		for(CLM_Flow_CountryBrand__mdt CBMD : CountryBrandMD)
        {	
    		CountryBrandMap.put(CBMD.Country__c+CBMD.Brand__c,CBMD);
		}
        for (Brewer_Registration__C oBrewerRegistration : lBrewerRegistrations)
    	{
            system.debug('Account_Commercial_Consent__c'+oBrewerRegistration.Account_Commercial_Consent__c);
            // Added Condition to only send if commercial consent status is active
            if (oBrewerRegistration.Account_Commercial_Consent__c == 'Active')
            {
            	system.debug('oBrewerRegistration.CLM_Welcome_Mail_Sent__c'+oBrewerRegistration.CLM_Welcome_Mail_Sent__c);
                // Condition to only allow the CLM flow to be sent once
                if (oBrewerRegistration.CLM_Welcome_Mail_Sent__c == null)
                {
                    system.debug('CountryBrandMap.containsKey(oBrewerRegistration.Country__c+oBrewerRegistration.Brand__c)'+CountryBrandMap.containsKey(oBrewerRegistration.Country__c+oBrewerRegistration.Brand__c));
                    // Condition to check on brand and Country, only specific country/brands are allowed
                    if (CountryBrandMap.containsKey(oBrewerRegistration.Consumer_Country__c+oBrewerRegistration.Brand__c))
                    {	
                       	// Condition to only allow brewer registrations as of the start date of the CLM Flow
                        Date dCLMStartdate = CountryBrandMap.get(oBrewerRegistration.Consumer_Country__c+oBrewerRegistration.Brand__c).Start_Date__c;
                        system.debug('dCLMStartdate'+dCLMStartdate);
                        if (oBrewerRegistration.CreatedDate >= dCLMStartdate)
            			{
                            // Add Brewer Registration to List as input for interface
                            lBrewerRegistrationsinCLM.add(oBrewerRegistration.Id);
                            system.debug(oBrewerRegistration.Id);
                    	}
                	}
           		}
            }
        }
        system.debug('lBrewerRegistrationsinCLM.size()'+lBrewerRegistrationsinCLM.size());
        if (lBrewerRegistrationsinCLM.size()>0)
        {
            UpdateBrewerRegistrationsCLM(lBrewerRegistrationsinCLM);
            system.debug('Call Interface');
        }
    }

    @future
    public static void UpdateBrewerRegistrationsCLM(List<ID> lBrewerRegistrationsinCLMids)
    {
        List<Brewer_Registration__C> lBrewerRegsUpdate = [SELECT Id, CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c,Consumer_Country__c FROM Brewer_Registration__C WHERE Id in: lBrewerRegistrationsinCLMids]; 
        for (Brewer_Registration__C BR : lBrewerRegsUpdate)
        {
            // Empty Quick Message
            BR.CLM_Welcome_Mail_Sent__c = system.today();
            BR.Send_Welcome_Email__c = true;
        }
        update lBrewerRegsUpdate;
    }
}