force-app/main/default/objects/OCI_Stock__c/OCI_Stock__c.object-meta.xml
<CustomObject>
    <description>Internal representation of OCI stock positions</description>
    <label>OCI Stock</label>
    <nameField>
        <label>sku@location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCI Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCI_Stock__c/fields/LocExtRef__c.field-meta.xml
<CustomField>
    <fullName>LocExtRef__c</fullName>
    <description>The name of the warehouse as used externally</description>
    <label>Location External Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Stock__c/fields/safetyStockCount__c.field-meta.xml
<CustomField>
    <fullName>safetyStockCount__c</fullName>
    <description
  >Amount of safety stock kept for this SKU in this warehouse</description>
    <label>Safety stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OCI/OCIStockTriggerHelper.cls
public with sharing class OCIStockTriggerHelper {
  public static void handleAfterUpdate(
    List<OCI_Stock__c> newStockItems,
    Map<Id, OCI_Stock__c> oldStockItems
  ) {
    Set<String> locations = new Set<String>();

    for (OCI_Stock__c stockItem : newStockItems) {
      OCI_Stock__c oldStockItem = oldStockItems.get(stockItem.Id);

      if (stockItem.SafetyStockCount__c != oldStockItem.SafetyStockCount__c) {
        locations.add(stockItem.LocExtRef__c);
      }
    }

    if (!locations.isEmpty() && locations.size() < 100) {
      // todo: bulkify for unlikely usecase of updating for more than 100 locations in one go.
      for (String location : locations) {
        OCICommerceAPI.updateSafetyStockToOCI(location);
        OCICommerceAPI.requestRefresh(location);
      }
    }
  }
}