force-app/main/default/objects/Account/fields/Account_Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Source_URL__c</fullName>
    <label>Account Consent Registration Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Date__c</fullName>
    <label>Account Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Email__c</fullName>
    <label>Account Registration Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Source__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Source__c</fullName>
    <label>Account Registration Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intershop</fullName>
            </value>
            <value>
                <fullName>Sampling Form</fullName>
            </value>
            <value>
                <fullName>External Database</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Local Database</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>DE.NL</fullName>
            </value>
            <value>
                <fullName>MDC.FR</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brewers_Selected__c.field-meta.xml
<CustomField>
    <fullName>Brewers_Selected__c</fullName>
    <description
  >Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</description>
    <inlineHelpText
  >Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</inlineHelpText>
    <label>Brewers Selected</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brewers_selected</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Source_URL__c</fullName>
    <label>Commercial Consent Reg. Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text__c</fullName>
    <label>Commercial Consent Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Commercial Consent Text Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Source__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Source__c</fullName>
    <label>Opt-in Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intershop</fullName>
            </value>
            <value>
                <fullName>Sampling Form</fullName>
            </value>
            <value>
                <fullName>External Database</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Local Database</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
            <value>
                <fullName>Pro-Campaign</fullName>
            </value>
            <value>
                <fullName>Zeta</fullName>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>DE.NL</fullName>
            </value>
            <value>
                <fullName>Zeta.Mein.Senseo</fullName>
            </value>
            <value>
                <fullName>serviceplan.mein.senseo</fullName>
            </value>
            <value>
                <fullName>MDC.FR</fullName>
            </value>
            <value>
                <fullName>BBDO</fullName>
                <isActive>false</isActive>
                <label>BBDO</label>
            </value>
            <value>
                <fullName>Blokker</fullName>
                <isActive>false</isActive>
                <label>Blokker</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Summary__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Summary__c</fullName>
    <label>Privacy Policy Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/Community_Consent_Label__mdt.object-meta.xml
<CustomObject>
    <label>Community Consent Label</label>
    <pluralLabel>Community Consent Labels</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_1__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_1__c</fullName>
    <label>Consent Text 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_2__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_2__c</fullName>
    <label>Consent Text 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_3__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_3__c</fullName>
    <label>Consent Text 3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Consent Text Version</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_Label__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Label__c</fullName>
    <label>Privacy Policy Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_URL__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_URL__c</fullName>
    <label>Privacy Policy URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Community_Consent_Label__mdt/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Brewers_selected.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Capsule Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>SENSEO Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Automatique Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Expresso Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Other pad/capsule Coffee appliance</fullName>
    </customValue>
    <customValue>
        <fullName>Filter coffee pot</fullName>
    </customValue>
    <customValue>
        <fullName>Other coffee pot</fullName>
    </customValue>
    <customValue>
        <fullName>I do not have a brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Machine L&apos;OR Barista</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo</fullName>
        <isActive>false</isActive>
        <label>Tassimo</label>
    </customValue>
    <customValue>
        <fullName>Senseo</fullName>
        <isActive>false</isActive>
        <label>Senseo</label>
    </customValue>
    <description>Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</description>
    <masterLabel>Brewers selected</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>CATALAN</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian Nynorsk</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Ukrainian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MdCCommunityHelper.cls
public without sharing class MdCCommunityHelper {
  public static User createUser(
    String email,
    String firstName,
    String lastName,
    String birthdate,
    String postCode,
    String streetName,
    String houseNumber,
    String city,
    String country,
    String networkId,
    String usernamePostfix
  ) {
    User communityUser = new User();
    communityUser.UserName = email + usernamePostfix;
    communityUser.Email = email;

    communityUser.FirstName = firstname;
    communityUser.LastName = lastname;

    communityUser.PostalCode = postcode;
    communityUser.Street = ((streetName != null &&
      houseNumber != null)
      ? streetName + ':' + houseNumber
      : (streetName != null &&
          houseNumber == null)
          ? streetName
          : (streetName != null && houseNumber != null) ? houseNumber : '');
    communityUser.City = city;
    communityUser.Country = country;

    String nickname =
      ((firstname != null &&
        firstname.length() > 0)
        ? firstname.substring(0, 1)
        : '') + lastname.substring(0, 1);
    nickname += String.valueOf(Crypto.getRandomInteger()).substring(1, 7);
    communityUser.CommunityNickname = nickname;

    return communityUser;
  }

  public static Account createAccount(
    String firstName,
    String lastName,
    String email,
    String gender,
    String birthdate,
    String postcode,
    String houseNumber,
    String streetName,
    String city,
    String country,
    String applianceOwnership,
    Boolean sixTnYrsOld,
    Boolean commercialConsent,
    String networkId,
    String brandName
  ) {
    Account communityAccount = new Account(
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Person Account')
        .getRecordTypeId(),
      FirstName = firstName,
      LastName = lastName,
      PersonEmail = email,
      Gender__pc = gender,
      //PersonBirthdate = Date.valueOf(birthdate),
      BillingPostalCode = postcode,
      BillingStreet = ((streetName != null &&
        houseNumber != null)
        ? streetName + ':' + houseNumber
        : (streetName != null &&
            houseNumber == null)
            ? streetName
            : (streetName != null && houseNumber != null) ? houseNumber : ''),
      BillingCity = String.isNotBlank(city) ? city : null,
      BillingCountry = country,
      Country__c = country,
      Brewers_Selected__c = applianceOwnership,
      Sixteen_Years_or_Older__c = sixTnYrsOld,
      External_id__c = email + 'FR' + brandName,
      Brand__c = brandName,
      OwnerId = Label.CommunityOwnerID,
      Language__c = 'French',
      Type__c = 'Loyalty',
      Account_Consent_Registration_Source_URL__c = Network.getSelfRegUrl(
        networkId
      ),
      Account_Registration_Status__c = 'Active',
      Account_Registration_Date__c = System.today(),
      Account_Registration_Email__c = email,
      Account_Registration_Source__c = 'MDC.FR'
    );
    if (String.isNotBlank(birthdate)) {
      communityAccount.PersonBirthdate = Date.valueOf(birthdate);
    }
    if (commercialConsent) {
      List<Community_Consent_Label__mdt> consentLabels = CommunityConsentLabelsSelector.getCommunityConsentLabelsForCommunity(
        'Maison du Cafe',
        'FR'
      );
      communityAccount.Consent_Text__c =
        consentLabels[0].Consent_Text_1__c +
        '\n' +
        consentLabels[0].Consent_Text_2__c +
        ' ' +
        consentLabels[0].Privacy_Policy_Label__c +
        ' ' +
        consentLabels[0].Privacy_Policy_URL__c +
        ' ' +
        consentLabels[0].Consent_Text_3__c;
      communityAccount.Consent_Text_Version__c = String.valueOf(
        consentLabels[0].Consent_Text_Version__c
      );
      communityAccount.Privacy_Policy_Version__c = String.valueOf(
        consentLabels[0].Privacy_Policy_Version__c
      );
      communityAccount.Privacy_Policy_Summary__c = String.valueOf(
        consentLabels[0].Privacy_Policy_Version__c
      );
      communityAccount.Consent_Registration_Source_URL__c = Network.getSelfRegUrl(
        networkId
      );
      communityAccount.Opt_in_Source__c = 'MDC.FR';
      communityAccount.Consent_Status__c = 'Registered';
      communityAccount.Consent_Registration_Date__c = System.today();
      communityAccount.Account_Consent_Registration_Date__c = System.now();
      communityAccount = ConsumerAttributes.generateOPTURLS2(
        new List<Account>{ communityAccount }
      )[0];
    }

    insert communityAccount;
    return communityAccount;
  }

  /*public static void addRegistrationToMdcCampaign(Account customer) {
        Campaign mdcCampaign = findOrCreateMdcCampaign();
        Account accountWithContactId = AccountSelector.getAccountExternalId(customer.Id);
        CampaignMember registrationMember = new CampaignMember(
            ContactId = accountWithContactId.PersonContactId,
            Customer_External_Id__c = accountWithContactId.External_Id__c,
            CampaignId = mdcCampaign.Id,
            Status = 'Registered'
        );
        if(registrationMember != null){
            insert registrationMember;
        }   
    }
    
    public static Campaign findOrCreateMdcCampaign() {
        Campaign mdcCampaign = CampaignSelector.getCampaignByExternalId('Maison du Café-FR-MdCRegistration');
        if(mdcCampaign == null){
            mdcCampaign = new Campaign(
                Name = 'MdCRegistration',
                Campaign_Type__c = 'Registration',
                Brand__c = 'Maison du Café',
                Country__c = 'FR'
            );
            if(mdcCampaign != null){
                insert mdcCampaign;
            }
        }
        return mdcCampaign;
    }*/
}