force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_clicked__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_clicked__c</fullName>
    <label>Last E-mail clicked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_opened__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_opened__c</fullName>
    <label>Last E-mail opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_For_NoEmailSentToCustomer__c.field-meta.xml
<CustomField>
    <fullName>Days_For_NoEmailSentToCustomer__c</fullName>
    <label>Days For NoEmailSentToCustomer</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CLNRules_NoEmailSentUnsubscribeTest.cls
@isTest
public class CLNRules_NoEmailSentUnsubscribeTest {
  @IsTest
  private static void testNoEmailSentCustomer() {
    Cleanup_Rules_Settings__c CLN_Settings = new Cleanup_Rules_Settings__c(
      SetupOwnerId = UserInfo.getOrganizationId()
    );
    CLN_Settings.Days_For_NoEmailSentToCustomer__c = 0;
    insert CLN_Settings;
    date testDate = Date.TODAY().addMonths(-25);

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    List<Account> accList = new List<Account>();
    for (integer x = 0; x < 10; x++) {
      Account acct = TestDataBuilder.createAccount();
      acct.recordTypeId = recordTypeId;
      acct.CurrencyISOCode = 'EUR';
      acct.Deletion_Flag__c = false;
      acct.Account_Registration_Status__c = 'Deactivated';
      acct.Last_Email_Send_Date__pc = testDate;
      acct.Last_Email_clicked__c = testDate;
      acct.Last_Email_opened__c = testDate;
      acct.Consent_Status__c = 'Active';
      acct.Type__c = 'Registered';
      accList.add(acct);
    }
    insert accList;

    for (Account ac : accList) {
      Test.setCreatedDate(ac.Id, testDate);
    }

    Test.startTest();
    CLNRules_NoEmailSentUnsubscribe testBatch = new CLNRules_NoEmailSentUnsubscribe();
    DataBase.executeBatch(testBatch);
    Test.stopTest();

    List<Account> checkAccountList = [
      SELECT Id, Deletion_Flag__c, Last_Email_Send_Date__pc, Consent_Status__c
      FROM Account
    ];
    System.debug(checkAccountList);
    for (Account acc : checkAccountList) {
      system.assert(acc.Consent_Status__c == 'Expired');
    }
  }
}