force-app/main/default/objects/Account/fields/Account_Deletion_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Deletion_Date__c</fullName>
    <label>Account Deactivation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Withdrawn_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Withdrawn_Date__c</fullName>
    <label>Commercial Consent Withdrawn Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Reason__c</fullName>
    <label>Deletion Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Double_Opt_in_Email_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_in_Email_Send_Date__c</fullName>
    <label>Double Opt-in Email Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Double_Opt_in_Reminder_Email_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_in_Reminder_Email_Send_Date__c</fullName>
    <label>Double Opt-in Reminder Email Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Double_Opt_in_Reminder_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_in_Reminder_Send_Date__c</fullName>
    <formula
  >TEXT(DATEVALUE( Double_Opt_in_Reminder_Email_Send_Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Double Opt-in Reminder Send Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Request_to_be_Forgotten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request to be Forgotten</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_for_Consumer_Deletes_Account__c.field-meta.xml
<CustomField>
    <fullName>Days_for_Consumer_Deletes_Account__c</fullName>
    <label>Days for Consumer Deletes Account</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_for_Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Days_for_Request_to_be_Forgotten__c</fullName>
    <label>Days for Request to be Forgotten</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CLNRULE_AccountWithCampaign.cls
global class CLNRULE_AccountWithCampaign implements Database.Batchable<SObject>{
    
    //constructor
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id, PersonContactId, Deletion_Flag__c, ContactID__pc FROM Account WHERE Deletion_Flag__c = FALSE');
    }
    
    //Method to execute to run batch job logic
    global void execute(Database.BatchableContext BC, List<Account> scope){
        Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
        List<Account> accountsToBeUpdated = new List<Account>();
        Set<String> accIdSet = new Set<String>();
        for(Account accRec : scope){
            accIdSet.add(accRec.Id);
        }
        List<Account> acctScope = new List<Account>([SELECT Id, Deletion_Flag__c, Account_Registration_Status__c, Double_Opt_in_Reminder_Email_Send_Date__c, Double_Opt_in_Reminder_Send_Date__c FROM Account WHERE Id IN: accIdSet]);
        List<CampaignMember> campMemList = [SELECT Id, Contact.AccountId, Campaign.EndDate, Campaign.CreatedDate, Campaign.Id FROM CampaignMember WHERE Contact.AccountId IN: accIdSet AND Campaign.EndDate != null ORDER BY Campaign.EndDate desc LIMIT 1];
        Map<Id, CampaignMember> campMemMap = new Map<Id, CampaignMember>();
        for(CampaignMember campRec : campMemList){
            campMemMap.put(campRec.Contact.AccountId, campRec);  
        }
        List<Account> accListInsert = new List<Account>();
        for(Account accRec : [SELECT Id, Account_Deletion_Date__c,Account_Registration_Status__c, Consent_Status__c, Consent_Withdrawn_Date__c, isHardBounced__pc,
                              Deletion_Flag__c, Deletion_Reason__c, To_be_Deleted_Date__c, Request_to_be_Forgotten__c, Double_Opt_in_Reminder_Email_Send_Date__c, Double_Opt_in_Reminder_Send_Date__c, Double_Opt_in_Email_Send_Date__c FROM Account WHERE Id IN: accIdSet]){   
                                  if(campMemMap.containsKey(accRec.Id) && !campMemMap.IsEmpty()){
                                      CampaignMember campMem = campMemMap.get(accRec.Id);
                                      if(accRec.Deletion_Flag__c == False && accRec.Account_Registration_Status__c != 'Active'  && accRec.Consent_Status__c == 'Withdrawn' && accRec.Consent_Withdrawn_Date__c != null && campMem.Campaign.EndDate < date.today().addMonths(-3)){
                                          accRec.Deletion_Flag__c = True;
                                          accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
                                          accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
                                          accListInsert.add(accRec);           
                                      }else if(accRec.Request_to_be_Forgotten__c == True && accRec.Deletion_Flag__c == False && accRec.Account_Registration_Status__c == 'Deactivated' && accRec.Consent_Status__c == 'Withdrawn' && campMem.Campaign.EndDate < date.today().addMonths(-1)){
                                          accRec.Deletion_Flag__c = True;
                                          accRec.Deletion_Reason__c = Label.DelReason_Request_to_be_Forgotten;
                                          accRec.To_be_Deleted_Date__c = date.Today().addDays(Integer.valueOf(settings.Days_for_Request_to_be_Forgotten__c));
                                          accListInsert.add(accRec);
                                      }else if(accRec.Deletion_Flag__c == false && accRec.Request_to_be_Forgotten__c == True && accRec.Account_Registration_Status__c != 'Active' && accRec.Consent_Status__c == Null && campMem.Campaign.EndDate < date.today().addMonths(-3)){
                                          accRec.Deletion_Flag__c = true;
                                          accRec.To_be_Deleted_Date__c = date.today().addDays(Integer.valueOf(settings.Days_for_Request_to_be_Forgotten__c));
                                          accRec.Deletion_Reason__c = Label.DelReason_No_Commercial_Consent;
                                          accListInsert.add(accRec);
                                      }else if(accRec.Request_to_be_Forgotten__c == True && accRec.Deletion_Flag__c == False && accRec.Account_Registration_Status__c == 'Deactivated' && accRec.Consent_Status__c == 'Withdrawn' && campMem.Campaign.EndDate < date.today().addMonths(-3)){
                                          accRec.Deletion_Flag__c = True;
                                          accRec.Deletion_Reason__c = Label.DelReason_Request_to_be_Forgotten;
                                          accRec.To_be_Deleted_Date__c = date.Today().addDays(Integer.valueOf(settings.Days_for_Request_to_be_Forgotten__c));
                                          accListInsert.add(accRec);
                                      }
                                  }
                              }
        
        //Update Account Records
        if(!accListInsert.isEmpty()){
            Database.update(accListInsert, false);
        }
    }
    
    //Method to execute after running batch job
    global void finish(Database.BatchableContext BC){
        
    }
}