force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Double_Opt_in_Reminder_Email_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_in_Reminder_Email_Send_Date__c</fullName>
    <label>Double Opt-in Reminder Email Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Request_to_be_Forgotten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request to be Forgotten</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/ProcessBuilderSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ProcessBuilderSettings</label>
</CustomObject>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/AccountProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>AccountProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AccountProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/IndividualEmailResultProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>IndividualEmailResultProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IndividualEmailResultProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/LoyaltyProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>LoyaltyProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/LoyaltyTransactionProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyTransactionProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>LoyaltyTransactionProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GDPRCleaningRulesTestError.cls
@isTest
public class GDPRCleaningRulesTestError {
    private static testMethod void manyAccountTest() {
        List<Account> lstAcc = new List<Account>();
        
        ProcessBuilderSettings__c cs = new ProcessBuilderSettings__c();
        cs.AccountProcessBuilder__c = true;
        cs.IndividualEmailResultProcessBuilder__c = true;
        cs.LoyaltyProcessBuilder__c = true;
        cs.LoyaltyTransactionProcessBuilder__c = true;
        //cs.Other field values
     	insert cs;

        String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
        for(integer x=0;x<200;x++){
            Account acct = TestDataBuilder.createAccount();
            acct.recordTypeId = recordTypeId;
            acct.Type__c = 'Loyalty';
            //acct.IsCustomerPortal = true;
            acct.Account_Registration_Status__c = 'Active';
            acct.Consent_Status__c = 'Active';
            lstAcc.add(acct);
        }
        
        insert lstAcc;
        
        system.debug('First');
        system.debug(lstAcc);
        
        for(Account accRec: lstAcc){ 
            accRec.Request_to_be_Forgotten__c = true;
        }
        update lstAcc;
        List<Account> updatedAcc = [SELECT Id, Request_to_be_Forgotten__c, Deletion_Flag__c, To_be_Deleted_Date__c From Account where Id IN :lstAcc];
        
        system.debug('Second');
        system.debug(updatedAcc);
        for(Account accRec: lstAcc){            
            accRec.Double_Opt_in_Reminder_Email_Send_Date__c = system.now();
        }
        update lstAcc;
        updatedAcc = [SELECT Id, Name, Request_to_be_Forgotten__c, Deletion_Flag__c, To_be_Deleted_Date__c From Account where Id IN :lstAcc];
        
        system.debug('last');
        system.debug(updatedAcc);
		
    }
}