force-app/main/default/objects/Account/fields/Account_Deletion_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Deletion_Date__c</fullName>
    <label>Account Deactivation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Withdrawn_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Withdrawn_Date__c</fullName>
    <label>Commercial Consent Withdrawn Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Reason__c</fullName>
    <label>Deletion Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Request_to_be_Forgotten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request to be Forgotten</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_for_Consumer_Deletes_Account__c.field-meta.xml
<CustomField>
    <fullName>Days_for_Consumer_Deletes_Account__c</fullName>
    <label>Days for Consumer Deletes Account</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_for_Consumer_Withdraws__c.field-meta.xml
<CustomField>
    <fullName>Days_for_Consumer_Withdraws__c</fullName>
    <label>Days for Consumer Withdraws</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_for_Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Days_for_Request_to_be_Forgotten__c</fullName>
    <label>Days for Request to be Forgotten</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/PersonAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>PersonAccountTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PersonAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLNRULE_AccountWithCampaignTest.cls
/*********************************************************************
Name    :               CLNRULE_AccountWithCampaignTest
Date    :               
Author  :               
Description :           Test Class of CLNRULE_AccountWithCampaign
Current Test Coverage : 
History :       
*********************************************************************/

@isTest
private class CLNRULE_AccountWithCampaignTest {
  public static testMethod void testScenario1() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Deactivated';
    accRec.Consent_Status__c = 'Withdrawn';
    accRec.Consent_Withdrawn_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-4)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(CampaignId = camp.Id, Status = 'Sent')
      );
    }
    Database.insert(camMemberList, false);
    Test.startTest();
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario2() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Deactivated';
    accRec.Consent_Status__c = 'Withdrawn';
    accRec.Account_Deletion_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-4)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    Test.startTest();
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    //accRec.Deletion_Flag__c = True;
    //accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
    //accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
    //Database.update(accRec, false);
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario3() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    settings.Days_for_Request_to_be_Forgotten__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Deactivated';
    accRec.Request_to_be_Forgotten__c = true;
    accRec.Consent_Status__c = 'Withdrawn';
    accRec.Consent_Withdrawn_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-2)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    Test.startTest();
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    //accRec.Deletion_Flag__c = True;
    //accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
    //accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
    //Database.update(accRec, false);
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario4() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    settings.Days_for_Request_to_be_Forgotten__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = null;
    accRec.Request_to_be_Forgotten__c = true;
    accRec.Consent_Status__c = 'Withdrawn';
    accRec.Consent_Withdrawn_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-2)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    Test.startTest();
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    //accRec.Deletion_Flag__c = True;
    //accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
    //accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
    //Database.update(accRec, false);
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario5() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    settings.Days_for_Request_to_be_Forgotten__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Deactivated';
    accRec.Request_to_be_Forgotten__c = true;
    accRec.Consent_Status__c = null;
    accRec.Consent_Withdrawn_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-4)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    Test.startTest();
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    //accRec.Deletion_Flag__c = True;
    //accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
    //accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
    //Database.update(accRec, false);
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario6() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    settings.Days_for_Request_to_be_Forgotten__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Active';
    accRec.Request_to_be_Forgotten__c = true;
    accRec.Consent_Status__c = 'Active';
    accRec.Consent_Withdrawn_Date__c = date.today();
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-4)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    Test.startTest();
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    //accRec.Deletion_Flag__c = True;
    //accRec.Deletion_Reason__c = Label.DelReason_Consent_Withdrawn;
    //accRec.To_be_Deleted_Date__c = Date.valueOf(accRec.Consent_Withdrawn_Date__c).addDays(Integer.valueOf(settings.Days_for_Consumer_Deletes_Account__c));
    //Database.update(accRec, false);
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }

  public static testMethod void testScenario7() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    insert ts1;
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    settings.Days_for_Consumer_Deletes_Account__c = 14;
    settings.Days_for_Consumer_Withdraws__c = 14;
    settings.Days_for_Request_to_be_Forgotten__c = 14;
    insert settings;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.LastName = 'Test Class';
    accRec.RecordTypeId = recordTypeId;
    accRec.Brand__c = 'Douwe Egberts';
    accRec.Type__c = 'Loyalty';
    accRec.Country__c = 'NL';
    accRec.PersonEmail = 'testclassNL@salesforce.com';
    accRec.External_Id__c = 'testclassNL@salesforce.comNLDouweEgberts';
    accRec.Deletion_Flag__c = false;
    accRec.Account_Registration_Status__c = 'Deactivated';
    accRec.Request_to_be_Forgotten__c = true;
    accRec.Consent_Status__c = null;
    accRec.To_be_Deleted_Date__c = date.today();
    insert accRec;
    Contact conRec = [
      SELECT Id, AccountId
      FROM Contact
      WHERE Account.Name = 'Test Class'
      LIMIT 1
    ];
    List<CampaignMember> camMemberList = new List<CampaignMember>();
    campaign camp = new Campaign(
      Name = 'TestCampaign',
      EndDate = date.today().addMonths(-4)
    );
    Database.insert(camp, false);
    for (integer i = 0; i < 10; i++) {
      camMemberList.add(
        new CampaignMember(
          ContactId = conRec.Id,
          CampaignId = camp.Id,
          Status = 'Sent'
        )
      );
    }
    Database.insert(camMemberList, false);
    Test.startTest();
    //(accRec.Deletion_Flag__c == false && accRec.Request_to_be_Forgotten__c == True && accRec.Account_Registration_Status__c != 'Active' && accRec.Consent_Status__c == Null && campMem.Campaign.EndDate < date.today().addMonths(-3)
    CLNRULE_AccountWithCampaign testBatch = new CLNRULE_AccountWithCampaign();
    DataBase.executeBatch(testBatch);
    System.debug('Deletion Flag: ' + accRec.Deletion_Flag__c);
    System.debug(
      'Registration Status: ' + accRec.Account_Registration_Status__c
    );
    System.debug('Consent Status: ' + accRec.Consent_Status__c);
    System.debug('Withdrawn Date: ' + accRec.Consent_Withdrawn_Date__c);
    System.debug('Campaign End Date: ' + camp.EndDate);
    System.assertEquals(
      accRec.Deletion_Flag__c = true,
      accRec.Deletion_Flag__c = true
    );
    Test.stopTest();
  }
}