force-app/main/default/objects/Account/fields/Account_Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Date__c</fullName>
    <label>Account Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Source_URL__c</fullName>
    <label>Account Consent Registration Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Email__c</fullName>
    <label>Account Registration Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Source__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Source__c</fullName>
    <label>Account Registration Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intershop</fullName>
            </value>
            <value>
                <fullName>Sampling Form</fullName>
            </value>
            <value>
                <fullName>External Database</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Local Database</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>DE.NL</fullName>
            </value>
            <value>
                <fullName>MDC.FR</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Source_URL__c</fullName>
    <label>Commercial Consent Reg. Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text__c</fullName>
    <label>Commercial Consent Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Commercial Consent Text Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Email_Sent_Date__c</fullName>
    <label>Loyalty Email Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Source__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Source__c</fullName>
    <label>Opt-in Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intershop</fullName>
            </value>
            <value>
                <fullName>Sampling Form</fullName>
            </value>
            <value>
                <fullName>External Database</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Local Database</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
            <value>
                <fullName>Pro-Campaign</fullName>
            </value>
            <value>
                <fullName>Zeta</fullName>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>DE.NL</fullName>
            </value>
            <value>
                <fullName>Zeta.Mein.Senseo</fullName>
            </value>
            <value>
                <fullName>serviceplan.mein.senseo</fullName>
            </value>
            <value>
                <fullName>MDC.FR</fullName>
            </value>
            <value>
                <fullName>BBDO</fullName>
                <isActive>false</isActive>
                <label>BBDO</label>
            </value>
            <value>
                <fullName>Blokker</fullName>
                <isActive>false</isActive>
                <label>Blokker</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Summary__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Summary__c</fullName>
    <label>Privacy Policy Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/EncryptionKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting value will be used in Encryption Key</description>
    <label>EncryptionKey</label>
</CustomObject>

force-app/main/default/objects/EncryptionKey__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/IV__c.field-meta.xml
<CustomField>
    <fullName>IV__c</fullName>
    <label>IV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/OptinURLPlaceholder__c.field-meta.xml
<CustomField>
    <fullName>OptinURLPlaceholder__c</fullName>
    <label>OptinURLPlaceholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/OptoutURLPlaceholder__c.field-meta.xml
<CustomField>
    <fullName>OptoutURLPlaceholder__c</fullName>
    <label>OptoutURLPlaceholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Account_Number__c</fullName>
    <label>Loyalty Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DELoyaltyCommunityHelperTest.cls
/* ----------------------------------------------------------------------------------------------
   Name: DELoyaltyCommunityHelperTest
   Description: 

   Date         Version     Author              Summary of Changes 
   -----------  -------     -----------------   -----------------------------------------
  012-March-2018   1.0       ralph.r.v.gozarin   Intial creation
*/

@IsTest(seeAllData = false)
public with sharing class DELoyaltyCommunityHelperTest {
    
    public static List<Id> lstAccIds = new List<Id>();
    
    private static List<Account> setupAccountData() {
        //TestDataFactory.setCustomSetting();
        
        
        List<Account> lstAcc = new List<Account>();
        
        Account acc = new Account(firstName = 'loyaltyTest', 
                                  lastName = 'UserTest',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Newsletter Subscriber',
                                  Consent_Status__c	 = 'Active',
                                  PersonEmail='jde5@douweegberts.com', 
                                  External_Id__c ='jde5@douweegberts.com'+Label.Country+Label.Brand,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID);
        lstAcc.add(acc);
         
        acc = new Account(firstName = 'loyaltyTest', 
                                  lastName = 'UserTest',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Newsletter Subscriber',
                                  Consent_Status__c	 = 'Pending Confirmation',
                                  PersonEmail='jde6@douweegberts.com', 
                                  External_Id__c ='jde6@douweegberts.com'+Label.Country+Label.Brand,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID);
        acc = new Account(firstName = 'loyaltyTest', 
                                  lastName = 'UserTest',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Loyalty',
                                  Consent_Status__c	 = 'Pending Confirmation',
                                  PersonEmail='jde7@douweegberts.com', 
                                  External_Id__c ='jde7@douweegberts.com'+Label.Country+Label.Brand,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID);
        
        
        lstAcc.add(acc);
        /*    
        Account acc3 = new Account(firstName = 'loyaltyTest7', lastName = 'UserTest7', Gender__pc = 'Male',
                                      PersonEmail='loyaltyTest.userTestx7@gmail.com', External_Id__c ='loyaltyTest.userTestx7@gmail.comNLDouwe Egberts',
                                      PersonBirthdate = Date.valueOf('1992-03-15'), Loyalty_Email_Sent_Date__c = system.now(),
                                     OwnerId='0054E000002dJtCQAU');
        lstAcc.add(acc2);
        lstAcc.add(acc3);
		*/  
        insert lstAcc;
        
        return lstAcc;
    }
    
    static testMethod void positivelightningSelfRegisterNewConsumer(){
        TestDataFactory.setCustomSetting();
        Test.startTest();
    	LightningSelfRegisterController.selfRegister('firstname1', 'lastname1', 'jde4@douweegberts.com', 
                                                     '', '','','regConfirmUrl', null, 'startUrl', false, 
                                                     String.valueOf(System.today().addYears(-20)),'1186 EC','26','Matterhorn','Amstelveen',
                                                     '', 'True');
        Test.stopTest();
        
    }
    static testMethod void positivelightningSelfRegisterCreateUser(){
        TestDataFactory.setCustomSetting();
        Test.startTest();
        LightningSelfRegisterController.selfRegister('firstname1', 'lastname1', 'jde8@douweegberts.com', 
                                                     '', '','','regConfirmUrl', null, 'startUrl', false, 
                                                     String.valueOf(System.today().addYears(-20)),'1186 EC','26','Matterhorn','Amstelveen',
                                                     '', 'True');
        
        List<Account> lstAcc  = new List<Account> ([SELECT ID FROM ACCOUNT WHERE personEmail = 'jde8@douweegberts.com']);
        system.debug('lstAcc '+lstAcc);
        
    	CommunityUsersFactory.Consumer_NewUser_EmailChange(lstAcc);
        Test.stopTest();
        
    }
    
    static testMethod void positivelightningSelfRegisterExistingConsumer(){
        
        setupAccountData();

        Test.startTest();
    	LightningSelfRegisterController.selfRegister('firstname1', 'lastname1', 'jde5@douweegberts.com', 
                                                     '', '','','regConfirmUrl', null, 'startUrl', false, 
                                                     String.valueOf(System.today().addYears(-20)),'1186 EC','26','Matterhorn','Amstelveen',
                                                     '', 'True');
        Test.stopTest();
    }
    
    static testMethod void positivelightningSelfRegisterExistingConsumerUpgrade(){
        setupAccountData();
        
        Test.startTest();
    	LightningSelfRegisterController.selfRegister('firstname1', 'lastname1', 'jde6@douweegberts.com', 
                                                     '', '','','regConfirmUrl', null, 'startUrl', false, 
                                                     String.valueOf(System.today().addYears(-20)),'1186 EC','26','Matterhorn','Amstelveen',
                                                     '', 'True');
        Test.stopTest();
    }
    static testMethod void positivelightningForgotPassword(){
 		LightningForgotPasswordController.forgotPassword('username', 'test');
    }
    
    @isTest
    static void createUser(){
        List<Account> lstAcc = setupAccountData();
        Test.startTest();
        lstAccIds = CommunityUsersFactory.createUser(lstAcc);
        Test.stopTest();
    }
    
    @isTest
    static void updateUserEmailAddress(){ 
        Set<ID> accIds = new Set<ID>();
        //User usr = TestDataFactory.TestCreateUser(3);
        
        for (Id AccId : lstAccIds)
        	accIds.add(AccId);
        
        Test.startTest();
        system.debug('!!! accids:: ' + accIds);
    	CommunityUsersFactory.updateUserEmailAddress(accIds);
        Test.stopTest();
    }
    @IsTest
    static void testUpgradeConsumerToLoyalty(){
        EncryptionKey__c encrypnKey = new EncryptionKey__c(SetupOwnerId=UserInfo.getOrganizationId());
        
        encrypnKey.Algorithm__c = 'AES256';
        encrypnKey.IV__c = '7402862816488480';
        encrypnKey.Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X';
        encrypnKey.OptinURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf';
        encrypnKey.OptoutURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf';
        insert encrypnKey;
        System.debug(encrypnKey);

        Account acc = new Account(firstName = 'loyaltyTestUpgrade', 
                                  lastName = 'UserTestUp',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Newsletter Subscriber',
                                  Consent_Status__c	 = '',
                                  PersonEmail='testUpgrade@douweegberts.com', 
                                  External_Id__c =null,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID,
                                  Privacy_Policy_Summary__c =null,
                                  Account_Consent_Registration_Source_URL__c = null,
                                  Account_Registration_Status__c = null ,
                                  Account_Consent_Registration_Date__c = null,
                                  Account_Registration_Email__c = null,
                                  Account_Registration_Source__c = null,
                                  Consent_Text__c = null,
                                  Consent_Text_Version__c = null,
                                  Privacy_Policy_Version__c = null,
                                  Consent_Registration_Source_URL__c = null,
                                  Opt_in_Source__c = null, BillingStreet = null, 
                                  BillingCity = null,BillingPostalCode = null,BillingCountry = null
                                  );
        insert acc;
        System.debug(acc);
        Id userId = UserInfo.getUserId();
        User u = [SELECT Name,Street, City, postalCode FROM User WHERE Id = :userId];

        Test.startTest();
            DELoyaltyCommunityHelper.upgradeConsumerToLoyalty(acc, true, 'DE.NL', u);
        Test.stopTest();
        
    }

    @IsTest
    static void testUpdateUser(){
        Id userId = UserInfo.getUserId();
        List<User> lstUser  = [SELECT Name,Street, City, postalCode FROM User WHERE Id = :userId];
        Test.startTest();
            List<User> rtListUser =  DELoyaltyCommunityHelper.updateUsers(lstUser);
            System.assert(rtListUser.size() > 0);
        Test.stopTest();
        
    }

    @IsTest
    static void testConsumerUserAccountExist(){
        
        Test.startTest();
          Boolean ret =   DELoyaltyCommunityHelper.consumerUserAccountExist('wrongId');
          System.assert(ret == false);
        Test.stopTest();
        
    }
    @IsTest
    static void testAccountPresentPositive(){
        Id userId = UserInfo.getUserId();
        User u = [SELECT Name,Email,Street, City, postalCode FROM User WHERE Id = :userId];

        Account acc = new Account(firstName = 'loyaltyTestUpgrade', 
                                  lastName = 'UserTestUp',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Loyalty',
                                  Consent_Status__c	 = '',
                                  PersonEmail= u.Email, 
                                  External_Id__c =u.Email+Label.Country+Label.Brand,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID,
                                  Privacy_Policy_Summary__c =null,
                                  Account_Consent_Registration_Source_URL__c = null,
                                  Account_Registration_Status__c = null ,
                                  Account_Consent_Registration_Date__c = null,
                                  Account_Registration_Email__c = null,
                                  Account_Registration_Source__c = null,
                                  Consent_Text__c = null,
                                  Consent_Text_Version__c = null,
                                  Privacy_Policy_Version__c = null,
                                  Consent_Registration_Source_URL__c = null,
                                  Opt_in_Source__c = null, BillingStreet = null, 
                                  BillingCity = null,BillingPostalCode = null,BillingCountry = null
                                  );
        insert acc;
        System.debug(acc);

        Loyalty__c l = new Loyalty__c(Loyalty_Account_Number__c ='1111111',Loyalty_Consumer__c = acc.Id,External_Id__c = acc.External_Id__c);
        insert l;

        String communityNetwId = [SELECT Id FROM NETWORK WHERE Name = :Label.CommunityName].Id;
        
        Test.startTest();
            DELoyaltyCommunityHelper.isCommunityAccountPresent(u, communityNetwId, '2000-10-01', 'true');
        Test.stopTest();

    }

    @IsTest
    static void testAccountPresentPositiveWithoutLoyalty(){
        EncryptionKey__c encrypnKey = new EncryptionKey__c(SetupOwnerId=UserInfo.getOrganizationId());

        encrypnKey.Algorithm__c = 'AES256';
        encrypnKey.IV__c = '7402862816488480';
        encrypnKey.Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X';
        encrypnKey.OptinURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf';
        encrypnKey.OptoutURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf';
        insert encrypnKey;
        System.debug(encrypnKey);
        Id userId = UserInfo.getUserId();
        User u = [SELECT Name,Email,Street, City, postalCode FROM User WHERE Id = :userId];

        Account acc = new Account(firstName = 'loyaltyTestUpgrade', 
                                  lastName = 'UserTestUp',
                                  Brand__c = 'Douwe Egberts',
                                  Type__c = 'Loyalty',
                                  Consent_Status__c	 = '',
                                  PersonEmail= u.Email, 
                                  External_Id__c =u.Email+Label.Country+Label.Brand,
                                  PersonBirthdate = System.today(),
                                  OwnerId=Label.CommunityOwnerID,
                                  Privacy_Policy_Summary__c =null,
                                  Account_Consent_Registration_Source_URL__c = null,
                                  Account_Registration_Status__c = null ,
                                  Account_Consent_Registration_Date__c = null,
                                  Account_Registration_Email__c = null,
                                  Account_Registration_Source__c = null,
                                  Consent_Text__c = null,
                                  Consent_Text_Version__c = null,
                                  Privacy_Policy_Version__c = null,
                                  Consent_Registration_Source_URL__c = null,
                                  Opt_in_Source__c = null, BillingStreet = null, 
                                  BillingCity = null,BillingPostalCode = null,BillingCountry = null
                                  );
        insert acc;
        System.debug(acc);

        String communityNetwId = [SELECT Id FROM NETWORK WHERE Name = :Label.CommunityName].Id;
        
        Test.startTest();
            DELoyaltyCommunityHelper.isCommunityAccountPresent(u, communityNetwId, '2000-10-01', 'true');
        Test.stopTest();

    }
    
    @IsTest
    static void testAccountCreation(){
       /*  User u = new User();
        u.FirstName ='testF';
        u.LastName = 'testL';
        u.Email= 'test@test.com';
        u.PostalCode = '75008';
        u.Street = 'street';
        u.City  = 'cityName';
        u.MobilePhone  = 0000000; */
        EncryptionKey__c encrypnKey = new EncryptionKey__c(SetupOwnerId=UserInfo.getOrganizationId());
        encrypnKey.Algorithm__c = 'AES256';
        encrypnKey.IV__c = '7402862816488480';
        encrypnKey.Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X';
        encrypnKey.OptinURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf';
        encrypnKey.OptoutURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf';
        insert encrypnKey;

        Account a = new Account (Name = 'TestNNN',Customer_ID__c = 1);
        insert a;

        User u = TestDataFactory.TestCreateUser(1, true)[0];
        String communityNetwId = [SELECT Id FROM NETWORK WHERE Name = :Label.CommunityName].Id;

        Test.startTest();
            DELoyaltyCommunityHelper.isCommunityAccountPresent(u, communityNetwId, '2000-10-01', 'true');
        Test.stopTest();
        
    }

     @IsTest
    static void testGetInactiveUsers(){
       List<User> userList = TestDataFactory.TestCreateUser(2, true);
       Set<String> userSet = new Set<String>();

       for(User u : userList){
        userSet.add(u.Username);
       }

       Test.startTest();
           List<User> inactiveUsers= DELoyaltyCommunityHelper.getInactiveUsers(userSet);
       Test.stopTest();
       System.assert(inactiveUsers.size() == 0);
        
    }
}