force-app/main/default/objects/Account/fields/Account_Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Date__c</fullName>
    <label>Account Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>This field is used for Loyalty Program</description>
    <externalId>true</externalId>
    <label>Loyalty_Customer ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_Migration_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Migration_Id__c</fullName>
    <externalId>true</externalId>
    <label>Data Migration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Email_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LightningConfirmEmailControllerTest.cls
@IsTest
public class LightningConfirmEmailControllerTest {
  @IsTest
  static void testConfirmEmail() {
    Account acc = new Account(
      FirstName = 'TESTforTEST',
      LastName = 'UserTestTEST',
      PersonEmail = 'testForTest1995@gmail.com',
      Gender__pc = 'Male',
      PersonBirthdate = System.today().addYears(-18),
      BillingPostalCode = '12365',
      BillingStreet = 'Mckinley hill:22:A',
      BillingCity = 'Taguig',
      Phone = '12345567465',
      Sixteen_Years_or_Older__c = true,
      Data_Migration_Id__c = '123456',
      Customer_ID__c = 123456,
      External_Id__c = 'testForTest1995@gmail.comNLDouwe Egberts',
      Account_Consent_Registration_Date__c = system.today(),
      Type__c = 'Loyalty',
      Consent_Status__c = 'Active',
      Brand__c = Label.Brand, //Douwe Egberts
      OwnerId = Label.CommunityOwnerID
      //RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account' LIMIT 1].Id
    );
    insert acc;

    Blob targetBlob = Blob.valueOf(String.valueOfGmt(acc.PersonBirthdate));
    Blob hash = Crypto.generateDigest('SHA-256', targetBlob);
    String hashBase64SHA1 = EncodingUtil.base64encode(hash);

    System.debug('account ' + acc.RecordTypeId);
    Account acct = [
      SELECT Id, Name, PersonEmail
      FROM Account
      WHERE PersonEmail = 'testForTest1995@gmail.com'
      LIMIT 1
    ];
    System.debug('account ' + acc);

    Test.startTest();
    // test confirmed
    String confirmEmailResponse = LightningConfirmEmailController.confirmEmail(
      hashBase64SHA1,
      'testForTest1995@gmail.com',
      './login'
    );
    System.assert(confirmEmailResponse == 'Confirmed');
    System.debug(confirmEmailResponse);

    Test.stopTest();
  }

  @IsTest
  static void testAlreadyConfirmed() {
    Account acc = new Account(
      FirstName = 'TESTforTEST',
      LastName = 'UserTestTEST',
      PersonEmail = 'testForTest1995@gmail.com',
      Gender__pc = 'Male',
      PersonBirthdate = System.today().addYears(-18),
      BillingPostalCode = '12365',
      BillingStreet = 'Mckinley hill:22:A',
      BillingCity = 'Taguig',
      Phone = '12345567465',
      Sixteen_Years_or_Older__c = true,
      Data_Migration_Id__c = '123456',
      Customer_ID__c = 123456,
      External_Id__c = 'testForTest1995@gmail.comNLDouwe Egberts',
      Account_Consent_Registration_Date__c = system.today(),
      Type__c = 'Loyalty',
      Consent_Status__c = 'Active',
      Brand__c = Label.Brand, //Douwe Egberts
      OwnerId = Label.CommunityOwnerID,
      Email_Confirmed__c = true
      //RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account' LIMIT 1].Id
    );
    insert acc;

    Blob targetBlob = Blob.valueOf(String.valueOfGmt(acc.PersonBirthdate));
    Blob hash = Crypto.generateDigest('SHA-256', targetBlob);
    String hashBase64SHA1 = EncodingUtil.base64encode(hash);

    System.debug('account ' + acc.RecordTypeId);
    Account acct = [
      SELECT Id, Name, PersonEmail
      FROM Account
      WHERE PersonEmail = 'testForTest1995@gmail.com'
      LIMIT 1
    ];
    System.debug('account ' + acc);

    Test.startTest();
    // test already confirmed
    String alreadyConfirmedResponse = LightningConfirmEmailController.confirmEmail(
      hashBase64SHA1,
      'testForTest1995@gmail.com',
      './login'
    );
    System.assert(alreadyConfirmedResponse == 'Already confirmed');
    System.debug(alreadyConfirmedResponse);

    Test.stopTest();
  }
  @IsTest
  static void testNotFound() {
    Account acc = new Account(
      FirstName = 'TESTforTEST',
      LastName = 'UserTestTEST',
      PersonEmail = 'testForTest1995@gmail.com',
      Gender__pc = 'Male',
      PersonBirthdate = System.today().addYears(-18),
      BillingPostalCode = '12365',
      BillingStreet = 'Mckinley hill:22:A',
      BillingCity = 'Taguig',
      Phone = '12345567465',
      Sixteen_Years_or_Older__c = true,
      Data_Migration_Id__c = '123456',
      Customer_ID__c = 123456,
      External_Id__c = 'testForTest1995@gmail.comNLDouwe Egberts',
      Account_Consent_Registration_Date__c = system.today(),
      Type__c = 'Loyalty',
      Consent_Status__c = 'Active',
      Brand__c = Label.Brand, //Douwe Egberts
      OwnerId = Label.CommunityOwnerID,
      Email_Confirmed__c = true
      //RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account' LIMIT 1].Id
    );
    insert acc;

    Blob targetBlob = Blob.valueOf(String.valueOfGmt(acc.PersonBirthdate));
    Blob hash = Crypto.generateDigest('SHA-256', targetBlob);
    String hashBase64SHA1 = EncodingUtil.base64encode(hash);

    System.debug('account ' + acc.RecordTypeId);
    Account acct = [
      SELECT Id, Name, PersonEmail
      FROM Account
      WHERE PersonEmail = 'testForTest1995@gmail.com'
      LIMIT 1
    ];
    System.debug('account ' + acc);

    Test.startTest();
    // test already confirmed
    String notFOund = LightningConfirmEmailController.confirmEmail(
      hashBase64SHA1,
      'testForTl.com',
      './login'
    );
    System.assert(notFOund == 'Customer  not found');
    System.debug(notFOund);

    Test.stopTest();
  }
}