force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Reason__c</fullName>
    <label>Deletion Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_clicked__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_clicked__c</fullName>
    <label>Last E-mail clicked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_opened__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_opened__c</fullName>
    <label>Last E-mail opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Order_Date__c</fullName>
    <label>Last Order Date</label>
    <summarizedField>Order__c.Start_Date__c</summarizedField>
    <summaryForeignKey>Order__c.Customer__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_For_NoEmailSentToCustomer__c.field-meta.xml
<CustomField>
    <fullName>Days_For_NoEmailSentToCustomer__c</fullName>
    <label>Days For NoEmailSentToCustomer</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CLNRules_NoEmailSentToCustomer.cls
/*****************************************************************************
Name    :       CLNRules_NoEmailSentToCustomer Batchable Class
Date    :       21 November 2017
Author  :       Anjerico Caburnay
Description:    Batchable class that will get all accounts with Deletion_Flag__c = false AND Account_Registration_Status__c !=: accStatus
                AND Last_Email_Send_Date__pc < LAST_N_DAYS:365
History
    fixed by Wunderman Thompson  09/2022   
*****************************************************************************/

global class CLNRules_NoEmailSentToCustomer implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    String Query =
      'SELECT Id, Type__c, IsCustomerPortal, Deletion_Flag__c, To_be_Deleted_Date__c, Deletion_Reason__c, Last_Email_clicked__c, Last_Email_opened__c, ' +
      'Brand__c, Last_Order_Date__c,Consent_Status__c,CreatedDate ' +
      'FROM Account ' +
      'WHERE Deletion_Flag__c = false ' +
      'AND (Last_Email_clicked__c <  LAST_N_MONTHS:24 OR Last_Email_clicked__c = Null) ' +
      'AND (Last_Email_opened__c < LAST_N_MONTHS:24 OR Last_Email_opened__c  = NULL) ' +
      'AND CreatedDate < LAST_N_MONTHS:24 ' +
      'AND Type__c != \'Loyalty\' AND Type__c != \'Registered\' AND IsCustomerPortal = false';
    /*
     'AND (Last_Email_Send_Date__pc < LAST_N_MONTHS:24 OR (Last_Email_Send_Date__pc = Null AND CreatedDate < LAST_N_MONTHS:24)) '+ */
    return Database.getQueryLocator(Query);
  }

  global void execute(Database.BatchableContext BC, List<Account> scope) {
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    List<Account> accountsToUpdate = new List<Account>();
    System.debug(scope.size());
    try {
      for (Account acc : scope) {
        // NON-DTC, non portal user
        acc.Deletion_Flag__c = true;
        acc.To_be_Deleted_Date__c = date.today()
          .addDays(Integer.valueOf(settings.Days_For_NoEmailSentToCustomer__c));
        acc.Deletion_Reason__c = 'No email sent over 24 months';
        acc.Consent_Status__c = 'Expired';
        accountsToUpdate.add(acc);
      }

      System.Debug(
        'Scope of the  Batch NoEMailSent24Months : \n' + scope.size()
      );
      System.Debug(
        'List of Account from Batch NoEMailSent24Months to be deleted : \n' +
        accountsToUpdate.size()
      );
      if (!accountsToUpdate.isEmpty()) {
        update accountsToUpdate;
      }
    } catch (exception e) {
      system.debug('Error: ' + e);
    }
  }

  global void finish(Database.BatchableContext BC) {
  }
}