force-app/main/default/objects/Account/fields/Account_Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Date__c</fullName>
    <label>Account Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>This field is used for Loyalty Program</description>
    <externalId>true</externalId>
    <label>Loyalty_Customer ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_Migration_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Migration_Id__c</fullName>
    <externalId>true</externalId>
    <label>Data Migration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Email_Sent_Date__c</fullName>
    <label>Loyalty Email Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DEPortalUsersConfirmEmailReminderTest.cls
@IsTest
public class DEPortalUsersConfirmEmailReminderTest {
  @IsTest
  static void testReminder() {
    String RecType = [
      SELECT ID
      FROM RECORDTYPE
      WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account'
    ]
    .Id;
    List<Account> lstAccount = new List<Account>();
    for (Integer i = 0; i <= 120; i++) {
      lstAccount.add(
        new Account(
          FirstName = 'T' + i + 'e' + i + 'st' + i + 't',
          LastName = 'U' + i + 's' + i + 'er' + i + 'r',
          PersonEmail = 'jde1' + i + '@douweEgberts.com',
          Gender__pc = 'Male',
          PersonBirthdate = System.today().addYears(-18),
          BillingPostalCode = '12365',
          BillingStreet = 'Mckinley hill:22:A',
          BillingCity = 'Taguig',
          Phone = '12345567465',
          Sixteen_Years_or_Older__c = true,
          Data_Migration_Id__c = '123456' + i,
          Customer_ID__c = 123456 + i,
          External_Id__c = 'jde1' + i + '@douweEgberts.comNLDouwe Egberts',
          Account_Consent_Registration_Date__c = system.today(),
          Type__c = 'Loyalty',
          Consent_Status__c = 'Active',
          Brand__c = Label.Brand, //Douwe Egberts
          OwnerId = Label.CommunityOwnerID,
          Loyalty_Email_Sent_Date__c = System.today(),
          RecordTypeId = RecType
        )
      );
    }

    insert lstAccount;
    for (Account a : lstAccount) {
      Test.setCreatedDate(a.Id, Datetime.now().addDays(-1));
    }

    List<Contact> contactList = [SELECT ID FROM CONTACT];
    System.debug(contactList.size());

    List<User> userList = TestDataFactory.TestCreateUser(120, true);
    for (Integer i = 0; i <= 120; i++) {
      userList[i].ContactId = contactList[i].ID;
      userList[i].Alias = 'DE' + i;
      userList[i].CommunityNickname = userList[i].Alias;
      userList[i].Username =
        'U' +
        i +
        's' +
        i +
        'er' +
        i +
        'r' +
        '@douweEgberts.com';
    }
    insert userList;

    Test.startTest();
    DEPortalUsersConfirmEmailReminderBatch b = new DEPortalUsersConfirmEmailReminderBatch();
    database.executebatch(b);
    Test.stopTest();
  }
}