force-app/main/default/objects/Account/fields/Account_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Registration_Status__c</fullName>
    <label>Account Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Double_Opt_in_Reminder_Email_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_in_Reminder_Email_Send_Date__c</fullName>
    <label>Double Opt-in Reminder Email Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_After_DOI_Reminder_Sent_Date_del__c.field-meta.xml
<CustomField>
    <fullName>Days_After_DOI_Reminder_Sent_Date_del__c</fullName>
    <label>Days After DOI Reminder Sent Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_to_be_Added_after_DOI_Reminder_Send__c.field-meta.xml
<CustomField>
    <fullName>Days_to_be_Added_after_DOI_Reminder_Send__c</fullName>
    <label>Days to be Added after DOI Reminder Send</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/CampaignMemberTrigger__c.field-meta.xml
<CustomField>
    <fullName>CampaignMemberTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CampaignMemberTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/PersonAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>PersonAccountTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PersonAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLNRULE_BatchDOIReminderMarkDelTest.cls
/*********************************************************************
Name    :               CLNRULE_BatchDOIReminderMarkDelTest
Date    :               29 November 2017
Author  :               William Paredes
Description :           Test Class of CLNRULE_BatchDOIReminderMarkDel
Current Test Coverage : 95%
History :      
    Fixed by Wunderman Thompson 09/2022
*********************************************************************/

@isTest
private class CLNRULE_BatchDOIReminderMarkDelTest {
    @TestSetup
    static void makeData(){
        TriggerSettings__c ts1 = new TriggerSettings__c();
        ts1.PersonAccountTrigger__c = True;
        ts1.CampaignMemberTrigger__c = True;
        insert ts1;
        Cleanup_Rules_Settings__c CRSetting = new Cleanup_Rules_Settings__c();
        CRSetting.Days_After_DOI_Reminder_Sent_Date_del__c = 7;
        CRSetting.Days_to_be_Added_after_DOI_Reminder_Send__c = 7;
        //Deleted CRSetting.Days_to_be_Added_after_DOI_Reminder_Send__c to produce system.exception
        insert CRSetting;
    }
    
    private static testMethod void testAccountsWithOrWithoutCampaign() {
        
        String profileID = TestDataBuilder.getUserProfileId('System Administrator');
        
        User testUser = TestDataBuilder.createUser(1, profileID);
        insert testUser;
        
        datetime testDate = Date.TODAY() - Integer.valueOf(Cleanup_Rules_Settings__c.getInstance().Days_After_DOI_Reminder_Sent_Date_del__c);
        System.runAs(testUser)
        {
            
            String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
            List<Account> accList = new List<Account>();
            for(integer x=0;x<90;x++){
                Account acct = TestDataBuilder.createAccount();
                acct.recordTypeId = recordTypeId;
                acct.CurrencyISOCode = 'EUR';
                acct.Country__c = 'NL';
                acct.Deletion_Flag__c = false;
                acct.Consent_Status__c = 'Pending Confirmation';
                acct.Account_Registration_Status__c = 'Deactivated';
                accList.add(acct);
            }
            insert accList;

            Contact conRec = [Select Id, AccountId from Contact WHERE Account.Name = 'Test Account' LIMIT 1];
            List<CampaignMember> camMemberList = new List<CampaignMember>();
            Campaign camp = new Campaign(Name = 'TestCampaign', EndDate = date.today().addMonths(-4));
            Database.insert(camp, false);
            for (integer i = 0; i< 10; i++) {
                camMemberList.add(new CampaignMember(ContactId = conRec.Id , CampaignId = camp.Id, Status = 'Sent'));
            }
            Database.insert(camMemberList, false);

            for(Account acc: accList){
                acc.Double_Opt_in_Reminder_Email_Send_Date__c = testDate;
            }
            update accList;

            Test.startTest();
                CLNRULE_BatchDOIReminderMarkDel testBatch = new CLNRULE_BatchDOIReminderMarkDel();
                DataBase.executeBatch(testBatch);
            Test.stopTest();
            
            List<Account> checkAccounts = [SELECT Id, Deletion_Flag__c FROM Account];
            for(Account acc : checkAccounts){
                //System.assert(acc.Deletion_Flag__c == true);
            }
            
        } 
    }
    
    
}