force-app/main/default/objects/Account/fields/Account_Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Consent_Registration_Date__c</fullName>
    <label>Account Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Date__c</fullName>
    <label>Commercial Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>This field is used for Loyalty Program</description>
    <externalId>true</externalId>
    <label>Loyalty_Customer ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_Migration_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Migration_Id__c</fullName>
    <externalId>true</externalId>
    <label>Data Migration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/EncryptionKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting value will be used in Encryption Key</description>
    <label>EncryptionKey</label>
</CustomObject>

force-app/main/default/objects/EncryptionKey__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/IV__c.field-meta.xml
<CustomField>
    <fullName>IV__c</fullName>
    <label>IV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/OptinURLPlaceholder__c.field-meta.xml
<CustomField>
    <fullName>OptinURLPlaceholder__c</fullName>
    <label>OptinURLPlaceholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/fields/OptoutURLPlaceholder__c.field-meta.xml
<CustomField>
    <fullName>OptoutURLPlaceholder__c</fullName>
    <label>OptoutURLPlaceholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Account_Number__c</fullName>
    <label>Loyalty Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Blocked_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Blocked_Date__c</fullName>
    <label>Loyalty Card Blocked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Created_Date__c</fullName>
    <label>Loyalty Card Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Number__c</fullName>
    <label>Loyalty Card Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Status__c</fullName>
    <label>Loyalty Card Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/ProcessBuilderSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ProcessBuilderSettings</label>
</CustomObject>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/AccountProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>AccountProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AccountProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/IndividualEmailResultProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>IndividualEmailResultProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IndividualEmailResultProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/LoyaltyProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>LoyaltyProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/LoyaltyTransactionProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyTransactionProcessBuilder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>LoyaltyTransactionProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/* ----------------------------------------------------------------------------------------------
   Name: TestDataFactory
   Description: All Test Data records
   Date         Version     Author              Summary of Changes 
   -----------  -------     -----------------   -----------------------------------------
   15-March-2018   1.0       ralph.r.v.gozarin   Intial creation
*/
@isTest(seeAllData = false)
public with sharing class TestDataFactory {

    public static EncryptionKey__c setCustomSetting(){
        //EncryptionKey__c encrypnKey;     
        EncryptionKey__c encrypnKey = EncryptionKey__c.getOrgDefaults();

        encrypnKey.Algorithm__c = 'AES256';
        encrypnKey.IV__c = '7402862816488480';
        encrypnKey.Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X';
        encrypnKey.OptinURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf';
        encrypnKey.OptoutURLPlaceholder__c = 'https://denl-test.jdecoffee.net/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf';
        upsert encrypnKey EncryptionKey__c.Id;


        return encrypnKey;
    }

    public static ProcessBuilderSettings__c setProcessBuilderSettings(){
        ProcessBuilderSettings__c prcSettings = ProcessBuilderSettings__c.getOrgDefaults();

        prcSettings.AccountProcessBuilder__c = false;
        prcSettings.LoyaltyProcessBuilder__c = false;
        prcSettings.IndividualEmailResultProcessBuilder__c = false;
        prcSettings.LoyaltyTransactionProcessBuilder__c = true;
        upsert prcSettings ProcessBuilderSettings__c.Id;
        system.debug('prc settings '+prcSettings);
        return prcSettings;
    }

    public static List<User> TestCreateUser(Integer i, Boolean isEmailPostFix){
        Map<String,Profile> mapProfile  = new Map<String,Profile>();
        mapProfile =  DELoyaltyCommunityHelper.mapProfileDetail(new Set<String> {Label.DECommunityProfile});
        List<User> lstUser = new List<User>();
        String email = '';

        for (Integer x=i; x>=0; x--) {
            if (isEmailPostFix){
                email = '_jde' + i + '@douweegberts.com.de.nl';
            } else {
                email = 'jde' + i + '@douweegberts.com.de.nl';
            }

            User user = new User(
                Alias = 'JDEUser' + i,
                Email = email,            
                EmailEncodingKey = 'UTF-8',
                LastName = 'User' + i,
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = mapProfile.get(Label.DECommunityProfile).Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = email,
                isActive = true
            );
            lstUser.add(user);
        }

        return lstUser;
    }

    public static List<Account> testAccountData(){ 
        List<Account> lstAccount = new List<Account>();
        lstAccount.add(
            new Account(
                FirstName = 'Test',
                LastName = 'User',
                PersonEmail = 'jde1@douweEgberts.com',
                Gender__pc = 'Male',
                PersonBirthdate = System.today().addYears(-18),
                BillingPostalCode = '12365',
                BillingStreet = 'Mckinley hill:22:A',
                BillingCity = 'Taguig',
                Phone = '12345567465',
                Sixteen_Years_or_Older__c = True,
                Data_Migration_Id__c = '123456',
                Customer_ID__c = 123456,
                External_Id__c = 'jde1@douweEgberts.comNLDouwe Egberts',
                Account_Consent_Registration_Date__c =  system.today(),
                Type__c = 'Loyalty',
                Consent_Status__c = 'Active',
                Brand__c = Label.Brand, //Douwe Egberts
                OwnerId = Label.CommunityOwnerID,
                RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account'].Id
            )
		);

        lstAccount.add(
            new Account(
                FirstName = 'test',
                LastName = 'User 2',
                PersonEmail = 'jde2@douweEgberts.com',
                Gender__pc = 'Male',
                PersonBirthdate = System.today().addYears(-18),
                BillingPostalCode = '12365',
                BillingStreet = 'Mckinley hill:100:E',
                BillingCity = 'Taguig',
                Phone = '12345567465',
                Sixteen_Years_or_Older__c = True,
                Data_Migration_Id__c = '1234567',
                Customer_ID__c = 1234567,
                External_Id__c = 'jde2@douweEgberts.comNLDouwe Egberts' ,
                Type__c = 'Loyalty',
                Consent_Status__c = 'Withdrawn',
                Consent_Registration_Date__c = system.today(),
                Brand__c = Label.Brand, //Douwe Egberts
                OwnerId = Label.CommunityOwnerID,
                RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account'].Id
            )
        );

        lstAccount.add(
            new Account(
                FirstName = 'test',
                LastName = 'User 3',
                PersonEmail = 'jde3@douweEgberts.com',
                Gender__pc = 'Male',
                PersonBirthdate = system.today().addDays(-20),
                BillingPostalCode = '12365',
                BillingStreet = 'Mckinley hill',
                BillingCity = 'Taguig',
                Phone = '12345567465',
                Sixteen_Years_or_Older__c = True,
                Data_Migration_Id__c = '12345678',
                Customer_ID__c = 12345678,
                External_Id__c = 'jde3@douweEgberts.comNLDouwe Egberts' ,
                Type__c = 'Loyalty',
                Consent_Status__c = 'Active',
                Consent_Registration_Date__c = system.today(),
                Brand__c = Label.Brand, //Douwe Egberts
                OwnerId = Label.CommunityOwnerID,
                RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account'].Id
            )
          );

            lstAccount.add(
            new Account(
                FirstName = 'test',
                LastName = 'User 4',
                PersonEmail = 'jde4@douweEgberts.com',
                Gender__pc = 'Male',
                PersonBirthdate = system.today().addDays(-20),
                BillingPostalCode = '12365',
                BillingStreet = 'Mckinley hill',
                BillingCity = 'Taguig',
                Phone = '12345567465',
                Sixteen_Years_or_Older__c = True,
                Data_Migration_Id__c = '123456789',
                Customer_ID__c = 123456789,
                External_Id__c = 'jde4@douweEgberts.comNLDouwe Egberts' ,
                Type__c = 'Loyalty',
                Consent_Status__c = 'Active',
                Consent_Registration_Date__c = system.today(),
                Brand__c = Label.Brand, //Douwe Egberts
                OwnerId = Label.CommunityOwnerID,
                RecordTypeId  = [SELECT ID FROM RECORDTYPE WHERE SOBJECTTYPE = 'ACCOUNT' AND NAME = 'Person Account'].Id
            )
        );

        insert lstAccount;
        return lstAccount;
	}


    public static List<Loyalty__c> testLoyaltyData(List<Account> lstacc) {
        List<Loyalty__c> lstLoyal = new List<Loyalty__c>();
        Integer cnt = 1;

        for(Account acc: lstacc) {
            Loyalty__c loyal = new Loyalty__c(
                External_Id__c = '12' + crypto.getRandomInteger(),
                //Loyalty_Account_Number__c = '12345' + cnt,
                Loyalty_Card_Number__c = '12' + crypto.getRandomInteger(),
                Loyalty_Card_Created_Date__c = Date.today(),
                Loyalty_Card_Status__c = 'Active',
                Loyalty_Card_Blocked_Date__c = Date.today().addYears(1),
                Loyalty_Consumer__c = acc.Id
            );
            cnt++;
            lstLoyal.add(loyal);
        }


        insert lstLoyal;
        lstLoyal = [SELECT ID,NAME,External_Id__c,Loyalty_Card_Number__c,
                    		Loyalty_Card_Created_Date__c,Loyalty_Card_Status__c,Loyalty_Card_Blocked_Date__c,
                   			Loyalty_Consumer__c 
                    FROM Loyalty__c
                    WHERE ID IN :lstLoyal];
        system.debug('lstLoyal '+lstLoyal);
        return lstLoyal;
    }
}