force-app/main/default/objects/Account/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If there is an active subscription this flag will be set to true, if there is no Active subscription, this flag will be set to False.</description>
    <label>Active Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Confirmation_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Confirmation_URL__c</fullName>
    <label>Commercial Consent Confirmation URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Date__c</fullName>
    <label>Commercial Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_IP_Address__c</fullName>
    <label>Commercial Consent Reg. IP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Source_URL__c</fullName>
    <label>Commercial Consent Reg. Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text__c</fullName>
    <label>Commercial Consent Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Commercial Consent Text Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_URL__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_URL__c</fullName>
    <label>Opt-in URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_out_URL__c.field-meta.xml
<CustomField>
    <fullName>Opt_out_URL__c</fullName>
    <label>Opt-out URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountSelector_Test.cls
/**
 * @author piotr.tugeman@emark.com
 */
@isTest
private class AccountSelector_Test {
  @testSetup
  static void beforeEachTest() {
    List<Account> testAccounts = new List<Account>();

    Account account1 = new AccountBuilder()
      .setLastName('TestName_1')
      .setEmail('test_1@a.a')
      .setCountry('NL')
      .setBrand('Jacobs')
      .build();

    Account account2 = new AccountBuilder()
      .setLastName('TestName_2')
      .setEmail('test_2@a.a')
      .setCountry('NL')
      .setBrand('Tassimo')
      .setConsentRegistrationSourceUrl('https://reg.com')
      .setConsentRegistrationDate('2018-09-10T10:32:56Z')
      .setConsentText('My consent text...')
      .setConsentStatus(AccountBuilder.CONSENT_STATUS_REGISTERED)
      .setConsentTextVersion('v1.0')
      .setPrivacyPolicyVersion('p1.0')
      .setConsentRegistrationIPAddress('192.168.0.0')
      .setOptInUrl('https://opt.in.pl')
      .setOptOutUrl('https://opt.out.pl')
      .setConsentConfirmationUrl('https://conf.in.pl')
      .build();

    Account account3 = new AccountBuilder()
      .setLastName('TestName_3')
      .setEmail('test_3@a.a')
      .setCountry('NL')
      .setBrand('Tassimo')
      .build();

    testAccounts.add(account1);
    testAccounts.add(account2);
    testAccounts.add(account3);

    Test.startTest();
    insert testAccounts;
    Test.stopTest();
  }

  @isTest
  static void test_getAllAccountsBusinessRelevantFields_return_everything_needed() {
    // under test:
    List<Account> allAccounts = AccountSelector.getAllAccountsBusinessRelevantFields();

    // assertions:
    System.assert(allAccounts.size() == 3, 'There should be 3 accounts');
    for (Account account : allAccounts) {
      System.assert(
        !String.isEmpty(account.External_ID__c),
        'Account External_Id should exist'
      );
    }
    System.assertNotEquals(
      allAccounts[0].External_Id__c,
      allAccounts[1].External_Id__c,
      'Accounts External_IDs should be different'
    );
    System.assertNotEquals(
      allAccounts[0].External_Id__c,
      allAccounts[2].External_Id__c,
      'Accounts External_IDs should be different'
    );
    System.assertNotEquals(
      allAccounts[1].External_Id__c,
      allAccounts[2].External_Id__c,
      'Accounts External_IDs should be different'
    );
  }

  @isTest
  static void test_getAccountByExternalId_return_updateable_fields() {
    // under test:
    Account account = AccountSelector.getAccountByExternalId(
      'test_2@a.aNLTassimo'
    );

    // assertions:
    System.assert(
      null != account,
      'There should be account with this externalID. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.External_Id__c),
      'Returned account should have non empty externalID. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Status__c),
      'Returned account should have non empty Consent_Status__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_Source_URL__c),
      'Returned account should have non empty Consent_Registration_Source_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Consent_Registration_Date__c,
      'Returned account should have non empty Consent_Registration_Date__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text__c),
      'Returned account should have non empty Consent_Text__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text_Version__c),
      'Returned account should have non empty Consent_Text_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Privacy_Policy_Version__c),
      'Returned account should have non empty Privacy_Policy_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_IP_Address__c),
      'Returned account should have non empty Consent_Registration_IP_Address__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Opt_in_URL__c),
      'Returned account should have non empty Opt_in_URL__c. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Opt_out_URL__c),
      'Returned account should have non empty Opt_out_URL__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Confirmation_URL__c),
      'Returned account should have non empty Consent_Confirmation_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Sixteen_Years_or_Older__c,
      'Returned account should have non empty Sixteen_Years_or_Older__c. Account=' +
      account
    );

    System.assert(
      String.isNotEmpty(account.PersonContactId),
      'Returned account should have non empty PersonContactId. Account=' +
      account
    );
    System.assert(
      null != account.Active_Subscription__c,
      'Returned account should have non empty Active_Subscription__c. Account=' +
      account
    );
  }

  @isTest
  static void test_getAccountByExternalId_return_null() {
    // under test:
    Account account = AccountSelector.getAccountByExternalId('Nonexisting Id');

    // assertions:
    System.assert(
      null == account,
      'There should be no account with this externalID. Account=' + account
    );
  }

  @isTest
  static void test_getAccountByContactId_return_updateable_fields() {
    // setup:
    Account accountWithContactId = [
      SELECT PersonContactId
      FROM Account
      WHERE External_Id__c = 'test_2@a.aNLTassimo'
    ];

    // under test:
    Account account = AccountSelector.getAccountByContactId(
      accountWithContactId.PersonContactID
    );

    // assertions:
    System.assert(
      null != account,
      'There should be account with this Contact ID.'
    );
    System.assert(
      String.isNotEmpty(account.External_Id__c),
      'Returned account should have non empty externalID. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Status__c),
      'Returned account should have non empty Consent_Status__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_Source_URL__c),
      'Returned account should have non empty Consent_Registration_Source_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Consent_Registration_Date__c,
      'Returned account should have non empty Consent_Registration_Date__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text__c),
      'Returned account should have non empty Consent_Text__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text_Version__c),
      'Returned account should have non empty Consent_Text_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Privacy_Policy_Version__c),
      'Returned account should have non empty Privacy_Policy_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_IP_Address__c),
      'Returned account should have non empty Consent_Registration_IP_Address__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Opt_in_URL__c),
      'Returned account should have non empty Opt_in_URL__c. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Opt_out_URL__c),
      'Returned account should have non empty Opt_out_URL__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Confirmation_URL__c),
      'Returned account should have non empty Consent_Confirmation_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Sixteen_Years_or_Older__c,
      'Returned account should have non empty Sixteen_Years_or_Older__c. Account=' +
      account
    );

    System.assert(
      String.isNotEmpty(account.PersonContactId),
      'Returned account should have non empty PersonContactId. Account=' +
      account
    );
    System.assert(
      null != account.Active_Subscription__c,
      'Returned account should have non empty Active_Subscription__c. Account=' +
      account
    );
  }

  @isTest
  static void test_getAccountByContactId_return_null() {
    // under test:
    Account account = AccountSelector.getAccountByContactId(
      'Nonexisting Contact Id'
    );

    // assertions:
    System.assert(
      null == account,
      'There should be no account with this Contact Id. Account=' + account
    );
  }

  @isTest
  static void test_getAccount_return_updateable_fields() {
    // under test:
    Account account = AccountSelector.getAccount('test_2@a.a', 'NL', 'Tassimo');

    // assertions:
    System.assert(
      null != account,
      'There should be account with this data. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.External_Id__c),
      'Returned account should have non empty externalID. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Status__c),
      'Returned account should have non empty Consent_Status__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_Source_URL__c),
      'Returned account should have non empty Consent_Registration_Source_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Consent_Registration_Date__c,
      'Returned account should have non empty Consent_Registration_Date__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text__c),
      'Returned account should have non empty Consent_Text__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Text_Version__c),
      'Returned account should have non empty Consent_Text_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Privacy_Policy_Version__c),
      'Returned account should have non empty Privacy_Policy_Version__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Registration_IP_Address__c),
      'Returned account should have non empty Consent_Registration_IP_Address__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Opt_in_URL__c),
      'Returned account should have non empty Opt_in_URL__c. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.Opt_out_URL__c),
      'Returned account should have non empty Opt_out_URL__c. Account=' +
      account
    );
    System.assert(
      String.isNotEmpty(account.Consent_Confirmation_URL__c),
      'Returned account should have non empty Consent_Confirmation_URL__c. Account=' +
      account
    );
    System.assert(
      null != account.Sixteen_Years_or_Older__c,
      'Returned account should have non empty Sixteen_Years_or_Older__c. Account=' +
      account
    );

    System.assert(
      String.isNotEmpty(account.PersonContactId),
      'Returned account should have non empty PersonContactId. Account=' +
      account
    );
    System.assert(
      null != account.Active_Subscription__c,
      'Returned account should have non empty Active_Subscription__c. Account=' +
      account
    );
  }

  @isTest
  static void test_getAccountExternalId_return_null() {
    // under test:
    Account account = AccountSelector.getAccountExternalId('Nonexisting Id');

    // assertions:
    System.assert(
      null == account,
      'There should be no account with this Contact Id. Account=' + account
    );
  }

  @isTest
  static void test_getAccountExternalId_return_external_id() {
    // setup:
    Account accountWithId = [
      SELECT Id
      FROM Account
      WHERE External_Id__c = 'test_2@a.aNLTassimo'
    ];

    // under test:
    Account account = AccountSelector.getAccountExternalId(accountWithId.Id);

    // assertions:
    System.assert(
      null != account,
      'There should be account with this data. Account=' + account
    );
    System.assert(
      String.isNotEmpty(account.External_Id__c),
      'Returned account should have non empty externalID. Account=' + account
    );
    System.assertEquals(
      'test_2@a.aNLTassimo',
      account.External_Id__c,
      'Returned account External ID should be same as in SOQL in setup'
    );
  }
}