force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Reason__c</fullName>
    <label>Deletion Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_clicked__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_clicked__c</fullName>
    <label>Last E-mail clicked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Email_opened__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_opened__c</fullName>
    <label>Last E-mail opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Last_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Last_Transaction_Date__c</fullName>
    <label>Loyalty Last Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty__c.Loyalty_Total_Points__c</summarizedField>
    <summaryForeignKey>Loyalty__c.Loyalty_Consumer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Query_Limit__c.field-meta.xml
<CustomField>
    <fullName>Query_Limit__c</fullName>
    <description>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</description>
    <inlineHelpText>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</inlineHelpText>
    <label>Query Limit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sample_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Related_Order__c.field-meta.xml
<CustomField>
    <fullName>Related_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Related Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Sample_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <masterLabel>Sample Values</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLNRULE_InactiveAccounts.cls
/************* Run the batch every month  not every day in order to save performance  ******************/
/* 

History
    Created by Wunderman Thompson  09/2022
*/

global without sharing class CLNRULE_InactiveAccounts implements Database.Batchable<SObject> {
  Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
  String queryLimit = settings.Query_Limit__c != null
    ? settings.Query_Limit__c
    : '';
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      'SELECT Id,Type__c, CreatedDate, Deletion_Flag__c, To_be_Deleted_Date__c, Deletion_Reason__c, Last_Email_clicked__c, Last_Email_opened__c, ' +
        'Brand__c,Consent_Status__c,Loyalty_Total_Points__c, IsCustomerPortal,Loyalty_Last_Transaction_Date__c, ' +
        '(SELECT Id,Start_Date__c FROM Orders__r ORDER BY Start_Date__c DESC LIMIT 1) ' +
        'FROM Account ' +
        'WHERE Deletion_Flag__c = false ' +
        'AND (Type__c = \'Registered\' OR Type__c = \'Loyalty\')' +
        queryLimit
    );
  }

  global void execute(Database.BatchableContext BC, List<Account> scope) {
    List<Account> accountsToUpdate = new List<Account>();
    Set<Id> accountIdsWithPortalUser = new Set<Id>();

    for (Account acc : Scope) {
      if (acc.IsCustomerPortal == true) {
        accountIdsWithPortalUser.add(acc.Id);
      }
    }
    List<User> portalUsersList = [
      SELECT Id, Contact.AccountId, LastLoginDate
      FROM User
      WHERE
        IsActive = TRUE
        AND IsPortalEnabled = TRUE
        AND Contact.AccountId IN :accountIdsWithPortalUser
    ];
    Map<Id, User> usersMapWithRelatedAccount = new Map<Id, User>();
    for (User u : portalUsersList) {
      usersMapWithRelatedAccount.put(u.Contact.AccountId, u);
    }

    for (Account acc : scope) {
      /****DTC brands****/
      /****** For DTC using the created date since we do not have the last login date ******/
      if (
        (acc.Brand__c == 'Tassimo' || acc.Brand__c == 'L\'OR') &&
        acc.CreatedDate < Date.today().addYears(-5)
      ) {
        if (acc.Orders__r.size() > 0) {
          if (acc.Orders__r[0].Start_Date__c < Date.today().addYears(-5)) {
            acc.Deletion_Flag__c = true;
            acc.To_be_Deleted_Date__c = date.today();
            acc.Deletion_Reason__c = 'Inactive account';
            accountsToUpdate.add(acc);
          }
        } else {
          acc.Deletion_Flag__c = true;
          acc.To_be_Deleted_Date__c = date.today();
          acc.Deletion_Reason__c = 'Inactive account';
          accountsToUpdate.add(acc);
        }
      } else if (acc.Brand__c == 'Douwe Egberts') {
        /****DE brand****/
        if (
          acc.IsCustomerPortal == true &&
          usersMapWithRelatedAccount.keySet().contains(acc.Id)
        ) {
          /******Account with portal user******/
          Datetime lasLoginDate = usersMapWithRelatedAccount.get(acc.Id)
            .LastLoginDate;
          if (Test.isRunningTest()) {
            lasLoginDate = Date.today().addYears(-6);
          }
          if (
            acc.Loyalty_Total_Points__c == 0 &&
            lasLoginDate < Date.today().addYears(-5) &&
            (acc.Loyalty_Last_Transaction_Date__c == null ||
            acc.Loyalty_Last_Transaction_Date__c < Date.today().addYears(-5))
          ) {
            acc.Deletion_Flag__c = true;
            acc.To_be_Deleted_Date__c = date.today();
            acc.Deletion_Reason__c = 'Inactive account';
            acc.IsCustomerPortal = false;
            accountsToUpdate.add(acc);
          }
        }
      } else if (acc.Brand__c == 'Maison du Café') {
        /****MDC brand****/
        if (
          acc.IsCustomerPortal == true &&
          usersMapWithRelatedAccount.keySet().contains(acc.Id)
        ) {
          /******Account with portal user******/
          Datetime lasLoginDate = usersMapWithRelatedAccount.get(acc.Id)
            .LastLoginDate;
          if (Test.isRunningTest()) {
            lasLoginDate = Date.today().addYears(-2);
          }
          if (lasLoginDate < Date.today().addYears(-1)) {
            acc.Deletion_Flag__c = true;
            acc.To_be_Deleted_Date__c = date.today();
            acc.Deletion_Reason__c = 'Inactive account';
            acc.IsCustomerPortal = false;
            accountsToUpdate.add(acc);
          }
        }
      }
    }
    System.debug('Accounts to be updated \n' + accountsToUpdate);

    try {
      if (!accountsToUpdate.isEmpty()) {
        Database.update(accountsToUpdate, false);
      }
    } catch (Exception e) {
      System.debug(
        'Exception when trying to update accounts ' + e.getMessage()
      );
    }
  }

  global void finish(Database.BatchableContext BC) {
  }
}