force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Confirm_URL__c.field-meta.xml
<CustomField>
    <fullName>Email_Confirm_URL__c</fullName>
    <label>Email Confirm URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Email_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DEPortalUsersConfirmEmailReminderBatch.cls
public without sharing class DEPortalUsersConfirmEmailReminderBatch implements Database.Batchable<SObject> {
  public Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      'SELECT Id, personEmail, Email_Confirm_URL__c, ContactID__pc ' +
        'FROM ACCOUNT ' +
        'WHERE Brand__c = \'Douwe Egberts\' AND Email_Confirmed__c = false AND isCustomerPortal = true ' +
        'AND PersonEmailBouncedDate = null AND CreatedDate = YESTERDAY '
    );
  }

  public void execute(Database.BatchableContext BC, List<Account> scope) {
    Integer count = 0;
    List<Account> targetAccounts = new List<Account>();
    for (Account acc : scope) {
      targetAccounts.add(acc);
      count++;
      if (count == 99) {
        sendConfirmEmailReminder(targetAccounts);
        count = 0;
      }
    }
    if (count > 0) {
      sendConfirmEmailReminder(targetAccounts);
    }
  }

  public void finish(Database.BatchableContext BC) {
  }

  private static void sendConfirmEmailReminder(List<Account> targetAccounts) {
    List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();

    for (Account acc : targetAccounts) {
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
      String[] toAddresses = new List<String>{ acc.personEmail };

      mail.setToAddresses(toAddresses);
      mail.setReplyTo('spaarprogramma@douwe-egberts.com');
      mail.setSenderDisplayName('D.E Spaarprogramma');
      mail.setBccSender(false);
      mail.setUseSignature(false);
      mail.setSaveAsActivity(true);

      mail.setTargetObjectId(acc.ContactID__pc);
      mail.setWhatId(acc.Id);
      mail.setTemplateId(Label.DE_Confirmation_Email_Template_Reminder_ID);
      mailList.add(mail);
    }
    if (mailList.size() > 0) {
      Messaging.SendEmailResult[] results = Messaging.sendEmail(mailList, true);
    }
  }
}