force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Email_Sent_Date__c</fullName>
    <label>Loyalty Email Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLNRULE_InactiveAccountsTest.cls
/* 
History
    Created by Wunderman Thompson  09/2022
*/
@IsTest
public  class CLNRULE_InactiveAccountsTest {
    
    @TestSetup
    static void makeData(){
        
    }

    @IsTest
    static void testDTCAccountsWithOrders(){
        date testDate = Date.TODAY().addYears(-6);
        
            String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
            List<Account> accList = new List<Account>();
            for(integer x=0;x<10;x++){
                Account acct = TestDataBuilder.createAccount();
                acct.recordTypeId = recordTypeId;
                acct.CurrencyISOCode = 'EUR';
                acct.Deletion_Flag__c = false;
                acct.brand__c = 'Tassimo';
                acct.Type__c = 'Registered';
                
                accList.add(acct);
            }
            insert accList;
            
            List<Order__c> orderList = new List<Order__c>(); 
            for(integer i=0;i<5;i++){
                Order__c o = new Order__c(Name= 'Test'+i,Customer__c=accList[i].Id, Start_Date__c = testDate);
                orderList.add(o);
            }
            insert orderList;
            System.debug('orders in test \n'+orderList);
            
            for(Account acc : accList){
                Test.setCreatedDate(acc.Id, testDate);
            }

            Test.startTest();
                CLNRULE_InactiveAccounts testBatch = new CLNRULE_InactiveAccounts();
                DataBase.executeBatch(testBatch);
            Test.stopTest();

            List<Account> checkAccountList = [SELECT Id, Deletion_Flag__c,Last_Email_Send_Date__pc FROM Account ];
            System.debug(checkAccountList);
            for(Account acc : checkAccountList){
                system.assert(acc.Deletion_Flag__c == true);
            }  
    }

    public static testMethod void testDE() {
    	Account acc = new Account();
        acc  = TestDataFactory.testAccountData()[0];
        acc.Loyalty_Email_Sent_Date__c =  System.today();
        acc.Brand__c = 'Douwe Egberts';
        acc.Type__c = 'Loyalty';
        update acc;

        //Test.setCreatedDate(acc.Id, Date.TODAY().addYears(-6));
        
        User u = new User();
        u = TestDataFactory.TestCreateUser(1,true)[0];
        u.ContactId = [SELECT ID FROM CONTACT WHERE ACCOUNTID = :acc.Id].Id;
        u.CommunityNickname = u.Alias;
        insert u;
        
        Test.startTest();
            CLNRULE_InactiveAccounts testBatch = new CLNRULE_InactiveAccounts();
            DataBase.executeBatch(testBatch);
        Test.stopTest();

        List<Account> checkAccountList = [SELECT Id,IsCustomerPortal, Deletion_Flag__c,Last_Email_Send_Date__pc FROM Account WHERE Id = :acc.Id ];
        System.debug(checkAccountList);
        for(Account ac : checkAccountList){
            system.assert(ac.Deletion_Flag__c == true);
        }
    }

    public static testMethod void testMDC() {
    	Account acc = new Account();
        acc  = TestDataFactory.testAccountData()[0];
        acc.Loyalty_Email_Sent_Date__c =  System.today();
        acc.Brand__c = 'Maison du Café';
        acc.Type__c = 'Loyalty';
        update acc;

        //Test.setCreatedDate(acc.Id, Date.TODAY().addYears(-6));
        
        User u = new User();
        u = TestDataFactory.TestCreateUser(1,true)[0];
        u.ContactId = [SELECT ID FROM CONTACT WHERE ACCOUNTID = :acc.Id].Id;
        u.CommunityNickname = u.Alias;
        insert u;
        
        Test.startTest();
            CLNRULE_InactiveAccounts testBatch = new CLNRULE_InactiveAccounts();
            DataBase.executeBatch(testBatch);
        Test.stopTest();

        List<Account> checkAccountList = [SELECT Id,IsCustomerPortal, Deletion_Flag__c,Last_Email_Send_Date__pc FROM Account WHERE Id = :acc.Id];
        for(Account ac : checkAccountList){
            System.assert(ac.Deletion_Flag__c == true);
        }
    }

   
}