force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CampaignSelector_Test.cls
/**
 * @author piotr.tugeman@emark.com
 */
@isTest
private class CampaignSelector_Test {
  @testSetup
  static void beforeEachTest() {
    //3 accounts:
    List<Account> testAccounts = new List<Account>();

    Account account1 = new AccountBuilder()
      .setLastName('FirstName')
      .setEmail('existing@email.com')
      .setCountry('NL')
      .setBrand('Jacobs')
      .build();

    Account account2 = new AccountBuilder()
      .setLastName('SecondName')
      .setEmail('existing@email.com')
      .setCountry('UK')
      .setBrand('Jacobs')
      .build();

    Account account3 = new AccountBuilder()
      .setLastName('ThirdName')
      .setEmail('existing@email.com')
      .setCountry('UK')
      .setBrand('Senseo')
      .build();

    testAccounts.add(account1);
    testAccounts.add(account2);
    testAccounts.add(account3);

    // 3 campaigns:
    List<Campaign> testCampaigns = new List<Campaign>();

    Campaign campaign1 = new Campaign();
    campaign1.Name = 'FirstCampaign';
    campaign1.Brand__c = 'Senseo';
    campaign1.Country__c = 'NL';

    Campaign campaign2 = new Campaign();
    campaign2.Name = 'SecondCampaign';
    campaign2.Brand__c = 'Senseo';
    campaign2.Country__c = 'UK';

    Campaign campaign3 = new Campaign();
    campaign3.Name = 'ThirdCampaign_empty';
    campaign3.Brand__c = 'Tassimo';
    campaign3.Country__c = 'NL';

    testCampaigns.add(campaign1);
    testCampaigns.add(campaign2);
    testCampaigns.add(campaign3);

    Test.startTest();

    insert testAccounts;
    insert testCampaigns;

    // 1st Account as Campaign1 member; 2nd and 3rd Account as Campaign2 member; Campaign3 without members;
    List<CampaignMember> testMembers = new List<CampaignMember>();

    Account account1withPersonContact = [
      SELECT PersonContactId
      FROM Account
      WHERE Id = :account1.Id
    ];
    CampaignMember member1 = new CampaignMember();
    member1.CampaignId = campaign1.Id;
    member1.ContactId = account1withPersonContact.PersonContactId;

    Account account2withPersonContact = [
      SELECT PersonContactId
      FROM Account
      WHERE Id = :account2.Id
    ];
    CampaignMember member2 = new CampaignMember();
    member2.CampaignId = campaign2.Id;
    member2.ContactId = account2withPersonContact.PersonContactId;

    Account account3withPersonContact = [
      SELECT PersonContactId
      FROM Account
      WHERE Id = :account3.Id
    ];
    CampaignMember member3 = new CampaignMember();
    member3.CampaignId = campaign2.Id;
    member3.ContactId = account3withPersonContact.PersonContactId;

    testMembers.add(member1);
    testMembers.add(member2);
    testMembers.add(member3);

    insert testMembers;

    Test.stopTest();
  }

  @isTest
  static void test_getAllCampaignMembers_returns_members() {
    // setup
    // existing campaigns @see beforeEachTest()
    Campaign campaign1 = [SELECT Id FROM Campaign WHERE Name = 'FirstCampaign'];
    Campaign campaign2 = [
      SELECT Id
      FROM Campaign
      WHERE Name = 'SecondCampaign'
    ];
    Campaign campaign3 = [
      SELECT Id
      FROM Campaign
      WHERE Name = 'ThirdCampaign_empty'
    ];

    // under test:
    List<CampaignMember> members1 = CampaignSelector.getAllCampaignMembers(
      campaign1.Id
    );
    List<CampaignMember> members2 = CampaignSelector.getAllCampaignMembers(
      campaign2.Id
    );
    List<CampaignMember> members3 = CampaignSelector.getAllCampaignMembers(
      campaign3.Id
    );

    // assertions:
    System.assertEquals(
      1,
      members1.size(),
      'There should be 1 member of this campaign'
    );
    System.assertEquals(
      2,
      members2.size(),
      'There should be 2 member of this campaign'
    );
    System.assert(
      members3.isEmpty(),
      'There should be 0 member of this campaign'
    );
  }

  @isTest
  static void test_getCampaignByExternalId_returns_null() {
    // setup:
    String nonexistingExternalId = 'Brand-Country-Name';

    // under test:
    Campaign campaign = CampaignSelector.getCampaignByExternalId(
      nonexistingExternalId
    );

    //assertion
    System.assertEquals(null, campaign, 'There should be NO campaign returned');
  }

  @isTest
  static void test_getCampaignByExternalId_returns_something() {
    // setup:
    Campaign existingCampaign = [
      SELECT External_Id__c
      FROM Campaign
      WHERE Name = 'FirstCampaign'
    ];

    // under test:
    Campaign campaign = CampaignSelector.getCampaignByExternalId(
      existingCampaign.External_Id__c
    );

    //assertion
    System.assert(
      null != campaign,
      'There should be campaign returned. campaign:' +
        campaign +
        ' existingCampaign:' +
        existingCampaign
    );
    System.assertEquals(
      'FirstCampaign',
      campaign.Name,
      'Returned Campaign Name should be same as in setup'
    );
  }

  @isTest
  static void test_getCampaignById_returns_null() {
    // setup:
    String nonexistingId = 'none';

    // under test:
    Campaign campaign = CampaignSelector.getCampaignById(nonexistingId);

    //assertion
    System.assertEquals(null, campaign, 'There should be NO campaign returned');
  }

  @isTest
  static void test_getCampaignById_returns_something() {
    // setup:
    Campaign existingCampaign = [
      SELECT Id
      FROM Campaign
      WHERE Name = 'FirstCampaign'
    ];

    // under test:
    Campaign campaign = CampaignSelector.getCampaignById(existingCampaign.Id);

    //assertion
    System.assert(null != campaign, 'There should be campaign returned');
    System.assertEquals(
      'FirstCampaign',
      campaign.Name,
      'Returned Campaign Name should be same as in setup'
    );
  }

  @isTest
  static void test_getCampaignMember_returns_null() {
    // setup:
    Campaign existingCampaign = [
      SELECT Id
      FROM Campaign
      WHERE Name = 'FirstCampaign'
    ];
    String existingCampaignId = existingCampaign.Id;
    String nonexistingContactId = '9999x000000179AAA';

    // under test:
    CampaignMember member = CampaignSelector.getCampaignMember(
      existingCampaignId,
      nonexistingContactId
    );

    //assertion
    System.assertEquals(null, member, 'There should be NO campaign returned');
  }

  @isTest
  static void test_getCampaignMember_returns_something() {
    // setup:
    Campaign existingCampaign = [
      SELECT Id
      FROM Campaign
      WHERE Name = 'FirstCampaign'
    ];
    Account existingAccount = [
      SELECT Id, PersonContactId
      FROM Account
      WHERE LastName = 'FirstName'
    ];
    String existingCampaignId = existingCampaign.Id;
    String existingContactId = existingAccount.PersonContactId;

    // under test:
    CampaignMember member = CampaignSelector.getCampaignMember(
      existingCampaignId,
      existingContactId
    );

    //assertion
    System.assert(null != member, 'There should be campaign returned');
    System.assertEquals(
      existingCampaign.Id,
      member.CampaignId,
      'Returned CampaignMember Campaign Id should be same as in setup'
    );
    System.assertEquals(
      existingAccount.PersonContactId,
      member.ContactId,
      'Returned CampaignMember Contact Id should be same as in setup'
    );
  }

  @isTest
  static void test_getAllCampaignsWithMembers_returns_something() {
    // under test:
    List<Campaign> allCampaigns = CampaignSelector.getAllCampaignsWithMembers();

    // assertions:
    System.assertEquals(
      3,
      allCampaigns.size(),
      'There should be 3 campaigns. AllCampaigns=' + allCampaigns
    );
  }
}