force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brewers_Selected__c.field-meta.xml
<CustomField>
    <fullName>Brewers_Selected__c</fullName>
    <description
  >Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</description>
    <inlineHelpText
  >Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</inlineHelpText>
    <label>Brewers Selected</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brewers_selected</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Confirmation_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Confirmation_URL__c</fullName>
    <label>Commercial Consent Confirmation URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Date__c</fullName>
    <label>Commercial Consent Registration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_IP_Address__c</fullName>
    <label>Commercial Consent Reg. IP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Registration_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Consent_Registration_Source_URL__c</fullName>
    <label>Commercial Consent Reg. Source URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text__c</fullName>
    <label>Commercial Consent Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Text_Version__c.field-meta.xml
<CustomField>
    <fullName>Consent_Text_Version__c</fullName>
    <label>Commercial Consent Text Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Machine_Selection__c.field-meta.xml
<CustomField>
    <fullName>Machine_Selection__c</fullName>
    <label>Machine Selection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_URL__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_URL__c</fullName>
    <label>Opt-in URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_out_URL__c.field-meta.xml
<CustomField>
    <fullName>Opt_out_URL__c</fullName>
    <label>Opt-out URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy_Version__c</fullName>
    <label>Privacy Policy Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Single_Opt_in__c.field-meta.xml
<CustomField>
    <fullName>Single_Opt_in__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Single Opt-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/globalValueSets/Brewers_selected.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Capsule Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>SENSEO Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Automatique Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Expresso Brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Other pad/capsule Coffee appliance</fullName>
    </customValue>
    <customValue>
        <fullName>Filter coffee pot</fullName>
    </customValue>
    <customValue>
        <fullName>Other coffee pot</fullName>
    </customValue>
    <customValue>
        <fullName>I do not have a brewer</fullName>
    </customValue>
    <customValue>
        <fullName>Machine L&apos;OR Barista</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo</fullName>
        <isActive>false</isActive>
        <label>Tassimo</label>
    </customValue>
    <customValue>
        <fullName>Senseo</fullName>
        <isActive>false</isActive>
        <label>Senseo</label>
    </customValue>
    <description>Used to filter presentation on the web based on user choice of picklist values. This is not a brewer registration.</description>
    <masterLabel>Brewers selected</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>CATALAN</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian Nynorsk</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Ukrainian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountBuilder.cls
/**
* @author piotr.tugeman@emark.com
*/
public with sharing class AccountBuilder {
    
    //Customer related:
    private String accountType;
    private String brand;
    private String country;
    private String email;
    private String gender;
    private String firstName;
    private String lastName;
    private String language;
    private String machineSelection;
    
    //Consent Related:
    private String consentRegistrationSourceUrl;
    private Datetime consentRegistrationDate;
    private String consentText;
    private String consentTextVersion;
    private String consentStatus;
    private String privacyPolicyVersion;
    private String consentRegistrationIPAddress;
    private String optInUrl;
    private String optOutUrl;
    private String consentConfirmationUrl;
    private Boolean sixteenYearsOrOlder;
    
    //Shipping Address related:
    private String shippingStreet;
    private String shippingState;
    private String shippingCity;
    private String shippingPostalCode;
    private String shippingCountry;
    
    //Brewer Registration
    private String brewerSelected;
    
    //Billing Address related:
    private String billingStreet;
    private String billingState;
    private String billingCity;
    private String billingPostalCode;
    private String billingCountry;
    
    //SOI
    private Boolean singleOptIn;
    
    //Other:
    private Id accountRecordType;
    private static final Id ACCONT_RECORD_TYPE_PERSON = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
    public static final String CONSENT_STATUS_CONFIRMED = 'Confirmed';
    public static final String CONSENT_STATUS_REGISTERED = 'Registered';//TODO: use picklist value ?
    
    
    
    public AccountBuilder() {
        //always create accounts with RecordType 'PersonAccount'
        setAccountRecordTypePerson();
    }
    
    private AccountBuilder setAccountRecordTypePerson(){
        this.accountRecordType = ACCONT_RECORD_TYPE_PERSON;
        return	this;
    }
    
    public AccountBuilder setConsentStatus( String consentStatus ){
        this.consentStatus=consentStatus;
        return this;
    }
    
    public AccountBuilder setAccountType( String accountType ){
        this.accountType=accountType;
        return this;
    }
    
    public AccountBuilder setBrand( String brandAPIName ){
        this.brand=brandAPIName;
        return this;
    }
    
    public AccountBuilder setCountry( String country ){
        this.country = country;
        return this;
    }
    
    public AccountBuilder setEmail( String email ){
        this.email = email;
        return this;
    }
    
    public AccountBuilder setGender( String gender ){
        this.gender=gender;
        return this;
    }
    
    public AccountBuilder setFirstName( String firstName ){
        this.firstName=firstName;
        return this;
    }
    
    public AccountBuilder setLastName( String lastName ){
        this.lastName = lastName;
        return this;
    }
    
    public AccountBuilder setLanguage( String language ){
        this.language = language;
        return this;
    }
    
    public AccountBuilder setConsentRegistrationSourceUrl( String consentRegistrationSourceUrl ){
        this.consentRegistrationSourceUrl=consentRegistrationSourceUrl;
        return this;
    }
    
    public AccountBuilder setMachineSelection( String machineSelection ){
		this.machineSelection=machineSelection;
		return this;
	}
   
    /**
* consentRegistrationDate 3 formats supported: 
* 'yyyy-MM-dd HH:mm:ss'
* ISO 8601:
* 'yyyy-MM-ddTHH:mm:ssZ'
* 'yyyy-MM-ddTHH:mm:ss.SSSZ'
*/
    public AccountBuilder setConsentRegistrationDate( String consentRegistrationDate ){
        this.consentRegistrationDate = DateTimeUtil.valueOfGmt( consentRegistrationDate );
        return this;
    }
    
    public AccountBuilder setConsentText( String consentText ){
        this.consentText=consentText;
        return this;
    }
    
    public AccountBuilder setConsentTextVersion( String consentTextVersion ){
        this.consentTextVersion=consentTextVersion;
        return this;
    }
    
    public AccountBuilder setPrivacyPolicyVersion( String privacyPolicyVersion ){
        this.privacyPolicyVersion=privacyPolicyVersion;
        return this;
    }
    
    public AccountBuilder setConsentRegistrationIPAddress( String consentRegistrationIPAddress ){
        this.consentRegistrationIPAddress=consentRegistrationIPAddress;
        return this;
    }
    
    public AccountBuilder setOptInUrl( String optInUrl ){
        this.optInUrl=optInUrl;
        return this;
    }
    
    public AccountBuilder setOptOutUrl( String optOutUrl ){
        this.optOutUrl=optOutUrl;
        return this;
    }
    
    public AccountBuilder setConsentConfirmationUrl( String consentConfirmationUrl ){
        this.consentConfirmationUrl=consentConfirmationUrl;
        return this;
    }
    
    public AccountBuilder setSixteenYearsOrOlder( Boolean sixteenYearsOrOlder ){
        this.sixteenYearsOrOlder=sixteenYearsOrOlder;
        return this;
    }
    
    public AccountBuilder setBrewerSelected (String BrewerSelected){
        this.BrewerSelected = BrewerSelected;
        return this;
    }
    
    public AccountBuilder setBillingStreet(String BillingStreet){
        this.BillingStreet = BillingStreet;
        return this;
    }
    
    public AccountBuilder setBillingState(String BillingState){
        this.BillingState = BillingState;
        return this;
    }
    
    public AccountBuilder setBillingCity(String BillingCity){
        this.BillingCity = BillingCity;
        return this;
    }
    
    public AccountBuilder setBillingPostalCode(String BillingPostalCode){
        this.BillingPostalCode = BillingPostalCode;
        return this;
    }
    
    public AccountBuilder setBillingCountry(String BillingCountry){
        this.BillingCountry = BillingCountry;
        return this;
    }
    
    public AccountBuilder setShippingStreet( String ShippingStreet ){
        this.ShippingStreet = ShippingStreet;
        return this;
    }
    
    public AccountBuilder setShippingState( String ShippingState ){
        this.ShippingState = ShippingState;	
        return this;
    }
    
    public AccountBuilder setShippingCity( String ShippingCity ){
        this.ShippingCity = ShippingCity;
        return this;
    }
    
    public AccountBuilder setShippingPostalCode( String ShippingPostalCode ){
        this.ShippingPostalCode = shippingPostalCode;
        return this;
    }
    
    public AccountBuilder setShippingCountry( String ShippingCountry ){
        this.ShippingCountry = ShippingCountry;
        return this;
    }
    
     public AccountBuilder setSingleOptIn(Boolean singleOptIn){
        this.singleOptIn = singleOptIn;
        return this;
    }
    
    public Account build(){
        
        Account acc = new Account();
        
        //Customer related:
        if ( String.isNotEmpty(this.accountType) ){
            acc.Type__c = this.accountType;
        }
        
        if ( String.isNotEmpty(this.country) ){
            acc.Country__c = this.country;
        }
        
        if ( String.isNotEmpty(this.brand) ){
            acc.Brand__c = this.brand;
        }
        
        if ( String.isNotEmpty(this.email) ){
            acc.PersonEmail = this.email;
        }
        
        if ( String.isNotEmpty(this.gender) ){
            acc.Gender__pc = this.gender;
        }
        if ( String.isNotEmpty(this.firstName) ){
            acc.firstName = this.firstName;
        }
        
        acc.lastName = this.lastName;
        
        if ( String.isNotEmpty( this.language ) ){
            acc.Language__c = this.language;
        }
        if ( String.isNotEmpty( this.machineSelection ) ){
			acc.Machine_Selection__c = this.machineSelection;
		}

        //Consent related:		
        if ( String.isNotEmpty(this.consentRegistrationSourceURL) ){
            acc.Consent_Registration_Source_URL__c = this.consentRegistrationSourceURL;
        }
        if ( null != this.consentRegistrationDate ){
            acc.Consent_Registration_Date__c = this.consentRegistrationDate;
        }
        if ( String.isNotEmpty(this.consentText) ){
            acc.Consent_Text__c = this.consentText;
        }
        if ( String.isNotEmpty(this.consentTextVersion) ){
            acc.Consent_Text_Version__c = this.consentTextVersion;
        }
        if ( String.isNotBlank( this.consentStatus ) ){
            acc.Consent_Status__c = this.consentStatus;
        }
        if ( String.isNotEmpty(this.privacyPolicyVersion) ){
            acc.Privacy_Policy_Version__c = this.privacyPolicyVersion;
        }
        if ( String.isNotEmpty(this.consentRegistrationIPAddress) ){
            acc.Consent_Registration_IP_Address__c = this.consentRegistrationIPAddress;
        }
        if ( String.isNotEmpty(this.optInURL) ){
            acc.Opt_in_URL__c = this.optInURL;
        }
        if ( String.isNotEmpty(this.optOutUrl) ){
            acc.Opt_out_URL__c = this.optOutUrl;
        }
        if ( String.isNotEmpty(this.consentConfirmationUrl) ){
            acc.Consent_Confirmation_URL__c = this.consentConfirmationUrl;
        }
        if ( null != this.sixteenYearsOrOlder ){
            acc.Sixteen_Years_or_Older__c = this.sixteenYearsOrOlder;
        }
        
        if( String.isNotEmpty(this.BrewerSelected)){
            acc.Brewers_Selected__c = this.BrewerSelected;
        }
        
        //Billing Address related:
        if(String.isNotEmpty(this.BillingStreet)){
            acc.BillingStreet = this.BillingStreet;
        }
        
        if(String.isNotEmpty(this.BillingState)){
            acc.BillingState = this.BillingState;
        }
        
        if(String.isNotEmpty(this.BillingCity)){
            acc.BillingCity = this.BillingCity;
        }
        
        if(String.isNotEmpty(this.BillingPostalCode)){
            acc.BillingPostalCode = this.BillingPostalCode;
        }
        
        if(String.isNotEmpty(this.BillingCountry)){
            acc.BillingCountry = this.BillingCountry;
        }
        //Shipping Address related:
        if ( String.isNotEmpty( this.ShippingStreet ) ){
            acc.ShippingStreet = this.ShippingStreet;
        }
        if ( String.isNotEmpty( this.ShippingState ) ){
            acc.ShippingState = this.ShippingState;
        }
        if ( String.isNotEmpty( this.ShippingCity ) ){
            acc.ShippingCity = this.ShippingCity;
        }
        if ( String.isNotEmpty( this.ShippingPostalCode ) ){
            acc.ShippingPostalCode = this.ShippingPostalCode;
        }
        if ( String.isNotEmpty( this.ShippingCountry ) ){
            acc.ShippingCountry = this.ShippingCountry;
        }
        
        //single opt in:
        if ( null != this.singleOptIn ){
            acc.Single_Opt_in__c = this.singleOptIn;
        }
        
        //Fields not mapped directly:
        acc.RecordTypeID = this.accountRecordType;
        acc.External_Id__c = this.email + this.country + this.brand;
        return acc;     
    }
}