force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/Brewer_Registration__c.object-meta.xml
<CustomObject>
    <label>Brewer Registration</label>
    <nameField>
        <label>Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brewer Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brewer_Registration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/CLM_Welcome_Mail_Sent__c.field-meta.xml
<CustomField>
    <fullName>CLM_Welcome_Mail_Sent__c</fullName>
    <description>For welcome email journeys</description>
    <label>CLM Welcome Mail Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brewer Registrations</relationshipLabel>
    <relationshipName>Brewer_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brewer Registrations</relationshipLabel>
    <relationshipName>Brewer_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Send_Welcome_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Welcome_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Welcome Email?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/BrewerRegistrationTrigger__c.field-meta.xml
<CustomField>
    <fullName>BrewerRegistrationTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BrewerRegistrationTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/PersonAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>PersonAccountTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PersonAccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bosch</fullName>
    </customValue>
    <customValue>
        <fullName>Cadbury</fullName>
    </customValue>
    <customValue>
        <fullName>Carte Noire</fullName>
    </customValue>
    <customValue>
        <fullName>Costa</fullName>
    </customValue>
    <customValue>
        <fullName>Evergood</fullName>
    </customValue>
    <customValue>
        <fullName>Friele</fullName>
    </customValue>
    <customValue>
        <fullName>Gevalia</fullName>
    </customValue>
    <customValue>
        <fullName>Grand Mere</fullName>
    </customValue>
    <customValue>
        <fullName>Hag</fullName>
    </customValue>
    <customValue>
        <fullName>Jacobs</fullName>
    </customValue>
    <customValue>
        <fullName>Kenco</fullName>
    </customValue>
    <customValue>
        <fullName>Koziol</fullName>
    </customValue>
    <customValue>
        <fullName>L&apos;Or</fullName>
    </customValue>
    <customValue>
        <fullName>Let</fullName>
    </customValue>
    <customValue>
        <fullName>Marabou</fullName>
    </customValue>
    <customValue>
        <fullName>Marcilla</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell House</fullName>
    </customValue>
    <customValue>
        <fullName>Milka</fullName>
    </customValue>
    <customValue>
        <fullName>Oreo</fullName>
    </customValue>
    <customValue>
        <fullName>Ritzenhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Suchard</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo</fullName>
    </customValue>
    <customValue>
        <fullName>Twinings</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Senseo</fullName>
    </customValue>
    <customValue>
        <fullName>Douwe Egberts</fullName>
    </customValue>
    <customValue>
        <fullName>Pickwick</fullName>
    </customValue>
    <customValue>
        <fullName>Maison du Café</fullName>
    </customValue>
    <customValue>
        <fullName>Jacqmotte</fullName>
    </customValue>
    <customValue>
        <fullName>Illy</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLMTriggerFlowClassTest.cls
@isTest
public class CLMTriggerFlowClassTest {
  @isTest
  static void CLMTriggerFlowClassTest() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    ts1.BrewerRegistrationTrigger__c = true;
    insert ts1;

    test.startTest();
    Account account1 = new AccountBuilder()
      .setLastName('TEST')
      .setEmail('test@test.com')
      .setCountry('NL')
      .setBrand('Senseo')
      .build();

    account1.Consent_Status__c = 'Confirmed';
    insert account1;

    Brewer_Registration__C brewer = new Brewer_Registration__C();
    brewer.Customer__c = account1.Id;
    brewer.Brand__c = 'Senseo';
    brewer.Country__c = 'NL';
    brewer.name = 'test';
    insert brewer;
    test.stopTest();
    Brewer_Registration__C brewer_Results1 = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer.Id
    ];
    system.assertEquals(null, brewer_Results1.CLM_Welcome_Mail_Sent__c);
    System.assertEquals(false, brewer_Results1.Send_Welcome_Email__c);
  }
  @isTest
  static void CLMTriggerFlowClassUpdateAccountActiveTest() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    ts1.BrewerRegistrationTrigger__c = true;
    insert ts1;

    test.startTest();
    Account account1 = new AccountBuilder()
      .setLastName('TEST')
      .setEmail('test@test.com')
      .setCountry('NL')
      .setBrand('Senseo')
      .build();

    account1.Consent_Status__c = 'Active';
    insert account1;

    Brewer_Registration__C brewer = new Brewer_Registration__C();
    brewer.Customer__c = account1.Id;
    brewer.Brand__c = 'Senseo';
    brewer.Country__c = 'NL';
    brewer.name = 'test';
    insert brewer;
    test.stopTest();
    Brewer_Registration__C brewer_Results = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer.Id
    ];
    system.assertEquals(
      system.today(),
      brewer_Results.CLM_Welcome_Mail_Sent__c
    );
    System.assertEquals(true, brewer_Results.Send_Welcome_Email__c);
  }
  @isTest
  static void CLMTriggerFlowClassUpdateAccountActivationTest() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.PersonAccountTrigger__c = true;
    ts1.BrewerRegistrationTrigger__c = true;
    insert ts1;

    Account account1 = new AccountBuilder()
      .setLastName('TEST')
      .setEmail('test@test.com')
      .setCountry('NL')
      .setBrand('Senseo')
      .build();

    account1.Consent_Status__c = 'Confirmed';
    insert account1;

    Brewer_Registration__C brewer = new Brewer_Registration__C();
    brewer.Customer__c = account1.Id;
    brewer.Contact__c = account1.personcontactid;
    brewer.Brand__c = 'Senseo';
    brewer.Country__c = 'NL';
    brewer.name = 'test';
    insert brewer;

    Brewer_Registration__C brewer1 = new Brewer_Registration__C();
    brewer1.Customer__c = account1.Id;
    brewer1.Contact__c = account1.personcontactid;
    brewer1.Brand__c = 'Senseo';
    brewer1.Country__c = 'NL';
    brewer1.name = 'test';
    insert brewer1;

    Brewer_Registration__C brewer2 = new Brewer_Registration__C();
    brewer2.Customer__c = account1.Id;
    brewer2.Contact__c = account1.personcontactid;
    brewer2.Brand__c = 'Senseo';
    brewer2.Country__c = 'NL';
    brewer2.name = 'test';
    insert brewer2;
    Brewer_Registration__C before_brewer_Results = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer.Id
    ];
    Brewer_Registration__C before_brewer_Results1 = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer1.Id
    ];
    Brewer_Registration__C before_brewer_Results2 = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer2.Id
    ];

    system.assertEquals(null, before_brewer_Results.CLM_Welcome_Mail_Sent__c);
    system.assertEquals(null, before_brewer_Results1.CLM_Welcome_Mail_Sent__c);
    system.assertEquals(null, before_brewer_Results2.CLM_Welcome_Mail_Sent__c);
    System.assertEquals(false, before_brewer_Results.Send_Welcome_Email__c);
    System.assertEquals(false, before_brewer_Results1.Send_Welcome_Email__c);
    System.assertEquals(false, before_brewer_Results2.Send_Welcome_Email__c);
    test.startTest();
    account1.Consent_Status__c = 'Active';
    update account1;
    test.stopTest();
    Brewer_Registration__C brewer_Results = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer.Id
    ];
    Brewer_Registration__C brewer_Results1 = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer1.Id
    ];
    Brewer_Registration__C brewer_Results2 = [
      SELECT CLM_Welcome_Mail_Sent__c, Send_Welcome_Email__c
      FROM Brewer_Registration__C
      WHERE id = :brewer2.Id
    ];

    system.assertEquals(
      system.today(),
      brewer_Results.CLM_Welcome_Mail_Sent__c
    );
    system.assertEquals(
      system.today(),
      brewer_Results1.CLM_Welcome_Mail_Sent__c
    );
    system.assertEquals(
      system.today(),
      brewer_Results2.CLM_Welcome_Mail_Sent__c
    );
    System.assertEquals(true, brewer_Results.Send_Welcome_Email__c);
    System.assertEquals(true, brewer_Results1.Send_Welcome_Email__c);
    System.assertEquals(true, brewer_Results2.Send_Welcome_Email__c);
  }
}