force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/YotpoAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Yotpo API Endpoints</description>
    <label>YotpoAPI</label>
</CustomObject>

force-app/main/default/objects/YotpoAPI__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client_Id</description>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>client_secret</description>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code</description>
    <label>Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language Code</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>CATALAN</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian Nynorsk</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Ukrainian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YotpoRequestTest.cls
@isTest
public with sharing class YotpoRequestTest {
  @testSetup
  static void testSetup() {
    //Insert YotpoAPI__c Settings
    List<YotpoAPI__c> yotpoList = new List<YotpoAPI__c>();
    YotpoAPI__c yotpoSettings = new YotpoAPI__c();

    yotpoSettings.Name = 'test';
    yotpoSettings.Brand__c = 'Tassimo';
    yotpoSettings.Client_Id__c = 'test';
    yotpoSettings.Client_Secret__c = 'test';
    yotpoSettings.Country__c = 'DE';
    yotpoSettings.Language__c = 'German';

    yotpoList.add(yotpoSettings);

    insert yotpoList;

    //Insert Accounts Settings
    List<Account> accountList = new List<Account>();

    Account acc = new Account(LastName = 'Yotpo Test Confirmed DE Tassimo');
    acc.Consent_Status__c = 'Confirmed';
    acc.Country__c = 'DE';
    acc.Language__c = 'German';
    acc.Brand__c = 'Tassimo';
    acc.PersonEmail = 'test@example.com';

    accountList.add(acc);

    acc = new Account(LastName = 'Yotpo Test Active DE Tassimo');
    acc.Consent_Status__c = 'Active';
    acc.Country__c = 'DE';
    acc.Language__c = 'German';
    acc.Brand__c = 'Tassimo';
    acc.PersonEmail = 'test@example.com';

    accountList.add(acc);

    acc = new Account(LastName = 'Yotpo Test Confirmed NL Tassimo');
    acc.Consent_Status__c = 'Confirmed';
    acc.Country__c = 'NL';
    acc.Language__c = 'German';
    acc.Brand__c = 'Tassimo';
    acc.PersonEmail = 'test@example.com';

    accountList.add(acc);

    acc = new Account(LastName = 'Yotpo Test Confirmed DE Tassimo No Lang');
    acc.Consent_Status__c = 'Confirmed';
    acc.Country__c = 'DE';
    acc.Brand__c = 'Tassimo';
    acc.PersonEmail = 'test@example.com';

    accountList.add(acc);

    insert accountList;
  }

  @isTest
  public static void getYotpoCredentialsTest() {
    Map<String, YotpoAPI__c> credentialsMap = YotpoRequest.getYotpoCredentials();
  }

  @isTest
  public static void getAccountsMapTest() {
    List<id> accountIds = new List<id>();

    for (Account a : [
      SELECT Id, PersonEmail, Country__c, Brand__c, Language__c
      FROM Account
    ]) {
      accountIds.add(a.Id);
    }

    Map<String, String[]> accountsMap = YotpoRequest.getAccountsMap(accountIds);
  }

  @isTest
  public static void getTokenTest() {
    String key = 'DE_German_Tassimo';
    Map<String, YotpoAPI__c> yotpoCredentialsMap = YotpoRequest.getYotpoCredentials();
    YotpoAPI__c credentials = yotpoCredentialsMap.get(key);

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new YotpoApiMock());
    String access_token = YotpoRequest.getToken(credentials);
    Test.stopTest();
  }

  @isTest
  public static void subscribeUsersTest() {
    List<id> accountIds = new List<id>();

    for (Account a : [
      SELECT Id, PersonEmail, Country__c, Brand__c, Language__c
      FROM Account
    ]) {
      accountIds.add(a.Id);
    }

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new YotpoApiMock());
    YotpoRequest.subscribeUsers(accountIds);
    Test.stopTest();
  }

  @isTest
  public static void unsubscribeUsersTest() {
    List<id> accountIds = new List<id>();

    for (Account a : [
      SELECT Id, PersonEmail, Country__c, Brand__c, Language__c
      FROM Account
    ]) {
      accountIds.add(a.Id);
    }

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new YotpoApiMock());
    YotpoRequest.unsubscribeUsers(accountIds);
    Test.stopTest();
  }
}