force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MdCForgotPasswordControllerTest.cls
@isTest
public class MdCForgotPasswordControllerTest {
  @testSetup
  static void setUpTestData() {
    User communityUser = new User();
    communityUser.UserName = 'test@emark.com.mdc.fr';
    communityUser.Email = 'test@emark.com';

    communityUser.FirstName = 'test';
    communityUser.LastName = 'test';

    String nickname = 'testt';
    nickname += String.valueOf(Crypto.getRandomInteger()).substring(1, 7);
    communityUser.CommunityNickname = nickname;

    Account communityAccount = new Account(
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Person Account')
        .getRecordTypeId(),
      FirstName = 'test',
      LastName = 'test',
      PersonEmail = 'test@emark.com',
      Gender__pc = 'Male',
      PersonBirthdate = Date.valueOf('1990-06-03'),
      Sixteen_Years_or_Older__c = true,
      External_id__c = 'test@emark.comFRMaison du Café',
      Brand__c = 'Maison du Café',
      OwnerId = Label.CommunityOwnerID
    );

    insert communityAccount;

    Site.createExternalUser(communityUser, communityAccount.Id);
  }

  @isTest
  static void forgotPasswordTest() {
    Test.startTest();
    MdCForgotPasswordController.forgotPassword(
      'test@emark.com',
      '/forgotpasswordconfirmation'
    );
    Test.stopTest();
  }

  @isTest
  static void forgotPasswordInactiveTest() {
    List<User> u = [
      SELECT Id, Email
      FROM User
      WHERE Profile.Name = 'MdC External Identity User' AND isActive = TRUE
      LIMIT 1
    ];
    u[0].IsActive = false;
    Test.startTest();
    update u;
    MdCForgotPasswordController.forgotPassword(
      u[0].Email,
      '/forgotpasswordconfirmation'
    );
    Test.stopTest();
  }

  @isTest
  static void setExperienceIdTest() {
    Test.startTest();
    MdCForgotPasswordController.setExperienceId('123');
    Test.stopTest();
  }
}