force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CampaignMemberRESTTest.cls
@isTest
global class CampaignMemberRESTTest {
  // Test Class to Test CampaignMemberREST Class - Created for DE265
  // Robbie Schaap 12-12-2018
  @isTest
  static void CampaignMemberRESTTest() {
    test.startTest();
    Account account = new AccountBuilder()
      .setAccountType('Loyalty')
      .setLastName('TestName')
      .build();
    insert account;

    Campaign Camp = new Campaign();
    Camp.Name = 'TEST';
    Camp.Brand__c = 'Senseo';
    Camp.Country__c = 'NL';
    insert Camp;

    test.stopTest();

    Account ACNTEST = [
      SELECT Id, PersonContactId
      FROM Account
      WHERE Id = :account.Id
    ];
    CampaignMember CampMem = new CampaignMember();
    CampMem.Status = 'Registered';
    CampMem.ContactId = ACNTEST.PersonContactId;
    CampMem.CampaignId = Camp.id;
    insert CampMem;

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();

    req.requestURI =
      '/services/apexrest/CampaignMemberGET/CampaignId=' +
      Camp.Id +
      '&ContactId=' +
      ACNTEST.PersonContactId;
    req.addParameter('ContactId', ACNTEST.PersonContactId);
    req.addParameter('CampaignId', Camp.Id);
    req.httpMethod = 'GET';
    req.addHeader('Content-Type', 'application/json');
    RestContext.request = req;
    RestContext.response = res;
    CampaignMemberREST.FullResponse Results = CampaignMemberREST.getCampaignMemberbyCampConId();

    //Success Assertion - Results: Already Member of Campaign
    system.assertEquals(true, Results.success);
    system.assertEquals(
      'Campaign NOT allowed. Consumer ALREADY in Campaign',
      Results.message
    );

    //Delete CampaignMember - Results: Not Yet Member of Campaign
    delete CampMem;
    CampaignMemberREST.FullResponse Results_NYMC = CampaignMemberREST.getCampaignMemberbyCampConId();
    system.assertEquals(true, Results_NYMC.success);
    system.assertEquals(
      'Campaign allowed. Consumer NOT YET in Campaign',
      Results_NYMC.message
    );

    req.requestURI =
      '/services/apexrest/CampaignMemberGET/CampaignId=' +
      ACNTEST.PersonContactId +
      '&ContactId=' +
      ACNTEST.PersonContactId;
    req.addParameter('ContactId', ACNTEST.PersonContactId);
    req.addParameter('CampaignId', Camp.Id);
    req.httpMethod = 'GET';
    req.addHeader('Content-Type', 'application/json');
    RestContext.request = req;
    RestContext.response = res;
    CampaignMemberREST.FullResponse Results_Fault = CampaignMemberREST.getCampaignMemberbyCampConId();

    //Campaign Not found Assertion
    system.assertEquals(false, Results_Fault.success);
    system.assertEquals('Campaign does not exist', Results_Fault.message);
  }
}