force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Commercial_Newsletter__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Newsletter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commercial Newsletter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Withdrawn_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Withdrawn_Date__c</fullName>
    <label>Commercial Consent Withdrawn Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/HighCO_synced__c.field-meta.xml
<CustomField>
    <fullName>HighCO_synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the Customer account is found in HighCO CRM Platform. Specific for France brands.</description>
    <inlineHelpText>This denotes if the Customer account is found in HighCO CRM Platform. Specific for France brands.</inlineHelpText>
    <label>HighCO synced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty__c.Loyalty_Total_Points__c</summarizedField>
    <summaryForeignKey>Loyalty__c.Loyalty_Consumer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Confirmation_Date__c</fullName>
    <label>Opt-in Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Request_Date__c</fullName>
    <label>Opt-in Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Status__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Status__c</fullName>
    <label>Opt-in Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Opt-out</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_in_Status_Changed__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Status_Changed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opt-in Status Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opt_out_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Opt_out_Request_Date__c</fullName>
    <label>Opt-out Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Request_to_be_Forgotten__c.field-meta.xml
<CustomField>
    <fullName>Request_to_be_Forgotten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request to be Forgotten</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Social_Media_Consent__c.field-meta.xml
<CustomField>
    <fullName>Social_Media_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Social Media Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Survey_Consent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/Brewer_Registration__c.object-meta.xml
<CustomObject>
    <label>Brewer Registration</label>
    <nameField>
        <label>Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brewer Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brewer_Registration__c/fields/Account_Commercial_Consent__c.field-meta.xml
<CustomField>
    <fullName>Account_Commercial_Consent__c</fullName>
    <description>Added for the CLM Flow</description>
    <formula>TEXT( Customer__r.Consent_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Commercial Consent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/CLM_Welcome_Mail_Sent__c.field-meta.xml
<CustomField>
    <fullName>CLM_Welcome_Mail_Sent__c</fullName>
    <description>For welcome email journeys</description>
    <label>CLM Welcome Mail Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Consumer_Country__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Country__c</fullName>
    <description>Added to make the CLM Flow working</description>
    <formula>TEXT( Customer__r.Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumer Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brewer Registrations</relationshipLabel>
    <relationshipName>Brewer_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Person_Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Person_Account_Email__c</fullName>
    <formula>Customer__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Person Account Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentSettings__mdt/ConsentSettings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for Consent Status</description>
    <label>Consent Settings</label>
    <pluralLabel>Consent Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConsentSettings__mdt/fields/CompletedBrandList__c.field-meta.xml
<CustomField>
    <fullName>CompletedBrandList__c</fullName>
    <label>CompletedBrandList</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConsentSettings__mdt/fields/CountryList__c.field-meta.xml
<CustomField>
    <fullName>CountryList__c</fullName>
    <description>Country Codes</description>
    <label>CountryList</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty_Transaction__c.Transaction_Amount__c</summarizedField>
    <summaryForeignKey>Loyalty_Transaction__c.Loyalty__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sample_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sample_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bosch</fullName>
    </customValue>
    <customValue>
        <fullName>Cadbury</fullName>
    </customValue>
    <customValue>
        <fullName>Carte Noire</fullName>
    </customValue>
    <customValue>
        <fullName>Costa</fullName>
    </customValue>
    <customValue>
        <fullName>Evergood</fullName>
    </customValue>
    <customValue>
        <fullName>Friele</fullName>
    </customValue>
    <customValue>
        <fullName>Gevalia</fullName>
    </customValue>
    <customValue>
        <fullName>Grand Mere</fullName>
    </customValue>
    <customValue>
        <fullName>Hag</fullName>
    </customValue>
    <customValue>
        <fullName>Jacobs</fullName>
    </customValue>
    <customValue>
        <fullName>Kenco</fullName>
    </customValue>
    <customValue>
        <fullName>Koziol</fullName>
    </customValue>
    <customValue>
        <fullName>L&apos;Or</fullName>
    </customValue>
    <customValue>
        <fullName>Let</fullName>
    </customValue>
    <customValue>
        <fullName>Marabou</fullName>
    </customValue>
    <customValue>
        <fullName>Marcilla</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell House</fullName>
    </customValue>
    <customValue>
        <fullName>Milka</fullName>
    </customValue>
    <customValue>
        <fullName>Oreo</fullName>
    </customValue>
    <customValue>
        <fullName>Ritzenhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Suchard</fullName>
    </customValue>
    <customValue>
        <fullName>Tassimo</fullName>
    </customValue>
    <customValue>
        <fullName>Twinings</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Senseo</fullName>
    </customValue>
    <customValue>
        <fullName>Douwe Egberts</fullName>
    </customValue>
    <customValue>
        <fullName>Pickwick</fullName>
    </customValue>
    <customValue>
        <fullName>Maison du Café</fullName>
    </customValue>
    <customValue>
        <fullName>Jacqmotte</fullName>
    </customValue>
    <customValue>
        <fullName>Illy</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sample_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <masterLabel>Sample Values</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandler.cls
/*********************************************************************
Name    :       AccountTriggerHandler Trigger
Date    :       20 June 2017
Author  :       Anjerico Caburnay
Description:    Trigger handler of AccountTrigger for Account Object
History :       
*********************************************************************/

public class AccountTriggerHandler {
  //calls all methods Before Insert
  public static void onBeforeInsert(List<Account> accountList) {
    System.debug(accountList + 'BEFOREINSERT');
    checkOptInStatusOnInsert(accountList);
    // lastEmailSentHardBounced(accountList);
    // email hard bounced disabled due to Dave's request 02/11/2022
    checkConsentStatusOnInsert(accountList);
  }

  //calls all methods Before Update
  public static void onBeforeUpdate(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    System.debug(accountList + 'BEFOREUPDATE');
    checkAccountTypeIfLoyaltyThenRemainLoyalty(accountList, oldMap);
    checkOptInStatusOnUpdate(accountList, oldMap);
    // lastEmailSentHardBounced(accountList);
    // email hard bounced disabled due to Dave's request 02/11/2022
    gdprConsumerCleaningRules(accountList);
    maskingAccount(accountList, oldMap);
    sendHighCoRequest(accountList, oldMap);
    checkConsentStatusOnUpdate(accountList, oldMap);
  }

  public static void onBeforeDelete(List<Account> accountList) {
    loyaltyTotalPointsDelete(accountList);
    commercialConsent(accountList);
  }

  public static void onAfterInsert(
    List<Account> accountList,
    Map<Id, Account> oldMap,
    Map<Id, Account> newMap
  ) {
    sendYotpoRequestOnAfterInsert(accountList);
  }

  public static void onAfterUpdate(
    List<Account> accountList,
    Map<Id, Account> oldMap,
    Map<Id, Account> newMap
  ) {
    brewerRegistration(accountList, oldMap);
    createLoyaltyRecord(newMap, oldMap);
    sendYotpoRequestOnAfterUpdate(accountList, oldMap);
  }

  // Global - needed for Tests
  public static List<ConsentSettings__mdt> consentSettings {
    get {
      if (consentSettings == null) {
        consentSettings = [
          SELECT Id, CountryList__c, CompletedBrandList__c
          FROM ConsentSettings__mdt
          ORDER BY Id
          LIMIT 1
        ];
      }
      return consentSettings;
    }
    set;
  }

  public static void brewerRegistration(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    Set<Id> accountIds = new Set<Id>();
    for (Account oAccount : accountList) {
      accountIds.add(oAccount.Id);
    }

    List<Brewer_Registration__C> lstBrewerRegs = [
      SELECT
        Id,
        Customer__c,
        Brand__c,
        Country__c,
        CreatedDate,
        Account_Commercial_Consent__c,
        CLM_Welcome_Mail_Sent__c,
        Person_Account_Email__c,
        Consumer_Country__c
      FROM Brewer_Registration__C
      WHERE Customer__c IN :accountIds
    ];
    Map<Id, List<Brewer_Registration__c>> registrationsByAccount = new Map<Id, List<Brewer_Registration__c>>();

    for (Brewer_Registration__c registration : lstBrewerRegs) {
      if (!registrationsByAccount.containsKey(registration.Customer__c)) {
        registrationsByAccount.put(
          registration.Customer__c,
          new List<Brewer_Registration__c>()
        );
      }
      registrationsByAccount.get(registration.Customer__c).add(registration);
    }

    for (Account oAccount : accountList) {
      if (registrationsByAccount.containsKey(oAccount.Id)) {
        List<Brewer_Registration__c> accountRegistrations = registrationsByAccount.get(
          oAccount.Id
        );
        if (
          oldMap.get(oAccount.Id).Consent_Status__c !=
          oAccount.Consent_Status__c &&
          oAccount.Consent_Status__c == 'Active'
        ) {
          CLMTriggerFlowClass.CLMTriggerFlow(accountRegistrations);
        }
      }
    }
  }

  public static void loyaltyTotalPointsDelete(List<Account> accountList) {
    for (Account acc : accountList) {
      if (acc.Loyalty_Total_Points__c > 0 && acc.Type__c == 'Loyalty') {
        acc.addError('Consumer with Active Loyalty Points cannot be deleted');
      }
    }
  }

  public static void commercialConsent(List<Account> accountList) {
    String profileName = [
      SELECT Name
      FROM Profile
      WHERE Id = :UserInfo.getProfileId()
    ]
    .Name;
    for (Account acc : accountList) {
      if (
        profileName != 'JDE DTC Support Agent' &&
        (acc.Consent_Status__c == 'Active' ||
        acc.Consent_Status__c == 'Confirmed')
      ) {
        acc.addError(
          'Consumer with Active or Confirmed consent cannot be deleted'
        );
      }
    }
  }

  //Checks if Opt in Request Date, Opt in Confirmation Date, Opt out Request Date has a value
  //Limitation Note: Intershop will only update one field at a time. So this method will just check one of these three fields
  public static void checkOptInStatusOnInsert(List<Account> accountList) {
    for (Account acc : accountList) {
      if (acc.Opt_in_Request_Date__c != null) {
        acc.Opt_In_Status__c = 'Requested';
        acc.Opt_in_Status_Changed__c = true;
      } else if (acc.Opt_in_Confirmation_Date__c != null) {
        acc.Opt_In_Status__c = 'Confirmed';
        acc.Opt_in_Status_Changed__c = true;
      } else if (acc.Opt_out_Request_Date__c != null) {
        acc.Opt_In_Status__c = 'Opt-out';
        acc.Opt_in_Status_Changed__c = true;
      }
    }
  }

  //Checks if Opt in Request Date, Opt in Confirmation Date, Opt out Request Date is Changed
  //Limitation Note: Intershop will only update one field at a time. So this method will just check one of these three fields
  public static void checkOptInStatusOnUpdate(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    for (Account acc : accountList) {
      if (
        acc.Opt_in_Request_Date__c != null &&
        oldMap.get(acc.Id).Opt_in_Request_Date__c != acc.Opt_in_Request_Date__c
      ) {
        acc.Opt_In_Status__c = 'Requested';
        acc.Opt_in_Status_Changed__c = true;
      } else if (
        acc.Opt_in_Confirmation_Date__c != null &&
        oldMap.get(acc.Id).Opt_in_Confirmation_Date__c !=
        acc.Opt_in_Confirmation_Date__c
      ) {
        acc.Opt_In_Status__c = 'Confirmed';
        acc.Opt_in_Status_Changed__c = true;
      } else if (
        acc.Opt_out_Request_Date__c != null &&
        oldMap.get(acc.Id).Opt_out_Request_Date__c !=
        acc.Opt_out_Request_Date__c
      ) {
        acc.Opt_In_Status__c = 'Opt-out';
        acc.Opt_in_Status_Changed__c = true;
      } else {
        acc.Opt_in_Status_Changed__c = false;
      }
    }
  }

  //Whenever a PersonAccount (all person account record types) is created for all brands. - modified by: angelito.cuello@accenture.com
  public static void checkConsentStatusOnInsert(List<Account> accountList) {
    if (consentSettings.size() > 0) {
      //List<ConsentSettings__mdt> consentSettings = [SELECT Id, CountryList__c, CompletedBrandList__c FROM ConsentSettings__mdt ORDER BY Id LIMIT 1];
      List<String> countryList = (List<String>) JSON.deserialize(
        consentSettings[0].CountryList__c,
        List<String>.class
      );
      List<String> brandList = (List<String>) JSON.deserialize(
        consentSettings[0].CompletedBrandList__c,
        List<String>.class
      );

      for (Account acc : accountList) {
        if (
          acc.Consent_Status__c == 'Confirmed' ||
          acc.Consent_Status__c == 'Active'
        ) {
          if (countryList.contains(acc.Country__c)) {
            if (brandList.contains(acc.Brand__c)) {
              acc.Social_Media_Consent__c = false;
              acc.Survey_Consent__c = false;
              acc.Commercial_Newsletter__c = true;
            }
          } else {
            if (brandList.contains(acc.Brand__c)) {
              acc.Social_Media_Consent__c = true;
              acc.Survey_Consent__c = true;
              acc.Commercial_Newsletter__c = true;
            }
          }
        }
      }
    }
  }

  //Whenever a PersonAccount (all person account record types) is updated for all brands. - modified by: angelito.cuello@accenture.com
  public static void checkConsentStatusOnUpdate(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    if (consentSettings.size() > 0) {
      //List<ConsentSettings__mdt> consentSettings = [SELECT Id, CountryList__c, CompletedBrandList__c FROM ConsentSettings__mdt ORDER BY Id LIMIT 1];
      List<String> countryList = (List<String>) JSON.deserialize(
        consentSettings[0].CountryList__c,
        List<String>.class
      );
      List<String> brandList = (List<String>) JSON.deserialize(
        consentSettings[0].CompletedBrandList__c,
        List<String>.class
      );

      for (Account acc : accountList) {
        if (
          (acc.Consent_Status__c == 'Confirmed' ||
          acc.Consent_Status__c == 'Active') &&
          oldMap.get(acc.Id).Consent_Status__c != acc.Consent_Status__c
        ) {
          if (countryList.contains(acc.Country__c)) {
            if (brandList.contains(acc.Brand__c)) {
              acc.Social_Media_Consent__c = false;
              acc.Survey_Consent__c = false;
              acc.Commercial_Newsletter__c = true;
            }
          } else {
            if (brandList.contains(acc.Brand__c)) {
              acc.Social_Media_Consent__c = true;
              acc.Survey_Consent__c = true;
              acc.Commercial_Newsletter__c = true;
            }
          }
        }
        if (
          acc.Consent_Status__c == 'Withdrawn' &&
          oldMap.get(acc.Id).Consent_Status__c != acc.Consent_Status__c
        ) {
          acc.Social_Media_Consent__c = false;
          acc.Survey_Consent__c = false;
          acc.Commercial_Newsletter__c = false;
        }

        if (
          (acc.Social_Media_Consent__c ||
          acc.Survey_Consent__c ||
          acc.Commercial_Newsletter__c) && acc.Consent_Status__c != 'Confirmed'
        ) {
          if (
            (oldMap.get(acc.Id).Social_Media_Consent__c !=
            acc.Social_Media_Consent__c) ||
            (oldMap.get(acc.Id).Survey_Consent__c != acc.Survey_Consent__c) ||
            (oldMap.get(acc.Id).Commercial_Newsletter__c !=
            acc.Commercial_Newsletter__c)
          ) {
            system.debug('Before Consent Update: ' + acc.Consent_Status__c);
            acc.Consent_Status__c = 'Active';
            acc.Consent_Withdrawn_Date__c = null;
            system.debug('After Consent Update: ' + acc.Consent_Status__c);
          }
        }

        if (
          !acc.Social_Media_Consent__c &&
          !acc.Survey_Consent__c &&
          !acc.Commercial_Newsletter__c
        ) {
          if (
            (oldMap.get(acc.Id).Social_Media_Consent__c !=
            acc.Social_Media_Consent__c) ||
            (oldMap.get(acc.Id).Survey_Consent__c != acc.Survey_Consent__c) ||
            (oldMap.get(acc.Id).Commercial_Newsletter__c !=
            acc.Commercial_Newsletter__c)
          ) {
            acc.Consent_Status__c = 'Withdrawn';
            acc.Consent_Withdrawn_Date__c = DateTime.Now();
          }
        }
      }
    }
  }
  public static void sendYotpoRequestOnAfterInsert(List<Account> accountList) {
    if (System.IsBatch() == false && System.isFuture() == false) {
      if (consentSettings.size() > 0) {
        //List<ConsentSettings__mdt> consentSettings = [SELECT Id, CountryList__c, CompletedBrandList__c FROM ConsentSettings__mdt ORDER BY Id LIMIT 1];
        List<String> countryList = (List<String>) JSON.deserialize(
          consentSettings[0].CountryList__c,
          List<String>.class
        );
        List<String> brandList = (List<String>) JSON.deserialize(
          consentSettings[0].CompletedBrandList__c,
          List<String>.class
        );

        List<Id> subscribeList = new List<Id>();
        List<Id> unsubscribeList = new List<Id>();

        for (Account acc : accountList) {
          //L'Or OR Tassimo
          if (acc.PersonEmail != null && brandList.contains(acc.Brand__c)) {
            if (
              acc.Consent_Status__c == 'Confirmed' ||
              acc.Consent_Status__c == 'Active'
            ) {
              if (!countryList.contains(acc.Country__c)) {
                subscribeList.add(acc.Id);
              } else {
                unsubscribeList.add(acc.Id);
              }
            } else {
              if (countryList.contains(acc.Country__c)) {
                unsubscribeList.add(acc.Id);
              }
            }
          }
        }

        if (subscribeList.size() > 0) {
          //Subscribe call
          System.debug('YotpoRequest: subscribeUsers');
          YotpoRequest.subscribeUsers(subscribeList);
        }

        if (unsubscribeList.size() > 0) {
          //Unsubscribe call
          System.debug('YotpoRequest: unsubscribeUsers');
          YotpoRequest.unsubscribeUsers(unsubscribeList);
        }
      } else {
        System.debug('Error: No Consent settings (Custom Metadata Type)');
      }
    }
  }

  public static void sendYotpoRequestOnAfterUpdate(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    if (System.IsBatch() == false && System.isFuture() == false) {
      if (consentSettings.size() > 0) {
        //List<ConsentSettings__mdt> consentSettings = [SELECT Id, CountryList__c, CompletedBrandList__c FROM ConsentSettings__mdt ORDER BY Id LIMIT 1];
        List<String> countryList = (List<String>) JSON.deserialize(
          consentSettings[0].CountryList__c,
          List<String>.class
        );
        List<String> brandList = (List<String>) JSON.deserialize(
          consentSettings[0].CompletedBrandList__c,
          List<String>.class
        );

        List<Id> subscribeList = new List<Id>();
        List<Id> unsubscribeList = new List<Id>();

        for (Account acc : accountList) {
          //L'Or OR Tassimo
          if (
            acc.PersonEmail != null &&
            brandList.contains(acc.Brand__c) &&
            oldMap.get(acc.Id).Consent_Status__c != acc.Consent_Status__c
          ) {
            if (
              acc.Consent_Status__c == 'Confirmed' ||
              acc.Consent_Status__c == 'Active'
            ) {
              if (!countryList.contains(acc.Country__c)) {
                subscribeList.add(acc.Id);
              } else {
                unsubscribeList.add(acc.Id);
              }
            } else {
              if (countryList.contains(acc.Country__c)) {
                unsubscribeList.add(acc.Id);
              }
            }
          }
        }

        if (subscribeList.size() > 0) {
          //Subscribe call
          System.debug('YotpoRequest: subscribeUsers');
          YotpoRequest.subscribeUsers(subscribeList);
        }

        if (unsubscribeList.size() > 0) {
          //Unsubscribe call
          System.debug('YotpoRequest: unsubscribeUsers');
          YotpoRequest.unsubscribeUsers(unsubscribeList);
        }
      } else {
        System.debug('Error: No Consent settings (Custom Metadata Type)');
      }
    }
  }

  public static void checkAccountTypeIfLoyaltyThenRemainLoyalty(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    for (Account acc : accountList) {
      if (oldMap.get(acc.Id).Type__c == 'Loyalty' && acc.Type__c != 'Loyalty') {
        acc.Type__c = 'Loyalty';
      }
    }
  }

  public static void sendHighCoRequest(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    for (Account acc : accountList) {
      if (acc.PersonEmail != null) {
        if (
          (acc.Consent_Status__c == 'Withdrawn' ||
          acc.Request_to_be_Forgotten__c == true) &&
          acc.HighCO_synced__c == true
        ) {
          acc.HighCO_synced__c = false;
          HighcoRequest.deleteUser(acc.PersonEmail);
        }
      }
    }
  }

  /* public static void lastEmailSentHardBounced(List<Account> accountList){
        for(Account acc : accountList){
        if(acc.Deletion_Flag__c == false && acc.Account_Registration_Status__c != 'Active' && acc.isHardBounced__pc == true){
        acc.To_be_Deleted_Date__c = date.today();
        acc.Deletion_Flag__c = true;
        acc.Deletion_Reason__c = 'Email hard bounced';
        }
        }
        } */

  public static void createLoyaltyRecord(
    Map<Id, Account> newMap,
    Map<Id, Account> oldMap
  ) {
    Map<Id, Account> accMap = new Map<Id, Account>(
      [
        SELECT Id, (SELECT Id FROM Loyalty__r)
        FROM Account
        WHERE ID IN :newMap.keySet()
      ]
    );
    List<Loyalty__c> loyaltyList = new List<Loyalty__c>();
    for (Id accId : newMap.keySet()) {
      Account Id = newMap.get(accId);
      if (accMap.get(accId).Loyalty__r.isEmpty()) {
        if (
          (oldMap.get(accId).Type__c != newMap.get(accId).Type__c &&
          oldMap.get(accId).Type__c == 'Loyalty') ||
          newMap.get(accId).Type__c == 'Loyalty'
        ) {
          Loyalty__c loyaltyRec = new Loyalty__c();
          loyaltyRec.Loyalty_Consumer__c = newMap.get(accId).Id;
          loyaltyRec.External_Id__c = newMap.get(accId).External_Id__c;
          loyaltyList.add(loyaltyRec);
        }
      }
    }
    if (!loyaltyList.isEmpty()) {
      Database.insert(loyaltyList);
    }
  }

  public static void gdprConsumerCleaningRules(List<Account> accountList) {
    List<Account> accList = new List<Account>();
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    for (Account accRec : accountList) {
      if (
        accRec.Request_to_be_Forgotten__c == true &&
        accRec.Deletion_Flag__c == false
      ) {
        /*****Updated****/
        // Request_to_be_Forgotten To be deleted: immediately after request to be forgotten (max 1 day delay)
        // accRec.Deletion_Flag__c = True; => This should be captured & flagged in the AccountWithOrWithoutCampaign class ! because  it should check if the account is already in a campaign
        accRec.Account_Registration_Status__c = 'Deactivated';
        accRec.Consent_Status__c = 'Withdrawn';
        accRec.Account_Deletion_Date__c = date.Today();
        accRec.Consent_Withdrawn_Date__c = DateTime.Now();
      } else if (
        accRec.Consent_Status__c != 'Withdrawn' &&
        accRec.Consent_Status__c != 'Expired' &&
        accRec.Consent_Withdrawn_Date__c != null &&
        accRec.Deletion_Reason__c == Label.DelReason_Consent_Withdrawn
      ) {
        /*****  REVERT THE DELETION FLAG FOR THE USE CASE:  CONSENT WITHDRAWN *****/
        accRec.Consent_Withdrawn_Date__c = null;
        accRec.Deletion_Flag__c = false;
        accRec.Deletion_Reason__c = null;
        accRec.To_be_Deleted_Date__c = null;
      } else if (
        accRec.Consent_Status__c != 'Withdrawn' &&
        accRec.Consent_Status__c != 'Expired' &&
        accRec.Double_Opt_in_Email_Send_Date__c != null &&
        accRec.Consent_Status__c != 'Pending Confirmation' &&
        accRec.Deletion_Reason__c == Label.DelReason_No_Response_Consumer
      ) {
        /*****  REVERT THE DELETION FLAG FOR THE USE CASE:  DOI NOT CONFIRMED *****/
        accRec.Deletion_Flag__c = false;
        accRec.Deletion_Reason__c = null;
        accRec.To_be_Deleted_Date__c = null;
      }
      // this needs to be ommited since we are not using the criteria on Account_Registration_Status__c
      /***********REVERT DELETION FLAG After registration status changes to active ************/
      /* else if(accRec.Account_Registration_Status__c == 'Active' && accRec.Consent_Status__c != 'Withdrawn' && accRec.Consent_Status__c != 'Expired'){
                 
                accRec.Deletion_Flag__c = False;
                accRec.Deletion_Reason__c = null;
                accRec.To_be_Deleted_Date__c = null;
                
            }  */
    }
  }

  public static void maskingAccount(
    List<Account> accountList,
    Map<Id, Account> oldMap
  ) {
    List<Account> accountsToMask = new List<Account>();
    for (Account accRec : accountList) {
      if (
        accRec.Request_to_be_Forgotten__c == true &&
        (oldMap.get(accRec.Id).Request_to_be_Forgotten__c !=
        accRec.Request_to_be_Forgotten__c) &&
        accRec.Type__c == 'Loyalty' &&
        accRec.IsCustomerPortal == true
      ) {
        accRec.FirstName = Label.mskFirstName;
        accRec.LastName = Label.mskLastName;
        accRec.PersonEmail = Label.mskEmail + string.valueOf(Math.random());
        accountsToMask.add(accRec);
      }
    }
    if (!accountsToMask.isEmpty()) {
      MaskingUser.MaskCommunityUserForAccount(accountsToMask);
    }
  }
}