force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/ConsentUrlEncryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in the creation of OptIn/Out URLs</description>
    <label>Consent URL Encryption</label>
</CustomObject>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <label>Initialization Vector</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_In_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_In_URL_Template__c</fullName>
    <label>Opt In URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_Out_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_Out_URL_Template__c</fullName>
    <label>Opt Out URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MdCCommunityHelperTest.cls
@isTest
public class MdCCommunityHelperTest {
  @testSetup
  static void setUpTestData() {
    ConsentUrlEncryption__c testEncryptionRecord = new ConsentUrlEncryption__c(
      Name = 'Maison du Café',
      Algorithm__c = 'AES256',
      Initialization_Vector__c = '7402862816488480',
      Private_Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X',
      Opt_In_URL_Template__c = 'https://moncompte.maisonducafe.com/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf',
      Opt_Out_URL_Template__c = 'https://moncompte.maisonducafe.com/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf'
    );

    insert testEncryptionRecord;

    Account testAccount = new Account(
      FirstName = 'Testy',
      LastName = 'McTestFace',
      PersonEmail = 'testy@emark.com',
      Brand__c = 'Maison du Café',
      PersonBirthdate = Date.valueOf('1990-06-03')
    );

    insert testAccount;
  }

  @isTest
  static void createUserTest() {
    Test.startTest();
    Id communityId = [SELECT Id FROM Network WHERE Name = 'Maison du Café'].Id;
    User user = MdCCommunityHelper.createUser(
      'test@emark.com',
      'Emark',
      'Test',
      '1990-06-03',
      '2011 PX',
      'Teststraat',
      '8',
      'Haarlem',
      'FR',
      communityId,
      '.mdc.fr'
    );
    Test.stopTest();

    System.assert(user != null);
  }

  @isTest
  static void createAccountTest() {
    Test.startTest();
    Id communityId = [SELECT Id FROM Network WHERE Name = 'Maison du Café'].Id;
    Account account = MdCCommunityHelper.createAccount(
      'Emark',
      'Test',
      'test@emark.com',
      'Male',
      '1990-06-03',
      '2011 PX',
      '8',
      'Teststraat',
      'Haarlem',
      'FR',
      'Automatique Brewer',
      true,
      true,
      communityId,
      'Maison du Café'
    );
    Test.stopTest();

    System.assert(account != null);
    System.assert(String.isNotBlank(account.Id));
  }

  /*@isTest static void addRegistrationToMdcCampaignTest() {
		Account testAccount = [SELECT Id FROM Account LIMIT 1];
		Test.startTest();
		//MdCCommunityHelper.addRegistrationToMdcCampaign(testAccount);
		Test.stopTest();
		
		Campaign campaignWithMembers = [SELECT Id, (SELECT Id FROM CampaignMembers) FROM Campaign WHERE External_Id__c = 'Maison du Café-FR-MdCRegistration'];
		System.assert(campaignWithMembers != null);
		System.assert(!campaignWithMembers.CampaignMembers.isEmpty());
	}*/
}