force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MdCUserCreation.cls
public class MdCUserCreation {
  public static List<Id> createUserRecord(List<Account> lstAccount) {
    Set<ID> setAccId = new Set<ID>();
    for (Account acc : lstAccount) {
      try {
        setAccId.add(acc.Id);
      } catch (Exception ex) {
      }
    }
    List<Account> accRec = [
      SELECT
        Id,
        FirstName,
        LastName,
        PersonEmail,
        IsCustomerPortal,
        Type__c,
        Brand__c,
        Consent_Status__c,
        PersonContactId
      FROM Account
      WHERE Id IN :setAccId
    ];
    List<User> lstUsers = new List<User>();
    List<Id> userId = new List<Id>();
    Database.DMLOptions dlo = new Database.DMLOptions();
    dlo.EmailHeader.triggerUserEmail = true;
    for (Account acc : accRec) {
      if (
        acc.IsCustomerPortal == false &&
        acc.Type__c == 'Loyalty' &&
        acc.Brand__c == 'Maison du Café' &&
        acc.Consent_Status__c == 'Active'
      ) {
        User usrRec = new User();
        usrRec.FirstName = acc.FirstName;
        usrRec.LastName = acc.LastName;
        usrRec.Email = acc.PersonEmail;
        usrRec.ProfileId = [
          SELECT Id, Name
          FROM Profile
          WHERE Name = 'MdC External Identity User'
        ]
        .Id;
        usrRec.ContactId = acc.PersonContactId;
        usrRec.userName = acc.PersonEmail + Label.MDCCommunityUserNamePostFix;
        usrRec.alias =
          ((acc.FirstName != null &&
            acc.FirstName.length() > 0)
            ? acc.FirstName.substring(0, 1)
            : '') + acc.LastName.substring(0, 1);
        usrRec.CommunityNickname = CommunityUsersFactory.createRandomDigits(7);
        usrRec.EmailPreferencesAutoBcc = true;
        usrRec.EmailPreferencesAutoBccStayInTouch = false;
        usrRec.EmailPreferencesStayInTouchReminder = false;
        usrRec.UserPreferencesHideS1BrowserUI = true;
        usrRec.LanguageLocaleKey = Label.LanguageLocaleKey;
        usrRec.LocaleSidKey = Label.LocaleSidKey;
        usrRec.TimeZoneSidKey = Label.TimeZoneSidKey;
        usrRec.EmailEncodingKey = Label.EmailEncodingKey;
        lstUsers.add(usrRec);
      }
    }

    if (lstUsers != null) {
      try {
        Database.insert(lstUsers, dlo);
        userId.add(lstUsers[0].AccountId);
      } catch (Exception ex) {
      }
    }
    return userId;
  }
}