force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EncryptionKey__c/EncryptionKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting value will be used in Encryption Key</description>
    <label>EncryptionKey</label>
</CustomObject>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/ProcessBuilderSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ProcessBuilderSettings</label>
</CustomObject>

force-app/main/default/classes/LoyaltyStackTest.cls
@isTest(seeAllData = false)
public class LoyaltyStackTest {
    
    public static EncryptionKey__c encryptionKey = new EncryptionKey__c();
    static List<Loyalty__c> lstloyal;
    
    static {
        encryptionKey = TestDataFactory.setCustomSetting();
        TestDataFactory.setProcessBuilderSettings();
        List<Account> lstacc = TestDataFactory.testAccountData();
        lstloyal = TestDataFactory.testLoyaltyData(lstacc);
    }
    
    @isTest
    static void testLoyaltyInfoisNull(){
        LoyaltyDetails.LoyaltyResponse resp = LoyaltyStack.GetDigitalPointsBalance(null);
        system.assertEquals(Label.ArgumentsMissing, resp.status);
        
        LoyaltyDetails.LoyaltyResponse resp2 = LoyaltyStack.TransactPoints(null);
        system.assertEquals(Label.ArgumentsMissing, resp2.status);
        
        LoyaltyDetails.LoyaltyResponse resp3 = LoyaltyStack.UsePointsForPurchase(null);
        system.assertEquals(Label.ArgumentsMissing, resp3.status);
    }
    
    @isTest
    static void testLoyaltyConsumerNotFound(){
        LoyaltyDetails.LoyaltyInfo loyal = new LoyaltyDetails.LoyaltyInfo();
        loyal.accountNumber = 12300;
        LoyaltyDetails.LoyaltyResponse resp = LoyaltyStack.GetDigitalPointsBalance(loyal);
        //system.assertEquals(Label.ConsumerNotFound, resp.status);
    }
    
    @isTest
    static void testGetDigitalPointsBalanceSuccess(){
        LoyaltyDetails.LoyaltyResponse resp = LoyaltyStack.GetDigitalPointsBalance(loyaltyParams());
        //system.assertEquals(Label.SuccessMessage, resp.status);
    }
    
    @isTest
    static void testTransactPointsSuccess(){
        LoyaltyDetails.LoyaltyInfo loyalInfo = loyaltyParams();
        loyalInfo.mutationType = 'Deposit';
		loyalInfo.regularPointsAmount = 20;
        LoyaltyDetails.LoyaltyResponse resp = LoyaltyStack.TransactPoints(loyalInfo);
        //system.assertEquals(Label.SuccessMessage, resp.status);
        
        loyalInfo = loyaltyParams();
        loyalInfo.mutationType = 'Deposit';
		loyalInfo.regularPointsAmount = 0;
        resp = LoyaltyStack.TransactPoints(loyalInfo);
        //system.assertEquals(Label.SuccessMessage, resp.status);
        
        
        loyalInfo.mutationType = 'Correction';
        loyalInfo.regularPointsAmount = 2;
        LoyaltyDetails.LoyaltyResponse correctionResp = LoyaltyStack.TransactPoints(loyalInfo);
        //system.assertEquals(Label.SuccessMessage, correctionResp.status);
        
        loyalInfo.pointsAmount = 3;
        LoyaltyDetails.LoyaltyResponse resp2 = LoyaltyStack.UsePointsForPurchase(loyalInfo);
    }
    
    
    @isTest
    static void testInsufficientBalanceCorrection(){
        LoyaltyDetails.LoyaltyInfo loyalInfo = loyaltyParams();
        loyalInfo.mutationType = 'Deposit';
		loyalInfo.regularPointsAmount = 2;
        LoyaltyDetails.LoyaltyResponse resp = LoyaltyStack.TransactPoints(loyalInfo);
        //system.assertEquals(Label.SuccessMessage, resp.status);
        
        loyalInfo.mutationType = 'Redeem';
        loyalInfo.regularPointsAmount = 4;
        
        LoyaltyDetails.LoyaltyResponse correctionResp = LoyaltyStack.UsePointsForPurchase(loyalInfo);
        
        Account a = new Account();
        a.LastName = 'Test';
        a.personEmail = 'Test@jde12.com';
        a.External_Id__c = 'Test@jde12.comNLDouwe Egberts';
        a.Brand__c='Douwe Egberts';
        a.Type__c='Loyalty';
        insert a;
        
        Loyalty__c lyl = new Loyalty__c();
        lyl.Loyalty_Consumer__c = a.Id;
        lyl.External_Id__c = 'Test@jde12.comNLDouwe Egberts';
        
        insert lyl;
        
        
        loyalInfo.accountNumber = 1234;
        loyalInfo.referenceID = 'Test Reference';
        loyalInfo.specification = 'Test specification';
        loyalInfo.mutationType = 'Deposit';
		loyalInfo.regularPointsAmount = 2;
        LoyaltyStackHelper.createTransaction(loyalInfo,lyl); 
        
    }
	
    
    @isTest
    static void testTransactionMoreThan50000() {
        ProcessBuilderSettings__c prcSettings = ProcessBuilderSettings__c.getOrgDefaults();
        LoyaltyDetails.LoyaltyInfo loyalInfo = loyaltyParams();
        loyalInfo.regularPointsAmount = 50;
        loyalInfo.mutationType = 'Deposit';
        
        LoyaltyStack.TransactPoints(loyalInfo);
        
        loyalInfo.regularPointsAmount = 50001;
        loyalInfo.mutationType = 'Transfer';
        LoyaltyDetails.LoyaltyResponse resp2 = LoyaltyStack.TransactPoints(loyalInfo);
        //system.assertEquals(Label.ArgumentsMissing, resp2.status);
    }
    
    @isTest
    static void populateValidationErrors() {
        
        LoyaltyDetails.ValidationError loyVal = new LoyaltyDetails.ValidationError();
        List<LoyaltyDetails.ValidationError> lstloyVal = new List<LoyaltyDetails.ValidationError>();
        lstloyVal.add(loyVal);
    }
    @isTest
    static void populateAuthenticationHeader() {
        LoyaltyDetails.AuditHeader loyAuthHdr = new LoyaltyDetails.AuditHeader();
        List<LoyaltyDetails.AuditHeader> lstAuthHdr = new List<LoyaltyDetails.AuditHeader>();
        lstAuthHdr.add(loyAuthHdr);
    }
    
    private static LoyaltyDetails.LoyaltyInfo loyaltyParams(){
        LoyaltyDetails.LoyaltyInfo loyal = new LoyaltyDetails.LoyaltyInfo();
        loyal.accountNumber = Integer.valueOf(lstloyal[0].Name);
        loyal.referenceID = 'SAMPLE-01';
		loyal.specification = 'REF-102';
        return loyal;
    }
}