force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MdCChangePasswordControllerTest.cls
@isTest
public class MdCChangePasswordControllerTest {
    
    @testSetup static void setUpTestData() {
        User communityUser = new User();
        communityUser.UserName =  'test@emark.com.mdc.fr';
        communityUser.Email = 'test@emark.com';
        
        communityUser.FirstName = 'test';
        communityUser.LastName = 'test';
        
        String nickname = 'testt';
        nickname += String.valueOf(Crypto.getRandomInteger()).substring(1,7);
        communityUser.CommunityNickname = nickname;

        Account communityAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
            FirstName = 'test',
            LastName = 'test',
            PersonEmail = 'test@emark.com',
            Gender__pc = 'Male',
            PersonBirthdate = Date.valueOf('1990-06-03'),
            Sixteen_Years_or_Older__c = true,
            External_id__c = 'test@emark.comFRMaison du Café',
            Brand__c = 'Maison du Café',
            OwnerId = Label.CommunityOwnerID
        );

        insert communityAccount;

        Site.createExternalUser(communityUser, communityAccount.Id, 'Testing123!');
    }
    
    @isTest public static void testChangePasswordController() {
        // Instantiate a new controller with all parameters in the page
        PageReference pageRef = Page.MdCCommunityChangePassword;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('setupid', 'ChangePassword');
        MdCChangePasswordController controller = new MdCChangePasswordController();
        
        controller.oldPassword = '123456';
        controller.newPassword = 'qwerty1'; 
        controller.verifyNewPassword = 'qwerty1';                
        
        System.assertEquals(controller.changePassword(),null);                           
    }    
    
    @isTest public static void testChangePasswordDEForgotRequestController() {
        // Instantiate a new controller with all parameters in the page
        PageReference pageRef = Page.MdCCommunityChangePassword;
        Test.setCurrentPage(pageRef);
        MdCChangePasswordController controller = new MdCChangePasswordController();
        
        controller.oldPassword = '';
        controller.newPassword = 'qwerty1'; 
        controller.verifyNewPassword = 'qwerty1';                
        
        System.assertEquals(controller.changePassword(),null);                           
    }   
    
    @isTest public static void testChangePasswordPasswordsAreBlank() {
        // Instantiate a new controller with all parameters in the page
        PageReference pageRef = Page.MdCCommunityChangePassword;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('setupid', 'ChangePassword');
        MdCChangePasswordController controller = new MdCChangePasswordController();
        
        controller.oldPassword = '';
        controller.newPassword = ''; 
        controller.verifyNewPassword = '';                
        
        System.assertEquals(controller.changePassword(),null);                           
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = ''; 
        controller.verifyNewPassword = '';                
        
        System.assertEquals(controller.changePassword(),null); 
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = '1234'; 
        controller.verifyNewPassword = '';                
        
        System.assertEquals(controller.changePassword(),null);  
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = '1234'; 
        controller.verifyNewPassword = '1234';                
        
        System.assertEquals(controller.changePassword(),null);  
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = 'Teset12345'; 
        controller.verifyNewPassword = 'Test12345';                
        
        System.assertEquals(controller.changePassword(),null);  
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = 'Teset12345#'; 
        controller.verifyNewPassword = 'Test12345';                
        
        System.assertEquals(controller.changePassword(),null);  
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = '12345678'; 
        controller.verifyNewPassword = '12345678';      
        
        System.assertEquals(controller.changePassword(),null);  
        
        controller.oldPassword = 'Test1234';
        controller.newPassword = 'ABCDEFGHIJ'; 
        controller.verifyNewPassword = 'ABCDEFGHIJ';      
        
        System.assertEquals(controller.changePassword(),null);  
    }    
    
    @isTest public static void testChangePasswordDENonDERequestController() {
        // Instantiate a new controller with all parameters in the page
        PageReference pageRef = Page.MdCCommunityChangePassword;
        Test.setCurrentPage(pageRef);
        MdCChangePasswordController controller = new MdCChangePasswordController();
        
        controller.oldPassword = '';
        controller.newPassword = 'qwerty1'; 
        controller.verifyNewPassword = 'qwerty1';                
        
        System.assertEquals(controller.changePassword(),null);                           
    }   
    
}