force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sample_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sample_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/YotpoAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Yotpo API Endpoints</description>
    <label>YotpoAPI</label>
</CustomObject>

force-app/main/default/objects/YotpoAPI__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <description>access_token</description>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client_Id</description>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>client_secret</description>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country code</description>
    <label>Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YotpoAPI__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language Code</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>IRE</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>UA</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>CATALAN</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian Nynorsk</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Ukrainian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sample_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <masterLabel>Sample Values</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YotpoRequest.cls
public class YotpoRequest {
    /** 
     * https://apidocs.yotpo.com/reference/about-unsubscribers
     * 
     * By default, all Yotpo customers are opted-in/subscribed and unsubscribers are customers who unsubscribed themselves from one or more Yotpo emails.
     * that means, if we want to remove a set of email addresses from email distribution lists we need to create entries for them on unsubscribe list
    */
    public static final String TOKEN_ENDPOINT = 'https://api.yotpo.com/oauth/token';
    public static final String SUBSCRIBE_ENDPOINT = 'https://api.yotpo.com/apps/{{client_id}}/unsubscribers/mass_delete';
    public static final String UNSUBSCRIBE_ENDPOINT = 'https://api.yotpo.com/apps/{{client_id}}/unsubscribers/mass_create';

    public static final Integer REQUEST_TIMEOUT = 120000;

    public class TokenResponse
    {
        public String access_token;
        public String token_type;
    }

    public class subscribeRequest
    {
        public String utoken;
        public Boolean validate_data;
        public Boolean async;
        public Map<Integer, String[]> email_list;
    }

    public class unsubscribeRequest
    {
        public String utoken;
        public Boolean validate_data;
        public Boolean async;
        public Map<Integer, String[]> email_list;
    }

    public static Map<String, YotpoAPI__c> getYotpoCredentials() {
		List<YotpoAPI__c> yotpoCredentialRecords = [
			SELECT Id, Country__c, Language__c, Brand__c, Client_Id__c, Client_Secret__c, Access_Token__c
            FROM YotpoAPI__c ORDER BY Country__c, Language__c, Brand__c
		];

		Map<String, YotpoAPI__c> yotpoCredentialMap = new Map<String, YotpoAPI__c>();
        String key = '';

		for(YotpoAPI__c row : yotpoCredentialRecords){
            key = row.Country__c + '_' + row.Language__c + '_' + row.Brand__c;
			yotpoCredentialMap.put(key, row);
		}

		return yotpoCredentialMap;
	}

    public static Map<String, String[]> getAccountsMap(List<Id> subscriberIds) {
        List<Account> subscribeList = [SELECT Id, PersonEmail, Country__c, Brand__c, Language__c FROM Account WHERE Id IN :subscriberIds];
        Map<String, String[]> subscribersMap = new Map<String, String[]>();
        String key = '';

        System.debug('YotpoRequest: Gathering subscribers...');

        //Generate users Map
        for(Account row : subscribeList) {
            if(row.Country__c != null && row.Language__c != null && row.Brand__c != null){
                key = row.Country__c + '_' + row.Language__c + '_' + row.Brand__c;

                if(!subscribersMap.containsKey(key)){
                    subscribersMap.put(key, new List<String>());
                }

                subscribersMap.get(key).add(row.PersonEmail);
            } else {
                System.debug('YotpoRequest: Country, Language or Brand is missing for ' + row.PersonEmail);
            }
        }

        System.debug('YotpoRequest: Done. Map size = ' + subscribersMap.size());
        return subscribersMap;
    }

    public static String getToken(YotpoAPI__c credentials) {
        String access_token = '';
        HttpRequest request = new HttpRequest();
        String endpoint = TOKEN_ENDPOINT + '?client_id=' + credentials.Client_Id__c + '&client_secret=' + credentials.Client_Secret__c + '&grant_type=client_credentials';

        try {
            request.setEndpoint(endpoint);
            request.setMethod('GET');
            request.setTimeout(REQUEST_TIMEOUT);
            Http httpProtocol = new Http();
            HttpResponse response = httpProtocol.send(request);
    
            if (response.getStatusCode() == 200) {
                TokenResponse tokenResponse = (TokenResponse)JSON.deserialize(response.getBody(), TokenResponse.class);
                access_token = tokenResponse.access_token;
    
                System.debug('YotpoRequest: Token = ' + access_token);
            } else {
                System.debug('YotpoRequest: Error obtaining token!');
            }
        } catch(CalloutException  e) {
            System.debug('YotpoRequest: Exception Occurred in getToken callout: ' + e.getMessage());
        }
        catch(Exception e)
        {
            System.debug('YotpoRequest: Exception Occurred in getToken: ' + e.getMessage());
        }

        return access_token;
    }

    @future (callout=true)
    public static void subscribeUsers(List<Id> subscriberIds){
        Map<String, YotpoAPI__c> yotpoCredentialsMap = getYotpoCredentials();
        Map<String, String[]> subscribersMap = getAccountsMap(subscriberIds);

        //Iterate through map
        for (String key : subscribersMap.keySet()) {
            if(yotpoCredentialsMap.containsKey(key)){
                YotpoAPI__c credentials = yotpoCredentialsMap.get(key);

                //getToken
                System.debug('YotpoRequest: Obtaining token for key = ' + key);

                String access_token = getToken(credentials);

                if (access_token != null && access_token != '') {
                    //sending subscribe request
                    System.debug('YotpoRequest: Sending subscribe request...');

                    try {
                        HttpRequest request = new HttpRequest();
                        request.setMethod('DELETE');
                        request.setHeader('Content-Type', 'application/json');
                        request.setEndpoint(SUBSCRIBE_ENDPOINT.replace('{{client_id}}', credentials.Client_Id__c));
                        request.setTimeout(REQUEST_TIMEOUT);
    
                        subscribeRequest body = new subscribeRequest();
                        body.utoken = access_token;
                        body.validate_data = true;
                        body.async = true;
                        body.email_list = new Map<Integer, String[]> {
                            1 => subscribersMap.get(key)
                        };
    
                        request.setBody(JSON.serialize(body, true));
    
                        Http httpProtocol = new Http();
                        HttpResponse response = httpProtocol.send(request);
    
                        if (response.getStatusCode() == 200) {
                            System.debug('YotpoRequest: Success!');
                        } else {
                            System.debug('YotpoRequest: Error sending request!: ' + response.getBody());
                        }
                    } catch(CalloutException  e) {
                        System.debug('YotpoRequest: Exception Occurred in subscribeUsers callout: ' + e.getMessage());
                    }
                    catch(Exception e)
                    {
                        System.debug('YotpoRequest: Exception Occurred in subscribeUsers: ' + e.getMessage());
                    }
                 } else {
                    System.debug('YotpoRequest: Token error for key = ' + key);
                 }
            } else {
                System.debug('YotpoRequest: ' + key + ' not found in YotpoAPI custom settings');
            }
        }
    }

    @future (callout=true)
    public static void unsubscribeUsers(List<Id> subscriberIds){
        Map<String, YotpoAPI__c> yotpoCredentialsMap = getYotpoCredentials();
        Map<String, String[]> subscribersMap = getAccountsMap(subscriberIds);

        //Iterate through map
        for (String key : subscribersMap.keySet()) {
            if(yotpoCredentialsMap.containsKey(key)){
                YotpoAPI__c credentials = yotpoCredentialsMap.get(key);

                //getToken
                System.debug('YotpoRequest: Obtaining token for key = ' + key);

                String access_token = getToken(credentials);

                if (access_token != null && access_token != '') {

                    //sending subscribe request
                    System.debug('YotpoRequest: Sending unsubscribe request...');

                    try {
                        HttpRequest request = new HttpRequest();
                        request.setMethod('POST');
                        request.setHeader('Content-Type', 'application/json');
                        request.setEndpoint(UNSUBSCRIBE_ENDPOINT.replace('{{client_id}}', credentials.Client_Id__c));
                        request.setTimeout(REQUEST_TIMEOUT);
    
                        unsubscribeRequest body = new unsubscribeRequest();
                        body.utoken = access_token;
                        body.validate_data = true;
                        body.async = true;
                        body.email_list = new Map<Integer, String[]> {
                            1 => subscribersMap.get(key)
                        };
    
                        request.setBody(JSON.serialize(body, true));
    
                        Http httpProtocol = new Http();
                        HttpResponse response = httpProtocol.send(request);
    
                        if (response.getStatusCode() == 200) {
                            System.debug('YotpoRequest: Success!');
                        } else {
                            System.debug('YotpoRequest: Error sending request!: ' + response.getBody());
                        }
                    } catch(CalloutException  e) {
                        System.debug('YotpoRequest: Exception Occurred in unsubscribeUsers callout: ' + e.getMessage());
                    }
                    catch(Exception e)
                    {
                        System.debug('YotpoRequest: Exception Occurred in unsubscribeUsers: ' + e.getMessage());
                    }
                 } else {
                    System.debug('YotpoRequest: Token error for key = ' + key);
                 }
            } else {
                System.debug('YotpoRequest: ' + key + ' not found in YotpoAPI custom settings');
            }
        }
    }
}