force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaskingUserRecordTest.cls
@isTest(SeeAllData=False)
public class MaskingUserRecordTest {
    
    public static List<Account> lstAccount = new List<Account>(); 
    public static List<User> lstUser = new List<User>();
    
    private static testMethod void testMaskingUser(){
        
        String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
        Account account1 = new Account();
        account1.RecordTypeId = recordTypeId;
        account1.LastName = 'Testing';
        account1.PersonEmail = account1.LastName + '@gmail.com';
        account1.CurrencyIsoCode = 'EUR';
        lstAccount.add(account1);
        insert lstAccount;
        
        Set<ID> setAccId = new Set<ID>();
        for(Account acc : lstAccount){
            try{
                setAccId.add(acc.Id);  
            }
            
            catch(Exception ex){                
            }
        }
        
        Profile p= [SELECT id FROM Profile WHERE Name = 'MdC External Identity User'];
        System.debug('Profile: ' + p.Id);
        for(Account acc : [SELECT Id, FirstName, LastName, PersonEmail, IsCustomerPortal, Type__c, Brand__c, Consent_Status__c, PersonContactId FROM Account WHERE Id IN: setAccId]){
            System.debug('Person Contact ID: ' + acc.PersonContactId);
            User usr = new User( Firstname= acc.FirstName,
                           Lastname = acc.LastName,
                           EmailEncodingKey = 'UTF-8',
                           Email = acc.PersonEmail,
                           ProfileId = p.Id,
                           Username = acc.PersonEmail + '.fr',
                           alias = 'T',
                           LanguageLocaleKey = 'en_US',
                           TimeZoneSidKey = 'America/Los_Angeles',
                           CommunityNickname = CommunityUsersFactory.createRandomDigits(7),
                           IsActive = True
                           );
            usr.LocaleSidKey ='en_US';
            usr.ContactId = acc.PersonContactId;
            lstUser.add(usr);
        }
        
        insert lstUser;
    }
    
   
    //static void createUser{
        //lstAccount = TestDataFactory.testAccountData();
        //lstUser = TestDataFactory.TestCreateUser(4, True);
    //}
   
    @isTest
    static void DeactivateUser(){
        Test.startTest();
        testMaskingUser();
        MaskingUser.MaskCommunityUserForAccount(lstAccount);
        
        Test.stopTest();
    }
}