force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Angebote</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Cadbury</fullName>
            </value>
            <value>
                <fullName>Carte Noire</fullName>
            </value>
            <value>
                <fullName>Costa</fullName>
            </value>
            <value>
                <fullName>Douwe Egberts</fullName>
            </value>
            <value>
                <fullName>Evergood</fullName>
            </value>
            <value>
                <fullName>Friele</fullName>
            </value>
            <value>
                <fullName>Gevalia</fullName>
            </value>
            <value>
                <fullName>Grand Mere</fullName>
            </value>
            <value>
                <fullName>Hag</fullName>
            </value>
            <value>
                <fullName>Jacobs</fullName>
            </value>
            <value>
                <fullName>Kenco</fullName>
            </value>
            <value>
                <fullName>Koziol</fullName>
            </value>
            <value>
                <fullName>L'Or</fullName>
            </value>
            <value>
                <fullName>Let</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Maison du Café</fullName>
            </value>
            <value>
                <fullName>Marabou</fullName>
            </value>
            <value>
                <fullName>Marcilla</fullName>
            </value>
            <value>
                <fullName>Maxwell House</fullName>
            </value>
            <value>
                <fullName>Milka</fullName>
            </value>
            <value>
                <fullName>Oreo</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pickwick</fullName>
            </value>
            <value>
                <fullName>Ritzenhoff</fullName>
            </value>
            <value>
                <fullName>Senseo</fullName>
            </value>
            <value>
                <fullName>Suchard</fullName>
            </value>
            <value>
                <fullName>Tassimo</fullName>
            </value>
            <value>
                <fullName>Twinings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sixteen_Years_or_Older__c.field-meta.xml
<CustomField>
    <fullName>Sixteen_Years_or_Older__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sixteen Years or Older</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/ConsentUrlEncryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in the creation of OptIn/Out URLs</description>
    <label>Consent URL Encryption</label>
</CustomObject>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <label>Initialization Vector</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_In_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_In_URL_Template__c</fullName>
    <label>Opt In URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_Out_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_Out_URL_Template__c</fullName>
    <label>Opt Out URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MdCSelfRegisterControllerTest.cls
@isTest
public class MdCSelfRegisterControllerTest {
  @testSetup
  static void setUpTestData() {
    ConsentUrlEncryption__c testEncryptionRecord = new ConsentUrlEncryption__c(
      Name = 'Maison du Café',
      Algorithm__c = 'AES256',
      Initialization_Vector__c = '7402862816488480',
      Private_Key__c = 'falcwE3A6lFtyNWiPJoVDeHoH6h/QZ7X',
      Opt_In_URL_Template__c = 'https://moncompte.maisonducafe.com/Newsletter/Confirmation/?id=EID&e=EXP&cv=CONSVER&pv=PRIVVER&s=SIG&origin=sf',
      Opt_Out_URL_Template__c = 'https://moncompte.maisonducafe.com/Newsletter/Opt-out/?id=EID&s=SIG&origin=sf'
    );

    insert testEncryptionRecord;

    User communityUser = new User();
    communityUser.UserName = 'test@emark.com.mdc.fr';
    communityUser.Email = 'test@emark.com';

    communityUser.FirstName = 'test';
    communityUser.LastName = 'test';

    String nickname = 'testt';
    nickname += String.valueOf(Crypto.getRandomInteger()).substring(1, 7);
    communityUser.CommunityNickname = nickname;

    Account communityAccount = new Account(
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Person Account')
        .getRecordTypeId(),
      FirstName = 'test',
      LastName = 'test',
      PersonEmail = 'test1@emark.com',
      Gender__pc = 'Male',
      PersonBirthdate = Date.valueOf('1990-06-03'),
      Sixteen_Years_or_Older__c = true,
      External_id__c = 'test1@emark.comFRMaison du Café',
      Brand__c = 'Maison du Café',
      OwnerId = Label.CommunityOwnerID
    );

    insert communityAccount;

    Site.createExternalUser(communityUser, communityAccount.Id, 'Testing123!');

    Account communityAccount2 = new Account(
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Person Account')
        .getRecordTypeId(),
      FirstName = 'test',
      LastName = 'test',
      PersonEmail = 'test2@emark.com',
      Gender__pc = 'Male',
      PersonBirthdate = Date.valueOf('1990-06-03'),
      Sixteen_Years_or_Older__c = true,
      External_id__c = 'test2@emark.comFRMaison du Café',
      Brand__c = 'Maison du Café',
      OwnerId = Label.CommunityOwnerID
    );
    insert communityAccount2;
  }

  @isTest
  static void selfRegisterTest() {
    Test.startTest();
    MdCSelfRegisterController.SelfRegister(
      'Emark',
      'Test',
      'test@emark.com',
      null,
      null,
      null,
      './CheckPasswordResetEmail',
      null,
      false,
      'Male',
      '1990-06-03',
      '2011 PX',
      'Teststraat',
      '8',
      'Haarlem',
      'FR',
      'Automatique Brewer',
      true,
      true
    );
    Test.stopTest();

    Account testAccount = [
      SELECT Id, PersonEmail, IsCustomerPortal
      FROM Account
      WHERE PersonEmail = 'test@emark.com'
    ];
    System.assert(testAccount != null);
  }

  @isTest
  static void selfRegister2Test() {
    Account testAccount = [SELECT Id FROM Account LIMIT 1];

    Test.startTest();
    MdCSelfRegisterController.SelfRegister(
      'Emark',
      'Test',
      'test2@emark.com',
      'Testing123!',
      'Testing123!',
      testAccount.Id,
      './CheckPasswordResetEmail',
      null,
      true,
      'Male',
      '1990-06-03',
      '2011 PX',
      'Teststraat',
      '8',
      'Haarlem',
      null,
      'Automatique Brewer',
      true,
      true
    );
    Test.stopTest();

    Account updatedTestAccount = [
      SELECT Id, PersonEmail, IsCustomerPortal
      FROM Account
      WHERE PersonEmail = 'test2@emark.com'
      LIMIT 1
    ];
    System.assert(updatedTestAccount != null);
  }

  @isTest
  static void selfRegister3Test() {
    Test.startTest();
    MdCSelfRegisterController.SelfRegister(
      'Emark',
      'Test',
      'test1@emark.com',
      null,
      null,
      null,
      './CheckPasswordResetEmail',
      null,
      false,
      'Male',
      '1990-06-03',
      '2011 PX',
      'Teststraat',
      '8',
      'Haarlem',
      'FR',
      'Automatique Brewer',
      true,
      true
    );
    Test.stopTest();

    List<Account> testAccount = [
      SELECT Id, PersonEmail, IsCustomerPortal
      FROM Account
      WHERE PersonEmail = 'test1@emark.com'
    ];
    System.assert(testAccount.size() == 1);
  }

  @isTest
  static void siteAsContainerEnabledTest() {
    Test.startTest();
    Boolean isSelfRegContainer = MdCSelfRegisterController.siteAsContainerEnabled(
      URL.getSalesforceBaseUrl().toExternalForm() + '/s/mdc/login/SelfRegister'
    );
    Test.stopTest();
    //System.assertNotEquals(null, isSelfRegContainer, 'It would work if I could create community user just for UT.' );
  }

  @isTest
  static void returnApplianceOwnershipValuesTest() {
    Test.startTest();
    List<Map<String, String>> applianceValues = MdCSelfRegisterController.returnApplianceOwnershipValues();
    Test.stopTest();

    System.assert(!applianceValues.isEmpty());
  }

  @isTest
  static void setExperienceIdTest() {
    Test.startTest();
    MdCSelfRegisterController.setExperienceId('123');
    Test.stopTest();
  }
}