force-app/main/default/objects/Account/fields/Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>Consent_Status__c</fullName>
    <label>Commercial Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HighCO_synced__c.field-meta.xml
<CustomField>
    <fullName>HighCO_synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the Customer account is found in HighCO CRM Platform. Specific for France brands.</description>
    <inlineHelpText>This denotes if the Customer account is found in HighCO CRM Platform. Specific for France brands.</inlineHelpText>
    <label>HighCO synced?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BoomiAPI__c/BoomiAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BoomiAPI</label>
</CustomObject>

force-app/main/default/objects/BoomiAPI__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BoomiAPI__c/fields/Partner_Key__c.field-meta.xml
<CustomField>
    <fullName>Partner_Key__c</fullName>
    <label>Partner Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BoomiAPI__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HighcoRequestTest.cls
@isTest
public class HighcoRequestTest {
  private static testMethod void testHighcoDelete() {
    BoomiMock mock = new BoomiMock();
    Test.setMock(HttpCalloutMock.class, mock);

    BoomiAPI__c sett = new BoomiAPI__c();
    sett.Partner_Key__c = 'dd';
    sett.Endpoint_URL__c = 'http://';
    sett.Token__c = 'x';
    insert sett;

    List<Account> insertAccs = new List<Account>();
    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.RecordTypeId = recordTypeId;
    accRec.LastName = 'testing 123xdaa';
    accRec.Consent_Status__c = 'Withdrawn';
    accRec.PersonEmail = 'aa@bb.nl';
    insertAccs.add(accRec);
    insert insertAccs;

    accRec.Consent_Status__c = 'Withdrawn';
    accRec.HighCO_synced__c = true;
    update insertAccs;

    Account accrec2 = [
      SELECT PersonEmail
      FROM Account
      WHERE LastName = 'testing 123xdaa'
    ];

    HighcoRequest.deleteUser(accrec2.PersonEmail);
  }
}