force-app/main/default/objects/Account/fields/Data_Migration_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Migration_Id__c</fullName>
    <externalId>true</externalId>
    <label>Data Migration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty__c.Loyalty_Total_Points__c</summarizedField>
    <summaryForeignKey>Loyalty__c.Loyalty_Consumer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Account_Number__c</fullName>
    <label>Loyalty Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Blocked_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Blocked_Date__c</fullName>
    <label>Loyalty Card Blocked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Created_Date__c</fullName>
    <label>Loyalty Card Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Number__c</fullName>
    <label>Loyalty Card Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Card_Status__c</fullName>
    <label>Loyalty Card Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty_Transaction__c.Transaction_Amount__c</summarizedField>
    <summaryForeignKey>Loyalty_Transaction__c.Loyalty__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Data_Migration_ID__c.field-meta.xml
<CustomField>
    <fullName>Data_Migration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Data Migration ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Notes__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Notes__c</fullName>
    <label>Loyalty Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Notes_Reference__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Notes_Reference__c</fullName>
    <label>Loyalty Transaction/Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Total_Loyalty_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyalty_Points__c</fullName>
    <label>Total Loyalty Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltySelector.cls
/**
* All Loyalty and LoyaltyTransaction related SOQL queries.

* @author piotr.tugeman@emark.com
*/
public with sharing class LoyaltySelector {


	public static List<Loyalty__c> getLoyalties( String accountId ){
		List<Loyalty__c> loyalties = [ SELECT Id,
		Name, External_Id__c, Loyalty_Account_Number__c, Loyalty_Card_Blocked_Date__c,
		Loyalty_Card_Created_Date__c, Loyalty_Card_Number__c, Loyalty_Card_Status__c,
		Loyalty_Consumer__c, Loyalty_Total_Points__c
		FROM Loyalty__c
		WHERE Loyalty_Consumer__c=:accountId];

		return loyalties;
	}

	//loyalty.External_Id__c is unique and equal to account.External_Id__c
	public static Loyalty__c getLoyaltyByExternalId( String accountExternalId ){
		List<Loyalty__c> loyalties = [ SELECT Id,
		Name, External_Id__c, Loyalty_Account_Number__c, Loyalty_Card_Blocked_Date__c,
		Loyalty_Card_Created_Date__c, Loyalty_Card_Number__c, Loyalty_Card_Status__c,
		Loyalty_Consumer__c, Loyalty_Total_Points__c
		FROM Loyalty__c
		WHERE External_Id__c=:accountExternalId];

		if ( !loyalties.isEmpty() && 1 == loyalties.size() ){
			return loyalties[0];
		}
		else {
			return null;
		}
	}

	//TODO: is there a need for this method?
	//public static List<Loyalty_Transaction__c> getLoyaltyTransactionsByExternalId( String accountExternalId ){
	//}

	
	public static List<Loyalty_Transaction__c> getLoyaltyTransactions( String accountId, String loyaltyId ){
		List<Loyalty_Transaction__c> transactions = [ SELECT Id,
		Name, Data_Migration_ID__c, CurrencyIsoCode, Loyalty__c, Loyalty_Consumer__c,
		Loyalty_Notes__c, Loyalty_Source__c, Loyalty_Notes_Reference__c, Transaction_Amount__c,
		 Loyalty_Transaction_Type__c, Total_Loyalty_Points__c
		FROM Loyalty_Transaction__c
		WHERE Loyalty__c=:loyaltyId
		AND Loyalty_Consumer__c =:accountId];

		return transactions;
	}

	public static List<Loyalty_Transaction__c> getLoyaltyTransactions( String accountId  ){
		List<Loyalty_Transaction__c> transactions = [ SELECT Id,
		Name, Data_Migration_ID__c, CurrencyIsoCode, Loyalty__c, Loyalty_Consumer__c,
		Loyalty_Notes__c, Loyalty_Source__c, Loyalty_Notes_Reference__c, Transaction_Amount__c,
		Loyalty_Transaction_Type__c, Total_Loyalty_Points__c
		FROM Loyalty_Transaction__c
		WHERE Loyalty_Consumer__c =:accountId];

		return transactions;
	}
}