force-app/main/default/objects/Account/fields/Deletion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateCustomerPortalForAccount.cls
/* Developer: Accenture
   Purpose: Batch class which is called from scheduled class ScheduleUpdateCustomerPortal.
			This class queries all loyalty consumer records where request to be forgotten is true and iscustomer portal is enabled.
		 	The execute method disable community user.*/

/* 
History
    fixed by Wunderman Thompson  09/2022
*/
global class UpdateCustomerPortalForAccount implements Database.batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      [
        SELECT ID, IsCustomerPortal
        FROM ACCOUNT
        WHERE
          Deletion_Flag__c = TRUE
          AND IsCustomerPortal = TRUE
          AND Type__c = 'Loyalty'
      ]
    );
  }
  global void execute(Database.BatchableContext info, List<Account> scope) {
    List<Account> accsToUpdate = new List<Account>();
    for (Account acc : scope) {
      acc.IsCustomerPortal = false;
      accsToUpdate.add(acc);
    }
    if (!accsToUpdate.isEmpty()) {
      update accsToUpdate;
    }
  }
  global void finish(Database.BatchableContext info) {
  }
}