force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Voucher_External_Ids__c.field-meta.xml
<CustomField>
    <fullName>Voucher_External_Ids__c</fullName>
    <label>Voucher External Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Processed_By_Batch__c.field-meta.xml
<CustomField>
    <fullName>Processed_By_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed By Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Voucher_External_Ids__c.field-meta.xml
<CustomField>
    <fullName>Voucher_External_Ids__c</fullName>
    <label>Voucher External Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Redemption_Date__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Date__c</fullName>
    <label>Redemption Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ACN_MatchOrderAndVouchersSchedulableTest.cls
/*********************************************************************
Name    :       ACN_MatchOrderAndVouchersSchedulableTest
Date    :       03 August 2017
Author  :       Anjerico Caburnay
Description:    Test class for ACN_MatchOrderAndVouchersSchedulable Batch Schedulable
History : 
*********************************************************************/

@isTest
private class ACN_MatchOrderAndVouchersSchedulableTest {

	private static testMethod void testScheduler() {
        Test.StartTest();
            List<Voucher__c> voucherList = new List<Voucher__c>();
            for(integer x=0;x<=105;x++){
                Voucher__c vouch = new Voucher__c(Name='Test Vouncher '+x,External_Id__c='1000'+x,Redemption_Date__c=Date.today());
                voucherList.add(vouch);
            }
            insert voucherList;
            
            Account testAsc = new Account(LastName='test Account');
            insert testAsc;
            
            List<Order__c> orderList = new List<Order__c>();
            for(integer y=0;y<=5;y++){
                Order__c ord = new Order__c(Name='test order '+y,Customer__c=testAsc.Id,Processed_By_Batch__c=false,Voucher_External_Ids__c='1000'+y,Start_Date__c=Date.today());
                orderList.add(ord);
            }
            insert orderList;
            
            ACN_MatchOrderAndVouchersSchedulable sh1 = new ACN_MatchOrderAndVouchersSchedulable();      
            String sch = '0 0 15 * * ?';
            system.schedule('Test run schedulable', sch, sh1);
        Test.stopTest();
	}

}