force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Charity__c/Charity__c.object-meta.xml
<CustomObject>
    <label>Charity</label>
    <nameField>
        <label>Charity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Charity__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Donation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Charity__c.field-meta.xml
<CustomField>
    <fullName>Charity__c</fullName>
    <label>Charity</label>
    <referenceTo>Charity__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donated_Points__c.field-meta.xml
<CustomField>
    <fullName>Donated_Points__c</fullName>
    <label>Donated Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/DonorContact__c.field-meta.xml
<CustomField>
    <fullName>DonorContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DonorContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Loyalty_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Transaction</label>
    <referenceTo>Loyalty_Transaction__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Has_Charity__c.field-meta.xml
<CustomField>
    <fullName>Has_Charity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Charity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyDonationRESTResourceTest.cls
@isTest
private class LoyaltyDonationRESTResourceTest {
  @isTest
  static void test_createTransaction() {
    // setup:
    //non existing account @see beforeEachTest():
    mockPOSTRequest(
      '{"loyaltyTransaction":{"loyaltyId":"test@emailNLDE","loyaltyConsumer":"0010D00000JowNoQAJ","transactionAmount":"100","transactionType":"Redeem","loyaltySource":"Episerver","hasCharity":true}}'
    );
    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.RecordTypeId = recordTypeId;
    accRec.LastName = 'testing 123';
    insert accRec;

    Loyalty__c ltyRec = new Loyalty__c();
    ltyRec.Loyalty_Consumer__c = accRec.Id;
    ltyRec.External_Id__c = 'test@emailNLDE';
    insert ltyRec;

    Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
    ltyTransRec.Loyalty__c = ltyRec.Id;
    ltyTransRec.Loyalty_Consumer__c = accRec.Id;
    ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
    ltyTransRec.Loyalty_Source__c = 'Blokker POS';
    ltyTransRec.Transaction_Amount__c = 1000;
    ltyTransRec.Contact__c = accRec.PersonContactId;
    insert ltyTransRec;

    Charity__c chaRec = new Charity__c();
    chaRec.Name = 'Testing123';
    chaRec.External_ID__c = 'Test123';
    insert chaRec;

    Donation__c donationRec = new Donation__c();
    donationRec.Charity__c = chaRec.Id;
    donationRec.Donated_Points__c = 100;
    donationRec.DonorContact__c = ltyTransRec.Contact__c;
    insert donationRec;

    // under test:
    LoyaltyDonationRESTResource.FullResponse response = LoyaltyDonationRESTResource.upsertTransaction();

    /*assertions:
		List<Account> accountsAfter = AccountSelector.getAllAccountsBusinessRelevantFields();
		System.assertEquals(4, accountsAfter.size(), 'There should be 4 accounts (3 Existing + 1 New) response=' + response);
		System.assertEquals( true, response.success, 'Response should be successfull');
		System.assertEquals(response.message, AccountRESTResource.SUCCESS_ACCOUNT_CREATED, 'Response message should inform about account creation');*/
  }

  @isTest
  static void test_readAccountDataFrom_check_if_reads_all_dataTransaction() {
    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.RecordTypeId = recordTypeId;
    accRec.LastName = 'testing 123';
    insert accRec;

    Loyalty__c ltyRec = new Loyalty__c();
    ltyRec.Loyalty_Consumer__c = accRec.Id;
    ltyRec.External_Id__c = 'test@emailNLDE';
    insert ltyRec;

    Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
    ltyTransRec.Loyalty__c = ltyRec.Id;
    ltyTransRec.Loyalty_Consumer__c = accRec.Id;
    ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
    ltyTransRec.Loyalty_Source__c = 'Blokker POS';
    ltyTransRec.Transaction_Amount__c = 1000;
    insert ltyTransRec;

    mockPOSTRequest(
      '{"loyaltyTransaction":{"loyaltyId":"test@emailNLDE","loyaltyConsumer":"0010D00000JowNoQAJ","transactionAmount":"100","transactionType":"Redeem","loyaltySource":"Episerver","hasCharity":true}}'
    );
    Loyalty_Transaction__c createdTransaction = LoyaltyDonationRESTResource.readTransactionDataFrom(
      RestContext.request
    );
    // assertions:
    //System.assertEquals('test@emailNLDE', createdTransaction.Loyalty__c);
    System.assertEquals(
      '0010D00000JowNoQAJ',
      createdTransaction.Loyalty_Consumer__c
    );
    System.assertEquals(100, createdTransaction.Transaction_Amount__c);
    System.assertEquals(
      'Redeem',
      createdTransaction.Loyalty_Transaction_Type__c
    );
    System.assertEquals('Episerver', createdTransaction.Loyalty_Source__c);
    System.assertEquals(true, createdTransaction.Has_Charity__c);
  }

  @isTest
  static void test_readAccountDataFrom_check_if_reads_all_dataDonation() {
    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.RecordTypeId = recordTypeId;
    accRec.LastName = 'testing 123';
    insert accRec;

    Loyalty__c ltyRec = new Loyalty__c();
    ltyRec.Loyalty_Consumer__c = accRec.Id;
    ltyRec.External_Id__c = 'test@emailNLDE';
    insert ltyRec;

    Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
    ltyTransRec.Loyalty__c = ltyRec.Id;
    ltyTransRec.Loyalty_Consumer__c = accRec.Id;
    ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
    ltyTransRec.Loyalty_Source__c = 'Blokker POS';
    ltyTransRec.Transaction_Amount__c = 1000;
    ltyTransRec.Contact__c = accRec.PersonContactId;
    insert ltyTransRec;

    Charity__c chaRec = new Charity__c();
    chaRec.Name = 'Testing123';
    chaRec.External_ID__c = 'Test123';
    insert chaRec;

    Donation__c donationRec = new Donation__c();
    donationRec.Charity__c = chaRec.Id;
    donationRec.Donated_Points__c = 100;
    donationRec.DonorContact__c = ltyTransRec.Contact__c;
    insert donationRec;

    mockPOSTRequest(
      '{"loyaltyTransaction":{"loyaltyId":"test@emailNLDE","loyaltyConsumer":"0010D00000JowNoQAJ","transactionAmount":"-100","transactionType":"Redeem","loyaltySource":"Episerver","hasCharity":true,"donation":{"donatedPoints":"-100","donorId":"0010D00000JowNoQAJ","charityId":"Test123"}}}'
    );
    Donation__c createdDonation = LoyaltyDonationRESTResource.readDonationDataFrom(
      RestContext.request,
      ltyTransRec.Id
    );
    /* assertions:
		System.assertEquals('Test2', createdTransaction.Loyalty__c);
		System.assertEquals('0010D00000JowNoQAJ', createdTransaction.Loyalty_Consumer__c);
		System.assertEquals(100, createdTransaction.Transaction_Amount__c);
		System.assertEquals('Redeem', createdTransaction.Loyalty_Transaction_Type__c);
		System.assertEquals('Episerver', createdTransaction.Loyalty_Source__c);
        System.assertEquals(true, createdTransaction.Has_Charity__c);*/
  }

  private static void mockPOSTRequest(String jsonRequestBody) {
    RestRequest request = new RestRequest();
    request.httpMethod = 'POST';
    request.requestBody = Blob.valueOf(jsonRequestBody);
    RestContext.request = request;
  }
}