force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Charity__c/Charity__c.object-meta.xml
<CustomObject>
    <label>Charity</label>
    <nameField>
        <label>Charity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Charity__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Donation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Charity__c.field-meta.xml
<CustomField>
    <fullName>Charity__c</fullName>
    <label>Charity</label>
    <referenceTo>Charity__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donated_Points__c.field-meta.xml
<CustomField>
    <fullName>Donated_Points__c</fullName>
    <label>Donated Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/DonorContact__c.field-meta.xml
<CustomField>
    <fullName>DonorContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DonorContact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Loyalty_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Transaction</label>
    <referenceTo>Loyalty_Transaction__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Has_Charity__c.field-meta.xml
<CustomField>
    <fullName>Has_Charity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Charity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyDonationBuilderTest.cls
@isTest
private class LoyaltyDonationBuilderTest{
      
    @isTest
	static void test_setLoyaltyId(){
		//underTest:
		
        String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
        Account accRec = new Account();
        accRec.RecordTypeId = recordTypeId;
        accRec.LastName = 'testing 123';
        insert accRec;
        
		Loyalty__c ltyRec = new Loyalty__c();
        ltyRec.Loyalty_Consumer__c = accRec.Id;
        ltyRec.External_Id__c = 'imapaguio+002@gmail.comNLDouwe Egberts';
        insert ltyRec;
        
		Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
        ltyTransRec.Loyalty__c = ltyRec.Id;
        ltyTransRec.Loyalty_Consumer__c = accRec.Id;
        ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
        ltyTransRec.Loyalty_Source__c = 'Blokker POS';
        ltyTransRec.Transaction_Amount__c = 1000;
        insert ltyTransRec;
        
		Loyalty_Transaction__c ltyDonation = new LoyaltyDonationBuilder()
		//.setLoyaltyId(ltyTransRec.Loyalty__c)
		.setLoyaltyId('imapaguio+002@gmail.comNLDouwe Egberts')
		.transactionbuild();
        
		//assertions:
		//System.assertEquals('imapaguio+002@gmail.comNLDouwe Egberts', ltyRec.Loyalty__c);
	}
    
    @isTest
	static void test_setLoyaltyConsumer(){
		//underTest:
		Loyalty_Transaction__c ltyRec = new LoyaltyDonationBuilder()
		.setLoyaltyConsumer('0010D00000JowNoQAJ')
		.transactionbuild();
        
		//assertions:
		System.assertEquals('0010D00000JowNoQAJ', ltyRec.Loyalty_Consumer__c);
	}
    
    @isTest
	static void test_setTransactionAmount(){
		//underTest:
		//Double x = 100;
		Loyalty_Transaction__c ltyRec = new LoyaltyDonationBuilder()
		.setTransactionAmount(100)
		.transactionbuild();
        
		//assertions:
		System.assertEquals(100, ltyRec.Transaction_Amount__c);
	}
    
    @isTest
	static void test_setTransactionType(){
		//underTest:
		Loyalty_Transaction__c ltyRec = new LoyaltyDonationBuilder()
		.setTransactionType('Redeem')
		.transactionbuild();
        
		//assertions:
		System.assertEquals('Redeem', ltyRec.Loyalty_Transaction_Type__c);
	}
    
    @isTest
	static void test_setLoyaltySource(){
		//underTest:
		Loyalty_Transaction__c ltyRec = new LoyaltyDonationBuilder()
		.setLoyaltySource('Episerver')
		.transactionbuild();
        
		//assertions:
		System.assertEquals('Episerver', ltyRec.Loyalty_Source__c);
	}
    
    @isTest
	static void test_setHasCharity(){
		//underTest:
		Loyalty_Transaction__c ltyRec = new LoyaltyDonationBuilder()
		.setHasCharity( true )
		.transactionbuild();
        
		//assertions:
		System.assertEquals(true, ltyRec.Has_Charity__c);
	}
    
    @isTest
	static void test_setDonatedPoints(){
		//underTest:
		Donation__c donRec = new LoyaltyDonationBuilder()
		.setDonatedPoints( 100 )
		.donationbuild();
        
		//assertions:
		System.assertEquals(100, donRec.Donated_Points__c);
	}
    
    @isTest
	static void test_setDonorId(){
		//underTest:
		Donation__c donRec = new LoyaltyDonationBuilder()
		.setDonorId('0010D00000JowNoQAJ')
		.donationbuild();
        
		//assertions:
		System.assertEquals('0010D00000JowNoQAJ', donRec.Donor__c);
	}
    
    /*@isTest
	static void test_setCharityId(){
		//underTest:
		String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
        Account accRec = new Accou/*nt();
        accRec.RecordTypeId = recordTypeId;
        accRec.LastName = 'testing 123';
        insert accRec;
        
		Loyalty__c ltyRec = new Loyalty__c();
        ltyRec.Loyalty_Consumer__c = accRec.Id;
        ltyRec.External_Id__c = 'imapaguio+002@gmail.comNLDouwe Egberts';
        insert ltyRec;
        
		Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
        //Loyalty__c queryLoyalty = [SELECT Id FROM Loyalty__c WHERE External_ID__c = :loyaltyId LIMIT 1];
        ltyTransRec.Loyalty__c = ltyRec.Id;
        ltyTransRec.Loyalty_Consumer__c = accRec.Id;
        ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
        ltyTransRec.Loyalty_Source__c = 'Blokker POS';
        ltyTransRec.Transaction_Amount__c = 1000;
        ltyTransRec.Contact__c = accRec.PersonContactId;
        insert ltyTransRec;
        
        Charity__c chaRec = new Charity__c();
        chaRec.Name = 'Testing123';
        chaRec.External_ID__c = 'Test123';
        insert chaRec; 
        
        Donation__c donationRec = new Donation__c();
        donationRec.Charity__c = chaRec.Id;
        donationRec.Loyalty_Transaction__c = ltyTransRec.Id;
        donationRec.DonorContact__c = ltyTransRec.Contact__c;
      	insert donationRec;
        
		Donation__c donRec = new LoyaltyDonationBuilder()
		.setCharityId('Test123')
		.donationbuild();
        
		//assertions:
		System.assertEquals('Test123', donRec.Charity__c);
	}*/

    @isTest
	static void test_setTransactionId(){
		//underTest:
		
		Donation__c donRec = new LoyaltyDonationBuilder()
		.setTransactionId('a0V0D000001PDS3UAO')
		.donationbuild();
        
		//assertions:
		System.assertEquals('a0V0D000001PDS3UAO', donRec.Loyalty_Transaction__c);
	}
    
    /*@isTest
	static void test_setContactId(){
		//underTest:
		String recordTypeId = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
        Account accRec = new Account();
        accRec.RecordTypeId = recordTypeId;
        accRec.LastName = 'testing 123';
        insert accRec;
        
		Loyalty__c ltyRec = new Loyalty__c();
        ltyRec.Loyalty_Consumer__c = accRec.Id;
        ltyRec.External_Id__c = 'imapaguio+002@gmail.comNLDouwe Egberts';
        insert ltyRec;
        
		Loyalty_Transaction__c ltyTransRec = new Loyalty_Transaction__c();
        ltyTransRec.Loyalty__c = ltyRec.Id;
        ltyTransRec.Loyalty_Consumer__c = accRec.Id;
        ltyTransRec.Loyalty_Transaction_Type__c = 'Compensation';
        ltyTransRec.Loyalty_Source__c = 'Blokker POS';
        ltyTransRec.Transaction_Amount__c = 1000;
        ltyTransRec.Contact__c = accRec.PersonContactId;
        insert ltyTransRec;
        
        Charity__c chaRec = new Charity__c();
        chaRec.Name = 'Testing123';
        chaRec.External_ID__c = 'Test123';
        insert chaRec; 
        
        Donation__c donationRec = new Donation__c();
        donationRec.Charity__c = chaRec.Id;
        donationRec.Loyalty_Transaction__c = ltyTransRec.Id;
        donationRec.DonorContact__c = ltyTransRec.Contact__c;
      	insert donationRec;
        
		Donation__c donRec = new LoyaltyDonationBuilder()
		.setContactId('0030D00000FBHsPQAX')
		.donationbuild();
        
		//assertions:
		//System.assertEquals('0030D00000FBHsPQAX', donRec.DonorContact__c);
	}*/
}