force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Newsletter Subscriber</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Sample Requestor</fullName>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>c</fullName>
                <isActive>false</isActive>
                <label>c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Notes_Reference__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Notes_Reference__c</fullName>
    <label>Loyalty Transaction/Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Total_Loyalty_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Loyalty_Points__c</fullName>
    <label>Total Loyalty Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerHandler.cls
/**
* handler for CampaignMemberTrigger .
*
* @author piotr.tugeman@emark.com

History
    @Fixed by Wunderman Thompson  09/2022
*/
public class CampaignMemberTriggerHandler {
  public static final String LOYALTY_TRANSACTION_TYPE = 'Campaign Reward';
  public static final String LOYALTY_SOURCE = 'Campaign';

  public static void onBeforeInsert(List<CampaignMember> CampaignMemList) {
    customerAccount(CampaignMemList);
  }

  public static void onBeforeUpdate(List<CampaignMember> CampaignMemList) {
    customerAccount(CampaignMemList);
  }
  public static void customerAccount(List<CampaignMember> CampaignMemList) {
    Set<Id> contId = new Set<Id>();
    for (CampaignMember campMemList : CampaignMemList) {
      contId.add(campMemList.ContactId);
    }
    if (!contId.isEmpty()) {
      Map<Id, Contact> contMap = new Map<Id, Contact>(
        [SELECT Id, AccountId FROM Contact WHERE Id IN :contId]
      );
      for (CampaignMember cMemList : CampaignMemList) {
        if (cMemList.Customer__c == null) {
          try {
            cMemList.Customer__c = contMap.get(cMemList.ContactId).AccountId;
          } catch (Exception e) {
            System.debug('Exception while updating the customer__c field' + e);
          }
        }
      }
    }
  }

  /*
    public static void onAfterInsert( List<CampaignMember> campaignMembers ){
        for ( CampaignMember member: campaignMembers ){
            createLoyaltyTransaction( member );
        }
    }
    
    private static void createLoyaltyTransaction( CampaignMember member ){

        Campaign campaign = CampaignSelector.getCampaignById( member.CampaignId );
        if ( null == campaign ){
            System.debug( 'LoyaltyTransaction NOT created. Campaign does not exist. CampaignMember:' + member );
            return;
        }
        if ( false == campaign.Add_Points__c ){
            System.debug( 'LoyaltyTransaction NOT created. Campaign.Add_Points__c is unchecked (false). CampaignMember:' + member + ' Campaign:' + campaign );
            return;
        }

        //TODO: for which Loyalty when more than one? ANSWER: with matching externalID.
        //TODO: Create Loyalty when not available? ANSWER: No.
        Account account = AccountSelector.getAccountByContactId( member.ContactId );
        Loyalty__c loyalty = LoyaltySelector.getLoyaltyByExternalId( account.External_Id__c );
        
        if ( ! shouldGenerateLoyaltyTransaction( account, loyalty ) ){
            System.debug( 'LoyaltyTransaction NOT created for CampaignMember:' + member );
            return;
        }

        Loyalty_Transaction__c loyaltyTransaction = generateLoyaltyTransaction( loyalty, account, campaign );
        saveLoyaltyTransaction ( loyaltyTransaction );
    }

    private static Boolean shouldGenerateLoyaltyTransaction( Account account, Loyalty__c loyalty ){
        //only for Loyalty type accounts with existing Loyalty:
        if ( null == account ){
            System.debug( 'Account does not exist. Account:' + account );
            return false;
        }
        if ( 'Loyalty' != account.Type__c ){
            System.debug( 'Account type is not \'Loyalty\'. AccountType:' + account.Type__c + ' account:' + account );
            return false;
        }
        if ( null == loyalty ){
            System.debug( 'Loyalty does not exist for account:' + account );
            return false;
        }
        if ( account.External_Id__c != loyalty.External_Id__c){
            System.debug( 'Loyalty externalId does not match account externalId. Loyalty:' + loyalty + ' account:' + account );
            return false;
        }
        return true;
    }

    private static Loyalty_Transaction__c generateLoyaltyTransaction( Loyalty__c loyalty, Account account, Campaign campaign ){
        Loyalty_Transaction__c trans = new Loyalty_Transaction__c();
        trans.Loyalty__c = loyalty.Id;
        trans.Loyalty_Consumer__c = account.Id;
        trans.Loyalty_Transaction_Type__c = CampaignMemberTriggerHandler.LOYALTY_TRANSACTION_TYPE;
        trans.Loyalty_Source__c = CampaignMemberTriggerHandler.LOYALTY_SOURCE;
        trans.Loyalty_Notes_Reference__c = Campaign.External_Id__c;
        // transfer points from campaign:
        // Misleading, but campaign points should be stored in Transaction_Amount__c field (NOT Total_Loyalty_Points__c) 
        // trans.Total_Loyalty_Points__c = 0; // TODO: what is the purpose of this field ?
        Decimal points = 0;
        if ( true == campaign.Add_Points__c ){
            points = campaign.Points_Amount__c;
        }  
        trans.Transaction_Amount__c = points;

        return trans;

    }

    private static void saveLoyaltyTransaction( Loyalty_Transaction__c loyaltyTransaction ){
        insert loyaltyTransaction;
        System.debug( 'LoyaltyTransaction iserted. LoyaltyTransaction:' + loyaltyTransaction );
    } */
}