force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Order_Query_Limit__c.field-meta.xml
<CustomField>
    <fullName>Order_Query_Limit__c</fullName>
    <description>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</description>
    <inlineHelpText>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</inlineHelpText>
    <label>Order Query Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Vouchers_Query_Limit__c.field-meta.xml
<CustomField>
    <fullName>Vouchers_Query_Limit__c</fullName>
    <description>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</description>
    <inlineHelpText>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</inlineHelpText>
    <label>Vouchers Query Limit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Voucher_External_Ids__c.field-meta.xml
<CustomField>
    <fullName>Voucher_External_Ids__c</fullName>
    <label>Voucher External Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Processed_By_Batch__c.field-meta.xml
<CustomField>
    <fullName>Processed_By_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed By Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Voucher_External_Ids__c.field-meta.xml
<CustomField>
    <fullName>Voucher_External_Ids__c</fullName>
    <label>Voucher External Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Redemption_Date__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Date__c</fullName>
    <label>Redemption Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ACN_MatchOrderAndVouchersTest.cls
@isTest
private class ACN_MatchOrderAndVouchersTest {
    
    private static testMethod void runBatch() {
        Test.startTest();
        Cleanup_Rules_Settings__c vq = new Cleanup_Rules_Settings__c();
        vq.Vouchers_Query_Limit__c = '5000';
        vq.Order_Query_Limit__c = '5000';
        insert vq;
        
        List<Voucher__c> voucherList = new List<Voucher__c>();
        for(integer x=0;x<=105;x++){
            Voucher__c vouch = new Voucher__c(Name='Test Vouncher '+x,External_Id__c='1000'+x,Redemption_Date__c=Date.today());
            voucherList.add(vouch);
        }
        insert voucherList;
        
        Account testAsc = new Account(LastName='test Account');
        insert testAsc;
        
        List<Order__c> orderList = new List<Order__c>();
        for(integer y=0;y<=5;y++){
            Order__c ord = new Order__c(Name='test order '+y,Customer__c=testAsc.Id,Processed_By_Batch__c=false,Voucher_External_Ids__c='1000'+y,Start_Date__c=Date.today(),External_Id__c='123123'+y);
            orderList.add(ord);
        }
        insert orderList;
        
        system.debug('### Voucher__c: ' + voucherList);
        system.debug('### Order__c: ' + orderList);
        
        Integer qlimit = integer.ValueOf(vq.Order_Query_Limit__c);
        
        List<Order__c> orderCount = [SELECT Id, Voucher_External_Ids__c, Start_Date__c From Order__c WHERE Processed_By_Batch__c = False AND External_Id__c !=null limit :qlimit];
        if(orderCount.size() > 0){
            ACN_MatchOrderAndVouchers runBatch = new ACN_MatchOrderAndVouchers();
            Database.executeBatch(runBatch,2000);
            Test.stopTest();
        }
        
    }
}