force-app/main/default/objects/Account/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty__c.Loyalty_Total_Points__c</summarizedField>
    <summaryForeignKey>Loyalty__c.Loyalty_Consumer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <description
  >This object will hold information like Loyal Card Number, Total Loyalty Points, Total Loyalty Points Redeemed.</description>
    <label>Loyalty</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Loyalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Account_Number__c</fullName>
    <label>Loyalty Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Total_Points__c</fullName>
    <label>Loyalty Total Points</label>
    <summarizedField>Loyalty_Transaction__c.Transaction_Amount__c</summarizedField>
    <summaryForeignKey>Loyalty_Transaction__c.Loyalty__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/Loyalty_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object will store individual transaction details i.e. Loyal Points, Transaction Type, Loyalty Number</description>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Loyalty Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Loyalty__c</fullName>
    <label>Loyalty</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loyalty__c.Loyalty_Consumer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loyalty_Consumer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loyalty__c</referenceTo>
    <relationshipLabel>Loyalty Transactions (Loyalty)</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Consumer__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Consumer__c</fullName>
    <label>Loyalty Consumer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Transactions</relationshipLabel>
    <relationshipName>Loyalty_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Notes__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Notes__c</fullName>
    <label>Loyalty Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Notes_Reference__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Notes_Reference__c</fullName>
    <label>Loyalty Transaction/Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Source__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Source__c</fullName>
    <label>Loyalty Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer Relations</fullName>
                <default>true</default>
                <label>Consumer Relations</label>
            </value>
            <value>
                <fullName>Blokker POS</fullName>
            </value>
            <value>
                <fullName>Blokker WebShop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Episerver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Loyalty_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Transaction_Type__c</fullName>
    <label>Loyalty Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Redeem</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Campaign Reward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Loyalty Transaction Amount</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyStackHelper.cls
/* AUTHOR: Accenture
 * PURPOSE:This is a main service class for LoyaltyStack web service class. The main purpose of this class is to create transaction
 * 		   or return total loyalty balance for the consumer.
 */
public class LoyaltyStackHelper {
  /*This method return false if arguments is null or account number is null*/
  public static Boolean checkArgumentsAreMissing(
    LoyaltyDetails.LoyaltyInfo loyaltyInfo
  ) {
    if (loyaltyInfo == null || loyaltyInfo.accountNumber == null) {
      return true;
    }
    return false;
  }

  /*This method query the total loyalty points for the consumer whose account number matches with the account number received in argument*/
  public static LoyaltyDetails.LoyaltyResponse GetDigitalLoyaltyPointsBalance(
    LoyaltyDetails.LoyaltyInfo loyaltyInfo
  ) {
    LoyaltyDetails.LoyaltyResponse resp = new LoyaltyDetails.LoyaltyResponse();
    if (checkArgumentsAreMissing(loyaltyInfo)) {
      resp.Status = Label.ArgumentsMissing;
      return resp;
    } else {
      try {
        string statusMsg = '';
        List<Loyalty__c> lstLoaylty = new List<Loyalty__c>(
          getLoyaltyDetails(
            new Set<String>{ string.valueOf(loyaltyInfo.accountNumber) }
          )
        );

        resp = populateLoyaltyResponse(lstLoaylty, 0);
      } catch (Exception ex) {
        resp.status = Label.UnknownError;
      }
    }
    return resp;
  }

  /*This method return the loyalty record details where account number is equal to the loyalty name */
  public static List<Loyalty__c> getLoyaltyDetails(
    Set<String> setAccountNumber
  ) {
    system.debug('string is ' + setAccountNumber);
    return [
      SELECT
        ID,
        Loyalty_Total_Points__c,
        Loyalty_Consumer__c,
        Name,
        Loyalty_Account_Number__c
      FROM Loyalty__c
      WHERE Loyalty_Account_Number__c IN :setAccountNumber
    ];
  }
  /*This method populates the Loyalty response class attributes with the loyalty record received as part of reqeust*/
  public static LoyaltyDetails.LoyaltyResponse populateLoyaltyResponse(
    List<Loyalty__c> listLylt,
    Integer pointsUsed
  ) {
    LoyaltyDetails.LoyaltyResponse resp = new LoyaltyDetails.LoyaltyResponse();

    resp.Balance = (listLylt != null && !listLylt.isEmpty()
      ? (Long) listLylt[0].Loyalty_Total_Points__c
      : 0);
    resp.Status = (listLylt != null && !listLylt.isEmpty()
      ? Label.SuccessMessage
      : Label.ConsumerNotFound);
    resp.BonusPointsUsed = 0;
    resp.RegularPointsUsed = (Long) pointsUsed;

    return resp;
  }
  /*This method creates the transaction based on the input received and returns the created transaction as part of response*/
  public static Loyalty_Transaction__c createTransaction(
    LoyaltyDetails.LoyaltyInfo loyaltyInfo,
    Loyalty__c loyalty
  ) {
    Loyalty_Transaction__c trans = new Loyalty_Transaction__c();

    trans.Loyalty__c = loyalty.Id;
    trans.Loyalty_Consumer__c = loyalty.Loyalty_Consumer__c;
    trans.Loyalty_Notes__c = loyaltyInfo.referenceID;
    trans.Loyalty_Notes_Reference__c = loyaltyInfo.specification;
    trans.Loyalty_Source__c = Label.BlokkerPOS;
    trans.Loyalty_Transaction_Type__c = loyaltyInfo.mutationType;
    trans.Transaction_Amount__c = loyaltyInfo.regularPointsAmount;

    try {
      insert trans;
    } catch (Exception ex) {
      if (ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
        throw new applicationException(Label.ArgumentsMissing);
      } else {
        throw new applicationException(Label.UnknownError);
      }
    }

    return trans;
  }
  /*This method creates transaction of type deposit by calling createTransaction method.
      It calls populateLoyaltyResponse method to populate the response for web service operation. 
	*/
  public static LoyaltyDetails.LoyaltyResponse transactPoints(
    LoyaltyDetails.LoyaltyInfo loyaltyInfo
  ) {
    LoyaltyDetails.LoyaltyResponse resp = new LoyaltyDetails.LoyaltyResponse();
    List<Loyalty__c> lstLoyalty = new List<Loyalty__c>();

    if (checkArgumentsAreMissing(loyaltyInfo)) {
      resp.Status = Label.ArgumentsMissing;
      return resp;
    }

    // This is the scenario when Use points for purchase is used. POS makes two successive calls. One with 0 transact points and another
    // for UsePointsForPurchase
    if (loyaltyInfo.pointsAmount == 0 || loyaltyInfo.regularPointsAmount == 0) {
      lstLoyalty = getLoyaltyDetails(
        new Set<String>{ String.valueOf(loyaltyInfo.accountNumber) }
      );
      resp = LoyaltyStackHelper.populateLoyaltyResponse(lstLoyalty, 0);
      return resp;
    }

    try {
      lstLoyalty = getLoyaltyDetails(
        new Set<String>{ String.valueOf(loyaltyInfo.accountNumber) }
      );
      if (lstLoyalty != null && !lstLoyalty.isEmpty()) {
        // Due to some technical reason @Blokker  POS, we are hardcoding this value to Deposit
        loyaltyInfo.mutationType = Label.TransactionTypeDeposit;
        createTransaction(loyaltyInfo, lstLoyalty[0]);
      }
      resp = LoyaltyStackHelper.populateLoyaltyResponse(lstLoyalty, 0);
    } catch (Exception ex) {
      resp.status = ex.getMessage();
      //throw new applicationException(ex.getMessage());
    }

    return resp;
  }

  /*This method is called to redeem the points available to the consumer.
   * This method negates the points requested and calls method createTransaction.
   * It then calls populateLoyaltyResponse method to populate the response attributes.
   */
  public static LoyaltyDetails.LoyaltyResponse usePointsForPurchase(
    LoyaltyDetails.LoyaltyInfo loyaltyInfo
  ) {
    LoyaltyDetails.LoyaltyResponse resp = new LoyaltyDetails.LoyaltyResponse();
    List<Loyalty__c> lstLoyalty = new List<Loyalty__c>();
    if (
      checkArgumentsAreMissing(loyaltyInfo) || loyaltyInfo.pointsAmount == null
    ) {
      resp.Status = Label.ArgumentsMissing;
      return resp;
    }
    try {
      loyaltyInfo.regularPointsAmount = (-1) * loyaltyInfo.pointsAmount;
      loyaltyInfo.mutationType = Label.TransactionTypeRedeem;
      lstLoyalty = getLoyaltyDetails(
        new Set<String>{ String.valueOf(loyaltyInfo.accountNumber) }
      );

      if (lstLoyalty != null && !lstLoyalty.isEmpty()) {
        createTransaction(loyaltyInfo, lstLoyalty[0]);
      }
      resp = LoyaltyStackHelper.populateLoyaltyResponse(lstLoyalty, 0);
    } catch (Exception ex) {
      resp.status = ex.getMessage();
      //throw new applicationException(ex.getMessage());
    }

    return resp;
  }
}