force-app/main/default/objects/Account/fields/New_Email__c.field-meta.xml
<CustomField>
    <fullName>New_Email__c</fullName>
    <label>New Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Email_Request_Datetime__c.field-meta.xml
<CustomField>
    <fullName>New_Email_Request_Datetime__c</fullName>
    <label>New Email Request Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/DE_Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DE community settings</label>
</CustomObject>

force-app/main/default/objects/DE_Community_Settings__c/fields/Get_Token_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Get_Token_Endpoint__c</fullName>
    <label>Get Token Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/fields/Grant_type__c.field-meta.xml
<CustomField>
    <fullName>Grant_type__c</fullName>
    <label>Grant type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/fields/Security_Token__c.field-meta.xml
<CustomField>
    <fullName>Security_Token__c</fullName>
    <label>Security Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/fields/Update_Account_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Update_Account_Endpoint__c</fullName>
    <label>Update Account Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_Community_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LightningConfMailChangeCTest.cls
@IsTest
public with sharing class LightningConfMailChangeCTest {
    @TestSetup
    static void makeData(){
        DE_Community_Settings__c DE = new DE_Community_Settings__c(SetupOwnerId=UserInfo.getOrganizationId());
        DE.Get_Token_Endpoint__c = '/testEndpoint';
        DE.Grant_type__c = 'password';
        DE.username__c = 'fakeUsername';
        DE.password__c = 'fakePassword';
        DE.Security_Token__c = 'fakeToken';
        DE.Client_Id__c = 'fakeClientId';
        DE.Client_Secret__c = 'fakeClientSecret';
        DE.Update_Account_Endpoint__c = '/testEndpoint';
        insert DE;
    }

    @IsTest
    static void testConfirmEmailChangeSuccess(){
        Account a = new Account(FirstName ='forTest',LastName = 'TESTFF',personEmail='test@testForTest.com',
                                 New_Email__c ='newtest@testForTest.com',New_Email_Request_Datetime__c =Datetime.now());
        insert a;
        Blob targetBlob = Blob.valueOf(String.valueOfGmt(a.New_Email_Request_Datetime__c));
        Blob hash = Crypto.generateDigest('SHA-256', targetBlob);
        String hashBase64SHA1 = EncodingUtil.base64encode (hash);

        Test.startTest();
            String result =  LightningConfirmEmailChangeController.confirmEmailChange(hashBase64SHA1, 'changeEmail@testForTest.com', './login');
            System.debug(result);
        Test.stopTest();
        
        Account  acc = [SELECT Id, personEmail, New_Email__c, New_Email_Request_Datetime__c FROM Account LIMIT 1 ];
        /******* ommited the assertion since this is calling webservice and the update will not be actually done, 
        no need to add mock classes since using try.. catch block  *******/
        /* System.assertNotEquals(a.personEmail, acc.personEmail);
        System.assertEquals(acc.New_Email__c, null);
        System.assertEquals(acc.New_Email_Request_Datetime__c, null);
        System.assertEquals('Confirmed', result); */
        
    }

    @IsTest
    static void testInvalidLink(){
        Account a = new Account(FirstName ='forTest',LastName = 'TESTFF',personEmail='test@testfortest.com',New_Email_Request_Datetime__c = Datetime.now());
        insert a;

        Test.startTest();
            String result =  LightningConfirmEmailChangeController.confirmEmailChange('wrongHashCode', 'changeEmail@testForTest.com', './login');
            System.debug(result);
        Test.stopTest();
        
        Account  acc = [SELECT Id, personEmail, New_Email__c, New_Email_Request_Datetime__c FROM Account LIMIT 1 ];
        System.assertEquals(a.personEmail, acc.personEmail);
        System.assertNotEquals(acc.New_Email_Request_Datetime__c, null);
        System.assertEquals('The link is invalid or expired', result);
        
    }

    @IsTest
    static void testInvalidEmail(){
        // should fail before query for the account
        Test.startTest();
            String result =  LightningConfirmEmailChangeController.confirmEmailChange('hashCode', '//#', './login');
            System.debug(result);
        Test.stopTest();
        System.assertEquals(Label.DEInvalidEmailAddress, result );
        
    }

    @IsTest
    static void testAccountNotFound(){
        // not inserting account
        Test.startTest();
            String result =  LightningConfirmEmailChangeController.confirmEmailChange('hashCode', 'changeEmail@testForTest.com', './login');
            System.debug(result);
        Test.stopTest();
        System.assertEquals('Customer  not found', result );
        
    }
}