force-app/main/default/objects/Account/fields/Opt_in_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Request_Date__c</fullName>
    <label>Opt-in Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/Brewer_Registration__c.object-meta.xml
<CustomObject>
    <label>Brewer Registration</label>
    <nameField>
        <label>Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brewer Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brewer_Registration__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brewer Registrations</relationshipLabel>
    <relationshipName>Brewer_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brewer_Registration__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/BrewerRegistrationTrigger__c.field-meta.xml
<CustomField>
    <fullName>BrewerRegistrationTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BrewerRegistrationTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BrewerRegistrationTriggerHandlerTest.cls
/*********************************************************************
Name    :               BrewerRegistrationTriggerHandlerTest
Date    :               12 July 2017
Author  :               Anjerico Caburnay
Description :           Test Class of  for Brewer_Registration__c Object
Current Test Coverage : 100% 
History :       
*********************************************************************/

@isTest
private class BrewerRegistrationTriggerHandlerTest {
  private static testMethod void insertRecord() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.BrewerRegistrationTrigger__c = true;
    insert ts1;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    List<Account> accList = new List<Account>();
    for (integer x = 0; x < 10; x++) {
      Account acct = TestDataBuilder.createAccount();
      acct.recordTypeId = recordTypeId;
      acct.Opt_in_Request_Date__c = Date.Today();
      accList.add(acct);
    }

    insert accList;

    List<Brewer_Registration__c> brewerList = new List<Brewer_Registration__c>();
    for (integer y = 0; y < 10; y++) {
      Brewer_Registration__c brw = new Brewer_Registration__c(
        Serial_Number__c = '123' + y,
        Customer__c = accList[y].Id
      );
      brewerList.add(brw);
    }

    insert brewerList;
  }
}