force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <label>TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/TriggerSettings__c/fields/VoucherTrigger__c.field-meta.xml
<CustomField>
    <fullName>VoucherTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VoucherTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VoucherTriggerHandlerTest.cls
@isTest
public class VoucherTriggerHandlerTest {
  private static testMethod void insertRecord() {
    TriggerSettings__c ts1 = new TriggerSettings__c();
    ts1.VoucherTrigger__c = true;
    insert ts1;

    String recordTypeId = TestDataBuilder.getObjectRecordTypeId(
      Account.SObjectType,
      'Person Account'
    );
    Account accRec = new Account();
    accRec.RecordTypeId = recordTypeId;
    accRec.LastName = 'testing 123';
    insert accRec;

    Voucher__c vouchRec = new Voucher__c();
    vouchRec.Customer__c = accRec.Id;
    vouchRec.Name = accRec.LastName;
    System.debug('voucherRec laman: ' + vouchRec);
    insert vouchRec;

    Test.startTest();
    vouchRec.Contact__c = accRec.PersonContactId;
    update vouchRec;
    Test.stopTest();
  }
}