force-app/main/default/objects/ConsentUrlEncryption__c/ConsentUrlEncryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in the creation of OptIn/Out URLs</description>
    <label>Consent URL Encryption</label>
</CustomObject>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Algorithm__c</fullName>
    <label>Algorithm</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <label>Initialization Vector</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_In_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_In_URL_Template__c</fullName>
    <label>Opt In URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Opt_Out_URL_Template__c.field-meta.xml
<CustomField>
    <fullName>Opt_Out_URL_Template__c</fullName>
    <label>Opt Out URL Template</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsentUrlEncryption__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsentUrlEncryptionSelector.cls
public class ConsentUrlEncryptionSelector {
  public static Map<String, ConsentUrlEncryption__c> getConsentUrlEncryptions() {
    List<ConsentUrlEncryption__c> encryptionRecords = [
      SELECT
        Id,
        Name,
        Algorithm__c,
        Initialization_Vector__c,
        Opt_In_URL_Template__c,
        Opt_Out_URL_Template__c,
        Private_Key__c
      FROM ConsentUrlEncryption__c
    ];

    Map<String, ConsentUrlEncryption__c> consentUrlEncryptionByBrand = new Map<String, ConsentUrlEncryption__c>();
    for (ConsentUrlEncryption__c encryptionRecord : encryptionRecords) {
      consentUrlEncryptionByBrand.put(encryptionRecord.Name, encryptionRecord);
    }

    return consentUrlEncryptionByBrand;
  }
}