force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VoucherTriggerHandler.cls
/*********************************************************************
Name    :       Voucher Trigger Handler
Date    :       19 January 2021
Author  :       Miguel Paguio
Description:    Trigger handler of Voucher for Voucher__c Object
History :       
*********************************************************************/

public class VoucherTriggerHandler{
    //calls all methods Before Insert
    public static void onBeforeInsert(List<Voucher__c> voucherList){
        customerContact(voucherList);
    } 
    
    public static void onAfterInsert(List<Voucher__c> voucherList)
    {
        
    }
    public static void customerContact(List<Voucher__c> voucherList){
        Set<Id> accIds = new Set<Id>();
        for(Voucher__c vouchList : voucherList){
            accIds.add(vouchList.Customer__c);
        }
        if(!accIds.isEmpty()){
            Map<Id, Account> accMap = new Map<Id, Account>([SELECT PersonContactId FROM Account WHERE Id IN: accIds]);
            for(Voucher__c vchList: voucherList){
                if(vchList.Customer__c != null){
                    vchList.Contact__c = accMap.get(vchList.Customer__c).PersonContactId; 
                } 
            }
        }
    }
}