force-app/main/default/objects/ProcessException/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description
  >Payload for exceptions generated in API callouts or callins</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessException/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Response from API callout</description>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessException/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>response code from the API callout</description>
    <label>StatusCode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessException/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>The transaction that this exception belongs to</description>
    <inlineHelpText>The transaction that this exception belongs to</inlineHelpText>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/monitoring/APILoggingUtil.cls
public with sharing class APILoggingUtil {
    // class to create ProcessException records for various Apex error situations (mainly exceptions)

    // general errors that are logged without an exception
     // in case of failed inserts, obviously the sObj attached should be the 'parent' object, not the failed insert (which is rolled back)
     public static void createProcessException(String message, String description, sObject sObj, String category, String transactionId) {
        ProcessException pe = new ProcessException();
        pe.AttachedToId = sObj.id;
        pe.Message = message.left(255);
        pe.Description = description.left(2000);
        pe.Category = category;
        pe.TransactionId__c = transactionId;
        insert pe; // error handling on the creation of an exception report seems a bit over the top...
    }


    // errors from API callouts and callins
    public static void createProcessException(String message, String description, sObject sObj, String category, String transactionId, HttpRequest req, HttpResponse res) {
        ProcessException pe = new ProcessException();
        pe.AttachedToId = sObj.id;
        pe.Message = message.left(255);
        pe.Description = description.left(2000);
        pe.Category = category;
        pe.TransactionId__c = transactionId;
        pe.Payload__c = req.getBody();
        pe.StatusCode__c = res.getStatusCode();
        pe.Response__c = res.getBody();
        insert pe; // error handling on the creation of an exception report seems a bit over the top...
    }
}