force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>AccessToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/ClientID__c.field-meta.xml
<CustomField>
    <fullName>ClientID__c</fullName>
    <label>ClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Query_Limit__c.field-meta.xml
<CustomField>
    <fullName>Query_Limit__c</fullName>
    <description>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</description>
    <inlineHelpText>This is a text value added to the end of the batch query to avoid CPU timeout when we have huge amount of data</inlineHelpText>
    <label>Query Limit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/REST_URL_Del_ConKey__c.field-meta.xml
<CustomField>
    <fullName>REST_URL_Del_ConKey__c</fullName>
    <label>REST_URL_Del_ConKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/REST_URL_Req_Token__c.field-meta.xml
<CustomField>
    <fullName>REST_URL_Req_Token__c</fullName>
    <label>REST_URL_Req_Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/Post_Deletion_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Post Deletion Audit Log</label>
    <nameField>
        <displayFormat>PDA-{0000000}</displayFormat>
        <label>Post Deletion Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Deletion Audit Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/Actual_Deletion_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Deletion_Date__c</fullName>
    <label>Actual Deletion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/DeletionInvokedinMC__c.field-meta.xml
<CustomField>
    <fullName>DeletionInvokedinMC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DeletionInvokedinMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/Salesforce_Person_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Person_Contact_ID__c</fullName>
    <label>Salesforce Person Contact ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLNRULE_DeleteMCRecBatch.cls
/**
*    @author: Alexander Cruz
*    @date: 09.Feb.2018
*    @description: Batch Class that will delete contacts to Marketing Cloud via REST API Call.
*
*    @Revision History
        @author : Wunderman thompson 
        @date: 08/2022
*    
History
    @Fixed by Wunderman Thompson  09/2022
*/
global class CLNRULE_DeleteMCRecBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
  public string Query;

  global CLNRULE_DeleteMCRecBatch() {
    Cleanup_Rules_Settings__c settings = Cleanup_Rules_Settings__c.getInstance();
    String queryLimit = settings.Query_Limit__c != null
      ? settings.Query_Limit__c
      : '';
    Query =
      'Select Salesforce_Person_Contact_ID__c, Actual_Deletion_Date__c from Post_Deletion_Audit_Log__c WHERE DeletionInvokedinMC__c = false ' +
      'AND  Actual_Deletion_Date__c <= TODAY ' +
      queryLimit;
    //Query = 'Select Salesforce_Person_Contact_ID__c, Actual_Deletion_Date__c from Post_Deletion_Audit_Log__c WHERE Salesforce_Person_Contact_ID__c  = \'0035E00000NqwdoQAB\'';
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(Query);
  }

  global void execute(
    Database.BatchableContext BC,
    List<Post_Deletion_Audit_Log__c> scope
  ) {
    try {
      // String accessToken = getMarketingCloudOAuthToken(Cleanup_Rules_Settings__c.getInstance().ClientID__c,Cleanup_Rules_Settings__c.getInstance().ClientSecret__c);
      //system.debug(getMarketingCloudOAuthToken(Cleanup_Rules_Settings__c.getInstance().ClientID__c,Cleanup_Rules_Settings__c.getInstance().ClientSecret__c));
      String res = deleteMarketingCloudContact(scope);
      System.debug(res);

      List<Post_Deletion_Audit_Log__c> pdaToBeUpdated = new List<Post_Deletion_Audit_Log__c>();

      for (Post_Deletion_Audit_Log__c p : scope) {
        p.DeletionInvokedinMC__c = true; //Set the markings
        pdaToBeUpdated.add(p);
      }
      System.debug('**pdaToBeUpdated:' + pdaToBeUpdated);

      //Update Account Records
      if (pdaToBeUpdated.size() > 0) {
        System.debug('**Updating Records**');
        Database.SaveResult[] srList = Database.update(pdaToBeUpdated, false);
        //Debug error records
        for (Database.SaveResult sr : srList) {
          if (sr.isSuccess()) {
            // Operation was successful, so get the ID of the record that was processed
            System.debug(
              '**Successfully updated PostDeletionAuditLog.PostDeletionAuditLogID: ' +
              sr.getId()
            );
          } else {
            // Operation failed, so get all errors
            for (Database.Error err : sr.getErrors()) {
              System.debug('**The following error has occurred.');
              System.debug(err.getStatusCode() + ': ' + err.getMessage());
            }
          }
        }
      }
    } catch (Exception e) {
      System.debug('**The following error has occurred.');
      System.debug('**Error: ' + e.getMessage());
    }
  }

  global void finish(Database.BatchableContext BC) {
  }

  private static String JSONPostCallForToken(String endPoint, String restBody) {
    Http h = new Http();
    HttpRequest r = new HttpRequest();
    r.setTimeout(60000);
    r.setEndpoint(endPoint);
    r.setMethod('POST');
    r.setHeader('Content-type', 'application/json');
    r.setBody(restBody);
    HttpResponse res = h.send(r);
    System.debug(res.getBody());
    return res.getBody();
  }

  public String JSONPostCallForDeletion(String endPoint, String restBody) {
    Http h = new Http();
    HttpRequest r = new HttpRequest();
    r.setTimeout(60000);
    r.setEndpoint(endPoint);
    r.setMethod('POST');
    r.setHeader('Content-type', 'application/json');
    r.setHeader(
      'Authorization',
      'Bearer ' +
      getMarketingCloudOAuthToken(
        Cleanup_Rules_Settings__c.getInstance().ClientID__c,
        Cleanup_Rules_Settings__c.getInstance().ClientSecret__c
      )
    );
    r.setBody(restBody);
    HttpResponse res = h.send(r);
    System.debug(res.getBody());
    return res.getBody();
  }

  public String getMarketingCloudOAuthToken(
    String clientId,
    String clientSecret
  ) {
    String responseBody = JSONPostCallForToken(
      Cleanup_Rules_Settings__c.getInstance().REST_URL_Req_Token__c,
      JSON.serialize(
        new Map<String, String>{
          'grant_type' => Cleanup_Rules_Settings__c.getInstance().Grant_Type__c,
          'client_id' => clientId,
          'client_secret' => clientSecret,
          'account_id' => Cleanup_Rules_Settings__c.getInstance().Account_Id__c
        }
      )
    );
    return ((Map<String, String>) JSON.deserialize(
        responseBody,
        Map<String, String>.class
      ))
      .get(Cleanup_Rules_Settings__c.getInstance().AccessToken__c);
  }

  public String deleteMarketingCloudContact(
    List<Post_Deletion_Audit_Log__c> conts
  ) {
    Set<String> contactIDtoDel = new Set<String>();
    for (Post_Deletion_Audit_Log__c pdalog : conts) {
      contactIDtoDel.add(pdalog.Salesforce_Person_Contact_ID__c);
    }
    system.debug('contactIDtoDel ' + contactIDtoDel);
    String responseBody = JSONPostCallForDeletion(
      Cleanup_Rules_Settings__c.getInstance().REST_URL_Del_ConKey__c,
      JSONbody(contactIDtoDel)
    );
    system.debug('responseBody ' + responseBody);
    return responseBody;
  }

  public string JSONbody(Set<String> contactIds) {
    string str = '{\"ContactTypeId\":0, \"values\":[';

    for (String s : contactIds) {
      str += ('\"' + s + '\",');
    }

    str = str.removeEnd(',');
    str += '],';
    str += ' \"DeleteOperationType\":\"ContactAndAttributes\"}';

    return str;
  }
}