force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_After_DOI_Reminder_Sent_Date_del__c.field-meta.xml
<CustomField>
    <fullName>Days_After_DOI_Reminder_Sent_Date_del__c</fullName>
    <label>Days After DOI Reminder Sent Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Days_to_be_Added_after_DOI_Reminder_Send__c.field-meta.xml
<CustomField>
    <fullName>Days_to_be_Added_after_DOI_Reminder_Send__c</fullName>
    <label>Days to be Added after DOI Reminder Send</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessBuilderSettings__c/ProcessBuilderSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ProcessBuilderSettings</label>
</CustomObject>

force-app/main/default/objects/ProcessBuilderSettings__c/fields/IndividualEmailResultProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>IndividualEmailResultProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IndividualEmailResultProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CLNRULE_BtcDOIReminderMrkDelSchedTest.cls
/*********************************************************************
Name    :      CLNRULE_BtcDOIReminderMrkDelSchedTest
Date    :       07 December 2017
Author  :       William Paredes
Description:    Test class for CLNRULE_BtcDOIReminderMrkDelSchedulable
History : 
History
    @Fixed by Wunderman Thompson  09/2022
*********************************************************************/

@isTest
private class CLNRULE_BtcDOIReminderMrkDelSchedTest {

	private static testMethod void testScheduler() {
        Test.StartTest();
        
            ProcessBuilderSettings__c PBSettings = new ProcessBuilderSettings__c();
            PBSettings.IndividualEmailResultProcessBuilder__c = true;
            insert PBSettings;
            
            Cleanup_Rules_Settings__c CRSetting = new Cleanup_Rules_Settings__c();
            CRSetting.Days_After_DOI_Reminder_Sent_Date_del__c = 7;
            CRSetting.Days_to_be_Added_after_DOI_Reminder_Send__c = 14;
            insert CRSetting;

            
            String recordTypeIdSt = TestDataBuilder.getObjectRecordTypeId(Account.SObjectType, 'Person Account');
            List<Account> accList = new List<Account>();
            for(integer x=0;x<=50;x++){
                Account acct = new Account(LastName='AccountTest '+x, recordTypeId = recordTypeIdSt);
                accList.add(acct);
            }
            insert accList;
            
            CLNRULE_BtcDOIReminderMrkDelSchedulable sh1 = new CLNRULE_BtcDOIReminderMrkDelSchedulable();      
            String sch = '0 0 15 * * ?';
            system.schedule('Test run schedulable', sch, sh1);
        Test.stopTest();
	}

}