force-app/main/default/objects/Cleanup_Rules_Settings__c/Cleanup_Rules_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cleanup Rules Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>AccessToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/ClientID__c.field-meta.xml
<CustomField>
    <fullName>ClientID__c</fullName>
    <label>ClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/REST_URL_Del_ConKey__c.field-meta.xml
<CustomField>
    <fullName>REST_URL_Del_ConKey__c</fullName>
    <label>REST_URL_Del_ConKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cleanup_Rules_Settings__c/fields/REST_URL_Req_Token__c.field-meta.xml
<CustomField>
    <fullName>REST_URL_Req_Token__c</fullName>
    <label>REST_URL_Req_Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/Post_Deletion_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Post Deletion Audit Log</label>
    <nameField>
        <displayFormat>PDA-{0000000}</displayFormat>
        <label>Post Deletion Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Deletion Audit Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/Actual_Deletion_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Deletion_Date__c</fullName>
    <label>Actual Deletion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/DeletionInvokedinMC__c.field-meta.xml
<CustomField>
    <fullName>DeletionInvokedinMC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DeletionInvokedinMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/Salesforce_Person_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Person_Contact_ID__c</fullName>
    <label>Salesforce Person Contact ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Deletion_Audit_Log__c/fields/To_be_Deleted_Date__c.field-meta.xml
<CustomField>
    <fullName>To_be_Deleted_Date__c</fullName>
    <label>To be Deleted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CLNRULE_DeleteMCRecBatchTest.cls
/* 

History
    @Fixed by Wunderman Thompson  09/2022
*/
@IsTest
public class CLNRULE_DeleteMCRecBatchTest {
    
    static testMethod void myUnitTest() {
        Cleanup_Rules_Settings__c CLN_Settings = new Cleanup_Rules_Settings__c(SetupOwnerId=UserInfo.getOrganizationId());
        CLN_Settings.ClientID__c = '00000000';
        CLN_Settings.ClientSecret__c = '1111111111';
        CLN_Settings.AccessToken__c = 'access_token';
        CLN_Settings.REST_URL_Del_ConKey__c = 'test.com';
        CLN_Settings.Grant_Type__c = 'autorization_code';
        CLN_Settings.REST_URL_Req_Token__c = 'test2.com';
        insert CLN_Settings;
        
        Datetime dateTimetemp = System.now();
        Date dateTemp = Date.newInstance(dateTimetemp.year(),dateTimetemp.month(),dateTimetemp.day());

        /* We can use  mock classes to get higher coverage for http callouts but we don't have time & 
        since the coverage is >75% we can already push to production lik this  */
        
        
        Test.startTest();
        Post_Deletion_Audit_Log__c log = new Post_Deletion_Audit_Log__c (Salesforce_Person_Contact_ID__c='0031l00000YAUk1AAH', DeletionInvokedinMC__c=false, 
                                                                         Actual_Deletion_Date__c = dateTemp, To_be_Deleted_Date__c = dateTemp);
        Insert log;
        
        CLNRULE_DeleteMCRecBatch mcdel = new CLNRULE_DeleteMCRecBatch();
        Database.executeBatch(mcdel);     
        Test.stopTest();
        
    }   
    
}