force-app/main/default/objects/IERRelatedList__c/IERRelatedList__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom settings is for the IER Related List Visualforce Page</description>
    <label>IER Related List</label>
</CustomObject>

force-app/main/default/objects/IERRelatedList__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IERRelatedList__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IERRelatedList__c/fields/Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Page_Size__c</fullName>
    <label>Page Size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IERRelatedListController_Test.cls
@isTest
public class IERRelatedListController_Test {
  @isTest
  static void testCallout() {
    Test.setMock(HttpCalloutMock.class, new IERHTTPCalloutMock());
    string accessToken = IERRelatedListHelper.getMarketingCloudOAuthToken(
      'testClientID',
      'testClientSecret'
    );
    string responseXML = IERRelatedListHelper.performMCAction(
      accessToken,
      'testOnly'
    );
    IERRelatedListHelper.XMLParserResult parserResult = new IERRelatedListHelper.XMLParserResult();
    parserResult = IERRelatedListHelper.XMLParser(responseXML);
  }
  @isTest
  static void IERRelatedListPageResultWithPageSize1() {
    IERRelatedList__c IERSetting = new IERRelatedList__c();
    IERSetting.Client_ID__c = 'testClientID';
    IERSetting.Client_Secret__c = 'testClientSecret';
    IERSetting.Page_Size__c = 1;
    insert IERSetting;

    Account testAcc2 = new Account();
    testAcc2.Name = 'TESTACCOUNT';
    testAcc2.Id = '0016E00000Y0ySZ';
    Test.setMock(HttpCalloutMock.class, new IERHTTPCalloutMock());
    PageReference pageRef = Page.IERRelatedList;
    Test.setCurrentPage(pageRef);
    test.startTest();
    IERRelatedListController IERCont = new IERRelatedListController(
      new ApexPages.StandardController(testAcc2)
    );
    IERCont.moveToNext();
    IERCont.moveToPrev();
    IERCont.moveToLast();
    test.stopTest();
  }
  @isTest
  static void IERRelatedListPageResultWithPageSize0() {
    IERRelatedList__c IERSetting = new IERRelatedList__c();
    IERSetting.Client_ID__c = 'testClientID';
    IERSetting.Client_Secret__c = 'testClientSecret';
    IERSetting.Page_Size__c = 0;
    insert IERSetting;

    Account testAcc2 = new Account();
    testAcc2.Name = 'TESTACCOUNT';
    testAcc2.Id = '0016E00000Y0ySZ';
    Test.setMock(HttpCalloutMock.class, new IERHTTPCalloutMock());
    PageReference pageRef = Page.IERRelatedList;
    Test.setCurrentPage(pageRef);
    test.startTest();
    IERRelatedListController IERCont = new IERRelatedListController(
      new ApexPages.StandardController(testAcc2)
    );
    test.stopTest();
  }
  @isTest
  static void IERRelatedListPageResultWithPageSize0NotInConsumerDetailPage() {
    IERRelatedList__c IERSetting = new IERRelatedList__c();
    IERSetting.Client_ID__c = 'testClientID';
    IERSetting.Client_Secret__c = 'testClientSecret';
    IERSetting.Page_Size__c = 0;
    insert IERSetting;

    Account testAcc2 = new Account();
    testAcc2.Name = 'TESTACCOUNT';
    Test.setMock(HttpCalloutMock.class, new IERHTTPCalloutMock());
    PageReference pageRef = Page.IERRelatedList;
    Test.setCurrentPage(pageRef);
    test.startTest();
    IERRelatedListController IERCont = new IERRelatedListController(
      new ApexPages.StandardController(testAcc2)
    );
    test.stopTest();
  }
}